### ISSUE TITLE
Développement du parcours "Je ne sais pas par où commencer"

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/transition-ecologique-entreprises-widget#109]
## Contexte

À la demande des partenaires, l'entreprise peut arriver sans besoin précis en tête et n'a pas nécessairement un projet. Il a été demandé de développer deux parcours parallèles "Je ne sais pas par où commencer" et "Avec un objectif précis" qui seront challengés par les tests utilisateurs.

Ce ticket porte sur la création d'une première version du parcours "Je ne sais pas par où commencer". Nous avons décidé en séance de d'abord implémenter un parcours générique (le même quel que soit le secteur d'activité), pour pouvoir ensuite travailler, secteur par secteur, sur l'affinement du parcours et des dispositifs proposés.

## User story

En tant qu'utilisateur, qui n'ai pas d'idée précise sur les actions que je veux mener mais qui souhaite m'engager dans la transition écologique des entreprises, j'aimerais qu'on me présente un panorama d'aides, adaptés à ma situation (ie pour lesquels je suis éligibles, et qui sont pertinentes étant donné mon domaine d'activité), pour : 
- m'accompagner dans l'identification des actions les plus pertinentes à mener pour mon entreprise
- ou me suggérer des actions pertinentes à mener pour mon entreprise

Je ne souhaite pas que me soient présentées des aides très pointues.  

## Critère d'acceptation

- [x] Après le premier call-to-action, avoir une bifurcation au démarrage du parcours (cf. [maquette](https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=2034%3A162460&mode=design&t=EKaMoSxiWtTyMDth-1))
- [x] Dans le cas "Je ne sais pas par où commencer" pouvoir saisir sont SIRET,  puis répondre aux questions spécifiées sur la maquette
- [x] Dans le cas "J'ai un objectif précis en tête" poursuivre le parcours tel qu'actuellement avec un objectif à sectionner

**Comment by JulienParis** [comment]
linked to #108 eand #110

**Comment by JulienParis** [comment]
cf #117
