### ISSUE TITLE
🖥️ Ajustements Edito parcours "Je ne sais pas..."

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/transition-ecologique-entreprises-widget#118]
**Corrections EDITO**

- [x] Modifier les choix pour les réponses à la question "Possédez-vous un ou plusieurs véhicules motorisés dans votre entreprise ?" ✅ Oui / ❌ Non, l’entreprise ne possède aucun véhicule motorisé / Je ne sais pas

- [x] Modifier la question _Enjeu déchets_ pour "Avez-vous l’envie de progresser sur la gestion de vos déchets ?" + les choix de réponses : 👍 Oui, j’aimerais faire mieux ! / 🤓 Non, je fais déja mon maximum / 👎 Non, la gestion des déchets n’est pas un enjeu pour moi / Aucune idée

- [x] Modifier la question _Matières premières_ pour "Avez-vous pour objectif de réduire vos pertes de matières premières ou votre production de déchets ?" + La réponse "Je ne sais pas / Je ne suis pas concerné"

- [x]  Modifier la réponse 3 à la question _Enjeu Eau_ pour "Aucune idée !"
- [x] Modifier la question _Energie Source principal_e par "La réduction de vos consommations d’énergie est-elle une priorité pour vous ?" 👍 Oui, c’est une priorité / ❌ Ce n’est pas ma priorité / Je ne sais pas
- [x] Modifier la thématique "Votre Stratégie" par "Votre stratégie environnementale", modifier la couleur pour le violet #646EFA et l'illustration [https://drive.google.com/file/d/1mewgEsKx_lHbv2WneK7sQvj9w2fZJ4P0/view?usp=sharing](url)
- [x] Modifier le texte d'intro sur la page de résultat "D’après les informations que vous avez renseigné, voici les accompagnements dont vous pouvez bénéficier pour diminuer l’empreinte écologique de votre entreprise."

- [x] Pour le bloc contact sur la page de résultats, modifier le texte pour "Vous souhaitez bénéficier de cet accompagnement ?" puis "👋 Un conseiller vous contactera dans les 5 jours" 
- [x]  Pour le bloc contact sur la page de résultats, rendre obligatoire tous les champs + ajouter astérisque (*)
- [x] Pré-remplir le message dans le champ Besoin par : 
"Bonjour,
Mon entreprise a une activité de service de (pré-remplir code naf)
J'aimerais bénéficier de l’accompagnement/ du financement/du prêt (+ nom du dispositif) 
Merci d'avance pour votre appel" 
cf maquette [https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=2519%3A81402&mode=design&t=nFBZ03Ne1tWhyEMX-1](url)

**Comment by JulienParis** [comment]
Commentaires: 

Petites complexités à bien reconnaître automatiquement quel adjectif démonstratif ("ce", "cet", "cette") utiliser dans la génération de l'entête du formulaire "Vous souhaitez bénéficier de cet **acompagnement** ?" car il peut y avoir plusieurs cas selon la nature de l'aide : 

- Dans les données actuellement : 
  - "accompagnement" > "cet"
  - "financement" > "ce"
- Potentiellement :
  - "prêt" > "cet"
  - "appel à projet" > "cet"

Même problème dans le message à pré-remplir dans le champs "Votre message" (ou "Besoin") du formulaire

**Comment by JulienParis** [comment]
## Résultats / évolutions de cette PR 

### Rendu du formulaire
 
![Capture d’écran 2023-09-11 à 15 54 18](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/abce81b4-8afc-4699-94b1-a53e1dea9baa)

### MAJ des questions

![Capture d’écran 2023-09-11 à 15 56 01](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/ba646cd2-9ce0-43a9-8d4f-83f336a6489b)

![Capture d’écran 2023-09-11 à 15 57 02](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/be16de10-64a7-4d13-ba13-043d8eef8d41)

![Capture d’écran 2023-09-11 à 15 59 27](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/83b108d3-ac07-461d-8d48-137d57a1a69e)

![Capture d’écran 2023-09-11 à 15 59 37](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/f0fd4fe9-b257-4662-a3aa-70b4f0c896e3)

![Capture d’écran 2023-09-11 à 15 59 54](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/7c867bd4-87f6-4f14-a355-03afa454dd4d)

![Capture d’écran 2023-09-11 à 16 00 05](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/548c3e9f-1644-4e20-8832-29c0f52306da)

![Capture d’écran 2023-09-11 à 16 00 19](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/5fc182df-2ae4-461c-bb62-24c226e63c11)
