### ISSUE TITLE
🖥 Modif front avec les thématiques startup

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#123]
Modifier les objectifs du parcours "j'ai un objectif précis en tête" pour respecter les décisions prises dans le ticket #122  :

🌱 Mesurer mon impact environnemental et le réduire
⚡️ Améliorer la performance énergétique de mon entreprise
💧 Diminuer ma consommation d'eau
🏢 Rénover mon bâtiment
🚲 Engager une démarche de mobilité durable
🗑 Mieux gérer mes déchets
🏭 Améliorez la performance environnementale de mes produits et services
🧑‍🎓 Former ou recruter sur la transition écologique

cf [Maquette figma](https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=2613%3A119340&mode=design&t=dFQBswP8o1HXy5Ne-1)

### Tâches 

- [x] Proposer dans le questionnaire les réponses telles que décrites ci-dessus. 
- [x] Enregistrer les réponses selon ce modèle de données, avec les réponses non sélectionnées qui prennent la valeur "non" et l'option sélectionnée la valeur "oui"

**Comment by JulienParis** [comment]
Intégration dans #147, commit https://github.com/betagouv/transition-ecologique-entreprises-widget/pull/147/commits/7796f5cc0078051dcc97a3fc1f464c0fc05b07e5

**Comment by pierrecamilleri** [comment]
Est-ce que je peux proposer des noms différents ?

- `est impact carbone` est obsolète, on s'était mis d'accord qu'on parlait plutôt d'impact environnemental. Proposition `est mon impact environnemental`
- du coup (mais même sans ça), `est ma performance environnementale` devient très ambigü, et le fait qu'on doive spécifier en commentaire `# ecoconception` me laisse penser que `est l'écoconception` est nettement mieux. 
- Pa

**Comment by JulienParis** [comment]
@pierrecamilleri ok pour modifier ces libellés de conditions publicodes. Je vais faire les modifs dans la PR. Il faudra juste vérifier ensemble que ces modifs sont bien cohérentes avec les yaml, leur processus de génération et les tests, et les pistes de question.

**Comment by pierrecamilleri** [comment]
oui, ces modifs sont liés et passent les tests uniquement avec les nouvelles données, PR #155.

Ce que je te propose, c'est que tu opères les modifs pour le questionnaire, mais tu laisses l'interface publicode inchangée, et je la change dans la PR concernée. Le filtrage ne sera pas effectif avant ces changements, mais ça ne fera pas échouer la CI.

**Comment by JulienParis** [comment]
A priori tout est intégré maintenant en preprod, on pourra considérer ce ticket fermé quand le passage en `preprod > prod` sera fait avec la #159
