### ISSUE TITLE
🖥 URLS slugs

### ISSUE THREAD

**Issue by JulienParis** [betagouv/transition-ecologique-entreprises-widget#124]
~A faire post-novembre~

Remis en prio par #179

**Comment by yvalentin** [comment]
Vue router scroll behavior  

https://router.vuejs.org/guide/advanced/scroll-behavior.html

**Comment by JulienParis** [comment]
Note: résolution avec la (grosse) PR #204

**Comment by ColineLebaratoux** [comment]
@JulienParis Est-ce que c'est le sujet de la #277 ?
