### ISSUE TITLE
✏️ Evolutions UX / UI / edito suite aux tests utilisateurs

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#137]
- [x]  Supprimer la question (batiment>surface)

- [x] modifier la formulation de la question déchets _"Aimeriez-vous améliorer la gestion des déchets de votre activité ?"_

- [x]  Revenir aux tranches pour le nb de salariés. (à la place du champ libre)

- 🧍‍Moins de 5 employés
- 👬️‍ Entre 5 et 49 employés
- ‍️👫👭 Entre 50 et 249 employés
+(ajouter une sélection intermédiaire ici ?)
- ‍️👫👭👫 Plus de 250 employés

- [x]  modifier le texte l'encart jaune_"Nous allons vous poser quelques questions pour pouvoir identifier les accompagnements et de financements dont vous pouvez bénéficier."_ [cf maquette](https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=2694%3A64798&mode=design&t=HcSscdLl1w4xmqGP-1)

- [x]  Sur la fiche dispositif, dérouler les acronymes de chaque opérateur
- ADEME, agence de la transition écologique
- Bpifrance, Banque Publique d'Investissement
- Chambre de Métiers et de l'Artisanat (CMA)
- Chambre de Commerce et d'Industrie (CCI)
- Direction départementale des finances publiques
- Agence de services et de paiement (ASP)
- Ministère de la Transition Ecologique et Solidaire
- Agence de l'Eau 
- ORACE, Organisation Régionale pour l'Abaissement de la Consommation Energétique

- [x] Sur la page résultats, ajouter la donnée du cout précédée de la mention “coût ou “montant de l’aide” sur la vignette du dispositif 

- [x] dans le formulaire de contact, remplacer "vous souhaitez bénéficier de cet accompagnement ?" par "Cet accompagnement vous intéresse ?" / "Ce financement vous intéresse ?" / "Ce prêt vous intéresse ?"
- [x] dans le formulaire de contact, ajouter le nom de l'opérateur "Envoyez votre demande, un conseiller de [nom de l'opérateur]  vous contactera dans les 5 jours [cf maquette](https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=3075%3A120753&mode=design&t=HcSscdLl1w4xmqGP-1)

- [x] cf ticket #135 Design de la page erreur lors de l'envoi du formulaire (genre si la personne met un email invalide ou un email qu'on a déjà dans Brevo)
- signale à l'utilisateur qu'il y a une erreur lors de l'envoi du formulaire ;
- affiche notre email de contact si la personne souhaite nous écrire pour nous signaler cette erreur ;
- contient le message d'erreur histoire qu'on puisse mieux identifier le problème.

**Comment by JulienParis** [comment]
Je regrouperai les modifs liées à cette issue sur la PR #147
