### ISSUE TITLE
🖥️ Modification du message dans le formulaire pour avoir plus d'informations sur le besoin de l'entreprise

### ISSUE THREAD

**Issue by JulienParis** [betagouv/transition-ecologique-entreprises-widget#157]
En tant qu'opérateur je souhaiterai avoir plus d'information sur le besoin de l'entreprise.
Pour s'approcher du formalisme Place des Entreprises le message serai le suivant :

```
Bonjour,

Mon entreprise a une activité de [activité NAF]
Le dispositif "[titre du dispositif]" pourrait m'intéresser car j'ai pour projet de  
J'ai besoin d'être accompagné(e) sur 

Merci d'avance pour votre appel
```
[activité NAF] est l'activité du code NAF, sur un niveau de sous-classe. [Exemple](https://www.insee.fr/fr/metadonnees/nafr2/sousClasse/55.10Z?champRecherche=false) "Hôtels et hébergement similaire" pour le code 55.10Z 

[titre du dispositif] exemple : "TPE Gagnantes" ou "Diag Eco-flux"

Attention : Agrandir sans doute la zone de texte pour voir tout le message.

**Comment by yvalentin** [comment]
Ceci peut être tester sur l’environnement de staging:

https://tee-frontend-staging.osc-fr1.scalingo.io

@jbledevehat @ColineLebaratoux

**Comment by jbledevehat** [comment]
@yvalentin Test Ok, ça peut aller en prod 👍

**Comment by JulienParis** [comment]
Note: résolu via la PR #169
