### ISSUE TITLE
Modifier les données / fusionner les dispositifs suivants

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#158]
- [x] refusionner FTD diag et financement car on a besoin de voir qu’il y a des € à la clé
 =>  La ligne "Fonds Tourisme Durable (OLD)" est à supprimer

- [x] Fusionner les 2 lignes Booster Éco-Énergie Tertiaire <>1000m2 (puisqu'on supprime la question de la superficie des locaux)
_=> La ligne "Booster Éco-Énergie Tertiaire (OLD)" est à supprimer

- [x] audit de certification/labelisation ligne 29 est un accompagnement sectoriel : Hôtellerie & restauration. A reformuler en contextualisant comme pour fonds tourisme durable "Restaurateurs & hébergeurs..."

**Comment by ColineLebaratoux** [comment]
@jbledevehat @pierrecamilleri on ne garde qu'uns seule ligne pour Visite énergie ? 
Dans ce cas comment traiter les coûts reste à charge différents & durée d'accompagnement ?

**Comment by pierrecamilleri** [comment]
Pas de solution miracle de mon côté, à part trouver une formulation générique (`Selon opérateur du dispositif`, ou possiblement un  poil plus précis), je n'ai pas d'idée. 

J'ai créé une issue sur (entre autres) la gestion des dispositifs CCI *ou* CMA, n'hésites pas à rajouter une case à cocher pour rétablir les bonnes informations de coûts reste à charge et durée de l'accompagnement (ou je peux le faire), cf #163
