### ISSUE TITLE
Typages des fichiers de type "Track**.ts" dans dossier `packages/web/questionnaire`

### ISSUE THREAD

**Issue by JulienParis** [betagouv/transition-ecologique-entreprises-widget#161]
Example : 

```js
import type { Track } from '../types'

export const needs: Track = {
...
```

**Comment by JulienParis** [comment]
Note: résolution dans #210 (à confirmer @yvalentin)

**Comment by yvalentin** [comment]
> Note: résolution dans #210 (à confirmer @yvalentin)
![image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/1521862/abbf34a7-8118-4a93-a325-074fb5b84761)
