### ISSUE TITLE
Filtrer les dispositifs régionaux sans SIRET

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#162]
En tant qu'utilisateur pouvoir visualiser (ou non) le dispositif régional me concernant (ou non)

- [x] Data > Inclure la zone géographique (régional) dans le dispositif 
- [ ] Dev > En cas d'absence de SIRET, pouvoir choisir la région (13 métrop + DOMTOM) à travers une page de select
   - Pour info, le champs libre pour requête dans la base adresse dans le cas d'absence de SIRET (bench côté API Adresse) sera pour plus tard
   - [ ] Voir [maquette figma](https://www.figma.com/proto/tHgzORFkJYTVspsQgR2kg6/TEE-V5?page-id=1436%3A131849&type=design&node-id=3538-33342&viewport=-12372%2C174%2C0.3&t=SzoOr0DkReR9eK8t-1&scaling=min-zoom&starting-point-node-id=3538%3A33342&show-proto-sidebar=1&mode=design) >> [Carte Design #160](https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/160)
- [x] Data > Dans le cas d'une saisie d'un SIRET filtrer au plus proche des données régionales

Critères d'acceptabilité 
- [ ] Filtrer dans les 2 cas de figures (SIRET ou non) sur des dispositifs régionaux

**Comment by JulienParis** [comment]
Note: résolution en cours dans les PR #222 et #227

**Comment by pierrecamilleri** [comment]
#227 est sur le sujet des secteurs d'activité et non des régions ;)
