### ISSUE TITLE
Amélioration de la performance du filtrage avec publicodes

### ISSUE THREAD

**Issue by pierrecamilleri** [betagouv/transition-ecologique-entreprises-widget#164]
### Contexte

Le filtrage se fait aujourd'hui côté client, avec publicodes. 

### Problématique 

Il a été constaté, après l'ajout de plus de 40 dispositifs, un temps de filtrage nettement perceptible, puis après mesure sur ma machine, qui avoisinent 2 secondes. (machine qui était performante il y a 10 ans)

### Tâches

- [x] N'ayant pas anticipé de problème de ce côté-là, j'évalue en réalité deux fois chaque dispositif, donc un easy fix peut déjà diviser le temps quasi par 2. 
- [x] Si le temps de chargement est toujours un sujet temporairement, alors une petite animation de chargement est envisageable
- [x] Dans l'idéal, si on veut maîtriser ce paramètre, alors il s'agit d'envisager le filtrage côté serveur.

**Comment by pierrecamilleri** [comment]
Petit diagnostic de ce qui prend du temps : 

- La création du moteur publicodes pour 1 dispositif (~200 ms sur ma machine)
- L'injection de données (~80 ms)
- L'évaluation (~10 ms)

Deux axes d'amélioration en conséquence :

- Une fois le filtrage effectué en backend, les moteurs publicodes pour chaque dispositif pourront être créés à la création du serveur. Gain espéré : temps de chargement divisé par ~3
- Si jamais ce n'est toujours pas satisfaisant, on peut consolider tout le code publicodes et injecter les données qu'une seule fois (gain espéré : nouveau temps de chargement divisé par ~10)

Aucune inquiétude donc sur la performance en cas de montée en charge (plus de dispositifs, plus de conditions à gérer).

**Comment by JulienParis** [comment]
Note: la seconde piste d'amélioration "light" (ajouter un loader) a un vieux ticket dédié que je viens juste de passer en issue #237 

Cette piste est aussi en cours d'exploration par @yvalentin sur la [branche `feature/button-loader`](https://github.com/betagouv/transition-ecologique-entreprises-widget/tree/feature/button-loader). On en a un peu parlé ensemble l'autre jour.
