### ISSUE TITLE
🖥️ Afficher la durée et le montant des prêts

### ISSUE THREAD

**Issue by pierrecamilleri** [betagouv/transition-ecologique-entreprises-widget#165]
### Contexte

La [PR 155](https://github.com/betagouv/transition-ecologique-entreprises-widget/pull/155) ajoute les premiers dispositifs qui sont des `prêts`. Le modèle de donnée a évolué avec ces ajouts, notamment avec les champs `montant du prêt` et `durée du prêt`.

Il s'agit donc d'afficher ces informations à l'utilisateur dans la fiche dispositif.

### Critères d'acceptation 

- [x] Les fiches dispositifs des prêts indiquent deux nouveaux cadres "Montant" et "Durée".
- [x] La donnée affichée dans ce cadre correspond aux données `montant du prêt` et `durée du prêt` respectivement.
- [x] Les illustrations sont identiques aux illustrations `montant du financement` (pour un financement) et `durée de l'accompagnement` (pour un accompagnement) respectivement.

**Comment by JulienParis** [comment]
Ces évolutions sont normalement passés en `preprod` : 

_Nota_ : Petite entorse à nos échanges sur la #155 ces modifications ont été inclues dans la branche `p-add-programs` lors de ma _review_ car les modifs étaient plus évidentes à repérer lors de la lecture des fichiers modifiés

**Comment by JulienParis** [comment]
Je rebondis pour signaler @yvalentin que je vais lier cette issue à une PR (pas encore créée) et une branche `feature/program-preview-info` qui aura pour but d'intégrer l'affichage des infos de `montant / coût` demandées en #168  

>  Sur la page résultats, ajouter la donnée du cout précédée de la mention “coût ou “montant de l’aide” sur la vignette du dispositif

Dans les critères d'acceptation entrés en description il n'est pas précisé où dans les front ces infos sont censées apparaître, pour ma part j'estime que cette description englobe l'affichage sur les cartes miniature.

**Comment by JulienParis** [comment]
PR prête avec _screenshot_ du résultat : #186
