### ISSUE TITLE
Mini correction UI sur les CTA

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#168]
---

Sur les parcours "je ne sais pas par ou commencer" ou "j'ai un objectif en tête"

- [x] sur le CTA "suivant" inverser l'emplacement de l'icone flèche après la mention "suivant"
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/d97f1364-0cd3-46d9-96ef-e47eb4a76a0d)

---
sur le formulaire de contact
- [x] Sur le CTA "envoyer" du formulaire de contact, inverser la place de la flèche après le mot "envoyer"

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/e799c81d-597b-495f-9d5f-e9f172c9d2de)

**Comment by celinebagault** [comment]
- [ ] Diag Ecoconception : Corriger "impact environnementale" -> "impact environnemental"

<img width="1316" alt="Capture d’écran 2023-10-17 à 10 55 23" src="https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/147497588/6101e746-3c2e-48df-9590-1a8635bb2e26">

- [ ] Visite Énergie : Corriger "plan d'actions" -> "plan d'action" (deux endroits)

<img width="1242" alt="Capture d’écran 2023-10-17 à 11 39 05" src="https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/147497588/86965477-c04a-45a7-8c4a-d52e04647c84">


<img width="738" alt="Capture d’écran 2023-10-17 à 11 39 11" src="https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/147497588/64185e87-6c53-4ba3-a410-4d3802acf9de">

**Comment by ColineLebaratoux** [comment]
@yvalentin je ne vois pas la correction sur staging. Normal?

**Comment by JulienParis** [comment]
Note: résolution dans #212 

Note: @ColineLebaratoux Je pense que c'est normal que tu ne voies pas encore la modif ni en `preprod` ni en `staging` car les modifs de @yvalentin de la PR #212 ne sont pas encore mergées dans `preprod`, et moi je ne les avais pas inclues dans la branche "Frankenstein" de démo qui est actuellement déployée en `staging`. 
Je pense que Yohan pourra taguer ce ticket en `need validation` une fois que la PR aura été mergée dans `preprod` (si j'ai bien pigé notre nouveau process)

**Comment by ColineLebaratoux** [comment]
Oui tout a fait, je ne regarde plus les tickets sur staging 🙈
