### ISSUE TITLE
🖥 Correction page de résultats quand pas de résultats

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#171]
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/69a903d6-6aed-4cda-94ac-eda3d90aa8ff)

modifier la page de résultats quand aucun résultat : 

- [x] supprimer "Titre "vos résultats" + sous titre" et remplacer par le message 
- ~~[ ] Lien vers "tous les résultats" = on ignore les choix du formulaire (on conserve les filtres secteur activité, géographique, effectif)~~
- [x] ajouter le bandeau contacter un conseiller

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/3f41a8e4-ff1a-4533-a909-53075b514cac)

https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=3454%3A24929&mode=design&t=Ih3VNPKwcMzOIzrH-1

**Comment by JulienParis** [comment]
Partiellement résolu avec PR #201 (manque le bandeau "Vous souhaitez contacter un conseiller ?" et le lien vers l'annuaire

**Comment by JulienParis** [comment]
Note : Problème du bandeau résolu en #267 avec PR #285

**Comment by JulienParis** [comment]
Note : Le lien vers "Tous les résultats" est un peu moins trivial qu'il n'y paraît, car rediriger vers tous les résultats suppose de se pencher un peu plus sur la question des URLS cf #292 

Suggestion: @ColineLebaratoux je propose que pour le moment on fasse une carte dédiée pour l'ajout du lien "Voir toutes les aides" dans le cas où l'utilisateur à zéro résultat. Le but ici est de commencer à périmétrer les issues et de moins regrouper de sujets sur une issue, afin de pouvoir les traiter, les clore, et les intégrer de façon plus fluide.

Dans un premier temps ce lien peut se contenter de faire ce que tu proposais : 
> Lien vers "tous les résultats" = on ignore les choix du formulaire (on conserve les filtres secteur activité, géographique, effectif)
... Mais il faudra forcément revenir sur ce sujet à cause des développements qu'occasionnera la #292
