### ISSUE TITLE
Mettre en place le tri des résultats sur les 2 parcours (version simplifiée)

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#174]
### tri par type d'aide + coût reste à charge (**Version simplifiée** )

⇒ tri de la page de résultats du parcours **“je ne sais pas par où commencer”** 

- [x]  Trier les dispositifs par type, dans l’ordre :
1/ les accompagnements gratuits (chaine de caractère "gratuit" dans la colonne "cout reste à charge")
2/ les autres accompagnements 
3/ les financements 
4/ les prêts

⇒ le tri de la page de résultats du parcours **“j’ai un projet en tête”** 

- [x]  Trier les dispositifs par type, dans l’ordre : 
1/ les financements
2/ les prêts 
3/ les accompagnements payants
4/ les accompagnements gratuits

**Comment by ColineLebaratoux** [comment]
Proposition vérifiée en test utilisateur

**Comment by ColineLebaratoux** [comment]
Pour aller plus loin distinguer les financements d'études et financements à l'investissement pour le parcours "je ne sais pas par ou commencer"

 Trier les dispositifs par type, dans l’ordre :
1/ les accompagnements gratuits
2/ les autres accompagnements
3/ les financements d'études
4/ les financements à l'investissement
5/ les prêts

**Comment by JulienParis** [comment]
à décider qui de @pierrecamilleri ou @JulienParis prend le ticket

**Comment by ColineLebaratoux** [comment]
Youhou ! Un grand pas pour le parcours utilisateur 🎉
