### ISSUE TITLE
🖥️ Fin du site legacy

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#179]
- [x] Développer la [page d'accueil à l'image de la maquette](https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=3028-95808&mode=design)
   - [x] ~~Header sans liens (dans un premier temps)~~
   - [x] Dans les bloc de texte thématique, le lien "Je me lance >" sont identique au call-to action en haut de page
   - [x] La zone de bas de page doit avoir le mail "france-transition@beta.gouv.fr" et non le mail @dev-durable
- [x] Recréer les pages du footer à l'identique
   - [ ] ~~Plan du site (obligation RGAA)~~
   - [x] Page d'accessibilité (obligation RGAA)
   - [x] Mentions légales
   - [x] Données personnelles
   - [x] Stats renvoyant vers la page Matomo
   - [x] Code source (lien à changer vers notre dépot GitHub)
   - [x] ~~API & iframe~~ 

Critères d'acceptabilités 

- [x] Avoir une page d'accueil à l'image de la maquette
- [x] URLS Slugs à avoir
    - [ ] https://mission-transition-ecologique.beta.gouv.fr/aides/tremplin correspondant à la page du dispositif Tremplin
- [ ] ~~Boutons back opérationnel~~

**Comment by JulienParis** [comment]
Note: Les cases que j'ai cochées correspondent à des avancées et intégrations dans la branche de travail `feature/full-vue`. Cette branche va bientôt être mergée dans `preprod` (cf [204](https://github.com/betagouv/transition-ecologique-entreprises-widget/pull/204) )

**Comment by JulienParis** [comment]
Update: Les différents changements listés (et non barrés) de la liste sont aujourd'hui tous passés en `prod`, à l'exception de la partie sur les URLs.

Pour mémoire les items barrés ont été reportés sur des issues dédiées : 

- Bouton "back" opérationnel : #277 
- Paln du site : voir #248 
- URLs : #292

**Comment by JulienParis** [comment]
@ColineLebaratoux vu que les items barrés ont désormais leur issue dédiée je propose qu'on ferme ce ticket n. 179

**Comment by jbledevehat** [comment]
Je confirme. On l'envoie en Done. Car c'est moi qui l'ai traité hier et barrés ces lignes.
