### ISSUE TITLE
Voir les critères d'eligibilité dans la fiche dispositif

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#183]
Ajouter les données d'éligibilité issues des dispositifs (sans évaluation dans un premier temps)
https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=4167%3A87176&mode=design&t=yGmpUNUPsuXiV6mB-1

- [x] **🏢 Secteur d’activité**
- afficher les données de la colonne éligibilité sectorielle
- ou si aucune condition, afficher "Tous secteurs d'activité"
- afficher les données de la colonne éligibilité NAF uniquement si des conditions sont mentionnées

- [x] **📍 Secteur géographique**
- afficher les données de la colonne "Zones géographiques Régional"
- afficher les données de la colonne "Zones géographiques Spécifique" ou "Zones géographiques Départemental" uniquement si des conditions sont mentionnées
- ou si aucune condition, afficher "France et territoires d'outre-mer"

- [x] **👫  Taille de l’entreprise**
- afficher les données de la colonne "Eligibilité Taille"
- afficher les données des colonnes "mix" max" "Effectif compris entre x et x employés"
- ou si aucune condition, afficher "Toutes tailles"
- afficher les données de la colonne "Microentre" sous la forme "Éligible aux micro-entreprises" ou "Non éligible aux micro-entreprises"

- [x] **🗓  Nombre d’années d’activité**
- afficher les données de la colonne "Eligibilité Existence" 
- ou si aucune condition, afficher "Éligible à toutes les entreprises"

- [x]  **💡 Autres critères d’éligibilité**
- afficher les données des 3 colonnes "éligibilité spécifique 1", "éligibilité spécifique 2", "éligibilité spécifique 3"
- ou si aucune condition, ne pas afficher la rubrique "💡 Autres critères d’éligibilité"

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/acc8144a-c1a5-4110-8c97-b94cfea40027)

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/e1dc657c-cc15-4554-89ac-2b4fd794af36)

---
~ticket front lié [#266](https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/266)~
~vision cible dans le ticket #257~

**Comment by ColineLebaratoux** [comment]
@pierrecamilleri, on pourra en discuter demain ? 
ça te semble faisable ou trop compliqué ?

**Comment by pierrecamilleri** [comment]
Je n'ai pas tout regardé les détails, mais à première vue, l'option 1 me paraît plus pertinente. Les informations que l'utilisateur nous a fournies, il les connaît bien (vu qu'il vient de nous les fournir), alors que les conditions d'éligibilité exacte sont nouvelles pour lui, et lui permet d'exercer un jugement critique (pour les utilisateurs les plus avisés). 

Par exemple : 
- L'entreprise est un Établissement de Taille Intermédiaire > "Ah, mais je ne suis pas éligible, malgrè le fait que j'ai plus de 250 salariés, j'en avais moins l'année dernière et donc je suis encore considéré comme une PME. Dommage !" 

L'inconvénient, c'est qu'on lui présente potentiellement des choses plus précises et techniques, mais j'ai du mal à m'imaginer présenter à ce stade des informations approximatives.

**Comment by JulienParis** [comment]
Note : @pierrecamilleri dispo pour seconder quand il y en aura besoin (pour intégrer côté front)
