### ISSUE TITLE
Ajouter la description longue dans un accordéon

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#184]
voir la maquette figma "en savoir plus" : https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=4167%3A87176&mode=design&t=zSBhGofst3V2NiTW-1

**Comment by pierrecamilleri** [comment]
Pour information, la description longue fait déjà partie des fiches dispositifs au format YAML. La prochaine étape est donc l'intégration de cette donnée dans le front-end.

**Comment by JulienParis** [comment]
note: effectivement, je n'avais réagi car j'ai été trompé par le 1er dispositif `accelerateur-decarbonation` qui (exception à la règle) n'a pas encore ce champ.

suggestion: je propose de reprendre ce ticket (devenir "assignee") et de changer le label/tag à `dev-front`

**Comment by JulienParis** [comment]
Preview sur https://tee-frontend-preprod-pr436.osc-fr1.scalingo.io/

Résultat => 

---

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/fdfebfa0-5637-4790-ab5d-d0ccf00b2f8f)

---

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/88677be2-1132-4a4b-8325-80e417a9bae0)

**Comment by ColineLebaratoux** [comment]
Merci @JulienParis 
Est-ce qu'il serait possible d'ajouter des règles pour gérer les interlignages pour améliorer la lecture de ce "pavé" de description longue ? 

- réduire l'interlignage au minimum entre les listes à puces 
- doubler l'interlignage entre 2 paragraphes (saut à la ligne)

cf maquette : 


![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/8233b583-20a1-4238-a2e2-e9600ab06ad0)

**Comment by ColineLebaratoux** [comment]
Pour cet exemple d'ailleurs, j'avais ajouter un saut de ligne dans le fichier excel : 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/ae0d8e3c-266a-473b-a8bc-d73df02fa86b)

**Comment by ColineLebaratoux** [comment]
cf autre ticket relatif aux interlignages sur la fiche dispositif : https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/447

**Comment by pierrecamilleri** [comment]
Après vérification les données yaml ont bien le double saut à la ligne.

```
 \ de domaines skiables.\n\nSont éligibles :\n•  Les engins \"non routiers\",c'est-à-dire\
                        _____
```

**Comment by JulienParis** [comment]
Quelques corrections apportées => https://tee-frontend-preprod-pr436.osc-fr1.scalingo.io/

Note : Je suis pour le moment resté sur l'accordéon tel qu'il est exactement proposé par le DSFR, sans les modifs d'UI que tu proposes de ton côté dans Figma

**Comment by ColineLebaratoux** [comment]
demande d'évolution concernant le comportement de l'accordéon : 
- [ ] déployé par défaut sur écran large 
- [ ] replié par défaut à partir d'une largeur d'écran type mobile

**Comment by ColineLebaratoux** [comment]
ticket lié #456 pour les conditions d'éligibilité

**Comment by JulienParis** [comment]
Comportement du tiroir ajouté, breakpoint choisi : tiroir ouvert par défaut à partir de la taille de fenêtre MD (768 px) et + grand (cf [breakpoints DSFR](https://www.systeme-de-design.gouv.fr/elements-d-interface/fondamentaux-techniques/grille-et-points-de-rupture))

@ColineLebaratoux pour validation 

Preview sur https://tee-frontend-preprod-pr436.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
Merci @JulienParis !

> Je suis pour le moment resté sur l'accordéon tel qu'il est exactement proposé et décrit par le DSFR (notre Bible à tous, amen), sans les modifs d'UI que tu proposes de ton côté dans Figma

Peux-tu intégrer l'évolution UI dans ce ticket ?
