### ISSUE TITLE
Filtrer sur les réponses à l'auto-diag

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#185]
# Contexte

Aujourd'hui, les réponses spécifiques au parcours "je ne sais pas par où commencer"  (c'est à dire celles qui ne sont pas communes avec le parcours "J'ai un objectif précis en tête" n'ont pas d'impact sur les réponses affichées. 

# Objectif 

Il s'agit donc de faire un lien entre les réponses du questionnaire et les dispositifs affichés.

# Détails

Dans la mesure du possible, on essaie de mutualiser les réponses dans les deux parcours. Ainsi : 
- La question sur les véhicules motorisés active la thématique "mobilité durable"
- La gestion des déchets, des matières premières, de l'eau, de l'énergie active la thématique associée (écoconception pour matières premières).
- La question des audits envrionnementaux sont rattaché à "l'impact environnemental"

Certaines questions appellent par contre un filtrage parfaitement nouveau, et dans ce cas, on utilise les données du [tableau xlsx de dispositifs](https://ademecloud.sharepoint.com/:x:/s/P-P-StartupDGE/ERKQ_wqzfFlHi85f0Fg1RRYBO3EwDP1_FwyvxQpOIsCIzg?rtime=pJNQpDTh20g) : 

- Propriétaire, ou pas, ou les deux
- Le mode de transport spécifique (domicile travail) & le carburant utilisé feront l'objet d'un autre ticket

**Comment by ColineLebaratoux** [comment]
@pierrecamilleri, on ferme les yeux sur tout ça. Je met ces points dans un ticket #355 https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/355

**Comment by pierrecamilleri** [comment]
Merci pour ces retours. 

> Par exemple si les déchets ne sont pas un enjeux pour lui, nous ne lui proposons pas un audit déchet (même s'il n'en a jamais fait). est-ce le cas / est-ce possible ?

Oui c'est possible (pour les deux suggestions) mais par contre il y a des prérequis un peu longs pour ne pas casser le refiltrage de la page des résultats au passage :  notamment le ticket #352 qui lui-même dépend de #164.

En effet, ces conditions de filtrage s'écrivent avec des combinaisons de OU et ET, et l'implémentation du refiltrage fait puor l'instant l'hypothèse d'une unique liste OU à plat. 

Par exemple dans le second cas, la condition s'écrirait si je comprends bien (en pseudo-publicodes) : 
```
une de ces conditions :
    - toutes ces conditions :
        - objectif = "bâtiment"
        - objectif = "énergie"
  - ... # éventuellements d'autres conditions
```
