### ISSUE TITLE
🖥 Corrections affichage des montants d'aide sur les cartes

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#187]
Corrections suite à la PR 186 

Le contenu est maintenant dense sur les cartes dispositifs ! Pour améliorer l'UI est-ce possible de : 

- [x] Augmenter la largeur des cartes dispositifs

![Image](https://user-images.githubusercontent.com/47628484/277662251-447868da-1f95-4ab0-8da5-dbd0451cb55a.png)

- [x] Mettre le détail du coût ou du montant de l'aide en plus petit 
![Image](https://user-images.githubusercontent.com/47628484/277662905-c18cb593-14fb-400e-9064-ffdebcd85de2.png)

- [x] Est-ce possible d'éviter les "€" orphelins ?

![Image](https://user-images.githubusercontent.com/47628484/277663546-e538898c-840e-4706-a029-ba2f1401e184.png)

![Image](https://user-images.githubusercontent.com/47628484/277663689-69ce88b6-17db-4b0d-b2ad-ff6d1ecaadcd.png)

**Comment by JulienParis** [comment]
Ces corrections seront prises en compte avec la PR #189

**Comment by JulienParis** [comment]
@ColineLebaratoux comme la PR #189 a été mergée (et passée récemment en prod), je pense que le pb d'interlignage doit être reporté dans un autre ticket de correctifs UI/UX (genre le #200) 

Si ça te va je peux clore ce ticket

**Comment by JulienParis** [comment]
@ColineLebaratoux pour tester notre nouveau process, je t'invite à passer ce ticket au label "Validé" alors avant que je le passe en done :)
