### ISSUE TITLE
⚠️ Au clic sur un dispositif sur la page de résultat, la position du scroll de la page de résultats est maintenue sur la page dispositif

### ISSUE THREAD

**Issue by JulienParis** [betagouv/transition-ecologique-entreprises-widget#190]

**Comment by jbledevehat** [comment]
@JulienParis Je ne vois pas la PR en Prod mais je la vois en Pré-prod

**Comment by ColineLebaratoux** [comment]
@JulienParis serait-ce possible de supprimer l'effet de mouvement "scroll to top" pour créer une transition france entre les 2 pages ? à dispo pour en discuter si ce n'est pas clair ;)

**Comment by ColineLebaratoux** [comment]
je mets cette correction dans le ticket #200 et je valide ce ticket #190
