### ISSUE TITLE
Fix: Manque une virgule dans les cgu ?

### ISSUE THREAD

**Issue by yvalentin** [betagouv/transition-ecologique-entreprises-widget#196]
https://github.com/betagouv/transition-ecologique-entreprises-widget/blob/c8932a122d993cb6e4d13827bc4e1aedc317a40e/packages/web/src/questionnaire/trackResults.ts#L177

Est-ce qu'il manque une virgule après `Pour toute question` ?

**Comment by jbledevehat** [comment]
@yvalentin si tu veux l'ajouter, go
