### ISSUE TITLE
Faire les corrections des 39 premières lignes (dataprod)

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#198]
JB : "Les cellules oranges dans le tableau "DataProd" peuvent être modifiées. Cela fait suite à une discussion avec Pierre qui pourra prendre ces modifications en réintégrant l'ensemble du tableau. Cela évitera de faire 25 PR par modification de cellules."

**Comment by jbledevehat** [comment]
@jbledevehat voir les cellules oranges
