### ISSUE TITLE
🖥 Correction étape Siret : lien vers annuaire entreprise

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#199]
⚠️ Correction importante pour les tests utilisateurs

**Correction de l'étape SIRET** : 

- [x] Supprimer la mention "Renseignez le SIRET de votre entreprise (14 chiffres)"
- [x] Supprimer l'exemple dans le champ de recherche de SIRET, à remplacer par "Votre numéro SIRET (14 chiffres)"
- [x] Ajouter la mention en bleu : besoin d'aide pour retrouver votre SIRET ? Cliquez ici (vers : https://annuaire-entreprises.data.gouv.fr)=> ce lien reste affiché en permanence, et est proposé également en cas d'erreur
- [x] Passer le lien "ou je complète les informations manuellement" en noir

---
❌ Version actuelle :
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/38d16fd9-1acb-4c86-9d90-d786474b101f)
---
🎯 **Version cible** :
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/5bf0cd26-a679-4837-a32c-793cc676c730)

---

**Comment by JulienParis** [comment]
Note: résolution dans PR #203
