### ISSUE TITLE
Ajout de filtres sur page de résultats

### ISSUE THREAD

**Issue by JulienParis** [betagouv/transition-ecologique-entreprises-widget#206]
Page de résultats

**Parcours je ne sais pas par ou commencer** 
de gauche à droite :
- 1) Filtre sur la thématique de l'aide (bâtiment, mobilité, eau...)
- 2) Filtre sur le type de dispositifs (financement, accompagnement, prêt...)
https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=3919%3A105442&mode=design&t=0ZjKiFiCnMjDn0uZ-1

~~**Parcours j'ai un objectif en tête**~~
~~(Ne pas voir le filtre sur la thématique de l'aide (bâtiment, mobilité, eau...)~~
- ~~Filtre sur le type de dispositifs (financement, accompagnement, prêt...)~~
https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=2613%3A117754&mode=design&t=0ZjKiFiCnMjDn0uZ-1

**Catalogue des aides** 
- 1) Filtre sur la thématique de l'aide (bâtiment, mobilité, eau...)
- 2) Filtre sur le type de dispositifs (financement, accompagnement, prêt...)
- ~~3) Filtre sur l'opérateur~~

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/6750c9b7-423b-4f80-998c-3e0107377338)

**Comment by jbledevehat** [comment]
Il manque le filtre "Avantage fiscal" à la liste

**Comment by JulienParis** [comment]
> Attention, il manque le filtre "Avantage fiscal" à la liste

Okay, valeur de filtre ajoutée sur la PR et la branche correspondante https://github.com/betagouv/transition-ecologique-entreprises-widget/pull/201/commits/4c2a3a3f6c3a1043da99439360ee120f7485f51a

**Comment by JulienParis** [comment]
Note: résolution dans PR #201

**Comment by ColineLebaratoux** [comment]
J'ai ajouté des corrections sur le ticket #242 (reformulations)

**Comment by jbledevehat** [comment]
Les contenus barrés ont des cartes dédiées à prioriser
