### ISSUE TITLE
🖥 Faire la page annuaire

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#207]
lien vers le figma : https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=3798%3A87935&mode=design&t=2Sldbxb8IIvDGeuF-1

- [ ] bandeau de titre et présentation de la page annuaire

- [ ]  3 filtres : thématiques, type d'aide, opérateur

- [ ] menu déroulant avec autocomplétion sur le titre (priorité 2)

Correspondant aux userstories : 
"En tant qu'utilisateur, je recherche un dispositif en particulier" (ex : tremplin)
"En tant qu'opérateur, j'utilise l'annuaire pour trouver les aides que nous proposons"
"En tant qu'opérateur, j'utilise l'annuaire pour voir l'exhaustivité des accompagnements ou financements proposés sur une thématique"

**Comment by JulienParis** [comment]
Note: Résolution avec PR #204, MAIS avec 2 filtres "type d'aide" et "thématique" uniquement pour le moment (au 09/11/2023)

**Comment by ColineLebaratoux** [comment]
je place ces évolutions dans un nouveau ticket #273
- [ ] bandeau de titre et présentation de la page annuaire
- [ ]  Ajout du filtre opérateur
- [ ] menu déroulant avec autocomplétion sur le titre (priorité 2)
