### ISSUE TITLE
Filtrer les dispositifs selon les code NAF éligibles

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#214]
# Contexte

Les dispositifs sont aujourd'hui filtrés selon des codes NAF niveau 1 seulement, et selon des secteurs pertinents. 

Les conditions d'éligibilité peuvent porter sur des codes NAF de n'importe quel niveau, notamment niveau 5

# Conditions d'acceptation

En tant qu'utilisateur, je veux que les dispositifs avec des conditions d'éligibilité sectorielle basé sur des code NAF (colonne AV, "Eligibilité sectorielle") me soient présentés uniquement si le secteur de mon entreprise est éligible. 

# Sous-tâches

  - [X] ~~Mise en qualité des données~~ > Faite à la main à même les yaml 
  - [X] Données de dispositifs au format yaml mises à jour avec les codes NAF à privilégier
  - [X] Faire le lien entre le questionnaire et le filtre publicodes pour que le filtre soit fonctionnel

**Comment by ColineLebaratoux** [comment]
-  Test avec le siret d'une entreprise du secteur de la fabrication de mobilier, parcours j'ai un objectif en tête + déchets 
(siret : 88420610300027,"Fabrication d'autres meubles et industries connexes de l'ameublement" / code APE 3109B)
> Le résultat "imprim'vert" ne devrait pas s'afficher (ne correspond pas au code naf)

**Comment by pierrecamilleri** [comment]
Je ne reproduis pas en [preprod](https://preprod.mission-transition-ecologique.incubateur.net/).

Voici le cas de test que j'ai testé : 
- Parcours objectif précis
- J'entre le siret "88420610300027"
- 20 et 49 employés (éligibilité imprim'vert < 250)
- Mieux gérer mes déchets (fait partie des objectifs imprim'vert)

Je n'obtiens pas imprim'vert dans la liste de résultats.

Idem dans le parcours "je ne sais pas par où commencer" en répondant "oui" à tout.

**Comment by ColineLebaratoux** [comment]
je ne le vois plus non plus ! 🤔
