### ISSUE TITLE
Changer wording CTA avant formulaire

### ISSUE THREAD

**Issue by JulienParis** [betagouv/transition-ecologique-entreprises-widget#23]
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/f18e3213-5b85-424f-91b8-137437055f98)

**Comment by jbledevehat** [comment]
Renommer par : 
"Vous avez envie de candidaté ?" 
"N'hésitez pas à nous laisser vos coordonnées, nous nous ferons un plaisir de vous aider." 

à la place de 
" Vous avez une question ?
N'hésitez pas à nous laisser un message, nous nous ferons un plaisir de répondre à vos questions. "

Car notre volonté est bien de déposer leur demande à leur place.

**Comment by jbledevehat** [comment]
J'ai fais la modif @JulienParis

**Comment by JulienParis** [comment]
bien noté @jbledevehat , par contre par souci d'hygiène c'est préférable de faire les modifs dans le code source sur une branche séparée et de faire un PR (pull request) avant de merger sur la branche principale `main`
