### ISSUE TITLE
Evolutions des questions mobilité sur le parcours "Je ne sais pas par où commencer"

### ISSUE THREAD

**Issue by pierrecamilleri** [betagouv/transition-ecologique-entreprises-widget#231]
Sur le parcours "Je ne sais pas par où commencer", supprimer les 3 questions 🚲mobilité car les réponses à ces questions ne filtrent pas efficacement (tu confirmes @pierrecamilleri ?)
A savoir :
"Quel est le mode de transport principal des salariés pour le trajet domicile-travail ?"
"Possédez-vous un ou plusieurs véhicules motorisés dans votre entreprise ?"
"Quelle est la source principale d'énergie de vos véhicules ?"

A la place, dans la partie 🚲mobilité ajouter cette question :
"Souhaitez-vous favoriser des déplacements plus écologiques pour vous et vos employés ?"

1.  👏 Oui, ça m'intéresse !
2.   🚲 Non, on fait déjà le maximum sur le sujet
3. ❌ Non, ce n'est pas un enjeu pour moi
4.  Aucune idée

Traitement de la réponse (pour décider s'il faut ou non afficher des dispositifs en lien avec la mobilité des employés)

1. OUi => 1
2. Non => 0
3. Non => 0
4. Ne sais pas => 1

**Comment by ColineLebaratoux** [comment]
Tu as raison, cette question pose systématiquement problème lors des tests !
_"mobilité :  On peut cliquer sur plusieurs choix ? moi je voudrais mettre voiture mais aussi trottinette. (il y en a une)"
_"mobilité_ : la moitié en voiture et la moitié en train ou métro. (j’aurais aimé cliqué sur 2 choix)"_

Le problème c'est que si on donne la possibilité de cliquer sur plusieurs choix : 
- On ne sait pas comment traiter la donnée derrière. Comment on l'interprète ?
- Ce type de question donne l"impression que nous fournissons en fin de parcours un diagnostic précis de la maturité écologique de l'entreprise. Ce qui n'est pas le cas. 

Proposition de reformulation 

Avez-vous mis en place un Plan de Mobilité Employeur pour favoriser les modes de déplacements alternatifs à la voiture de vos employés ?
1/ Oui, nous avons déjà mené cette démarche
2/ Pas encore, ça m'intéresse ! 
3/ Non, nous n'en avons pas besoin 

Traitement de la réponse (pour décider s'il faut ou non afficher des dispositifs en lien avec la mobilité des employés) 
1/ OUi => 0
2/ Pas encore => 1
3/ Non => 0

**Comment by ColineLebaratoux** [comment]
souhaitez-vous favoriser les déplacements plus écologiques pour vos employés ?

**Comment by ColineLebaratoux** [comment]
souhaitez-vous favoriser les déplacements plus écologiques pour vos employés ?

ajouter la notion de (domicile travail / entreprise)

**Comment by jbledevehat** [comment]
@ColineLebaratoux 
On peut garder la phrase "Souhaitez-vous favoriser des déplacements plus écologiques pour vous et vos employés ?" Car ce n'est pas uniquement mettre en place un plan mobilité...

**Comment by ColineLebaratoux** [comment]
Oui c'est bien ça @jbledevehat, ce que tu lis dans les commentaires c'est l'historique des réflexions. le texte de description du ticket est à jour avec la bonne proposition "Souhaitez-vous favoriser des déplacements plus écologiques pour vous et vos employés ?"

**Comment by JulienParis** [comment]
@ColineLebaratoux La piste de question supplémentaire pourrait ressembler à ça donc => 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/9a451221-6bc4-4c69-8598-36ff8cb4d63c)

@pierrecamilleri pour le filtrage côté Publicode j'ai une question : de quelle clé tu as besoin devant la valeur "0" ou "1" ?

**Comment by pierrecamilleri** [comment]
Ok pour conserver `questionnaire . objectif prioritaire . est la mobilité durable`

Note pour moi-même avant clôture du ticket : 

- [ ] Enlever les colonnes obsolètes sur le DGE
- [ ] Enlever les objectifs obsolètes sur les yaml

**Comment by JulienParis** [comment]
@ColineLebaratoux pour validation UX : il n'y a plus qu'une question pour la thématique mobilité (intégrant tes remarques précédentes), qui mène ensuite à la piste de questions des déchets =>

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/722a52ff-d9ee-489c-b297-4388693756b2)

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/0b9bdd89-c178-46e4-b1ff-dee8b53ea966)

Preview : https://tee-frontend-preprod-pr543.osc-fr1.scalingo.io
