### ISSUE TITLE
S'accorder sur le comportement de "re-filtrage" dans la page résultat : ET/ET ou OU/OU ?

### ISSUE THREAD

**Issue by JulienParis** [betagouv/transition-ecologique-entreprises-widget#236]
Issue dédiée pour parler du comportement des filtres souhaité dans la page résultats : 

Est-ce qu'on souhaite faire apparaître un dispositif dans les résultats "re-filtrés" si le champ lui-même n'existe pas ou non ?

Refs : 

- Voir discussion https://github.com/betagouv/transition-ecologique-entreprises-widget/pull/201#issuecomment-1804286057

**Comment by JulienParis** [comment]
Il y a certainement un problème dont j'ai exprimé le problème :) Personnellement je vois un flou dans la manière dont on parle justement du "résultat escompté" : il est possible qu'on soit tous d'accord, mais il est possible que non.... Cette issue vise essentiellement à lever cette ambiguïté.

Le filtrage des yaml eux-mêmes (leur éligibilité) est bien géré par la fonction de filtrage utilisant publicodes. Mon problème est lorsqu'il s'agit de "re-filter" avec les filtres/menus-déroulants en haut de la page de résultats. Pour des raisons de concision et de simplicité les composants vue de "re-filtrage" utilisent des fonctions de contrôle des conditions locales, et non publicodes. 

Lorsqu'il y a plusieurs filtres/menu-déroulants actifs on peut - d'un point de vue éditorial - se demander plusieurs choses :  

- faut-il afficher ou non un dispositif si une condition est sélectionnée dans le menu déroulant, mais que le champ lui-même n'existe pas dans le dispositif ? 
- faut-il afficher les dispositifs qui répondent à l'un ou l'autre des conditions choisies dans les menus déroulants, ou aux deux à la fois ? 

C'est sans doute pas la question philosophique du siècle, mais personnellement j'ai besoin de lever ce que je perçois comme une ambiguïté.

**Comment by ColineLebaratoux** [comment]
faut-il afficher ou non un dispositif si une condition est sélectionnée dans le menu déroulant, mais que le champ lui-même n'existe pas dans le dispositif ?

> - Est-ce que tu peux donner un exemple ? J'ai l'impression que tous les dispositifs ont les champs : le type d'aide et thématique renseignés. 

faut-il afficher les dispositifs qui répondent à l'un ou l'autre des conditions choisies dans les menus déroulants, ou aux deux à la fois ?

> Il faut afficher les dispositifs qui répondent aux deux conditions choisies : ET/ET (thématique + type d'aide)

**Comment by jbledevehat** [comment]
Cette carte doit être dans la colonne Purgatoire. Les filtres sont toujours avec un comportement "ET".
