### ISSUE TITLE
 Replace `ConditionOperators.inexist` by `ConditionOperators.missing`

### ISSUE THREAD

**Issue by yvalentin** [betagouv/transition-ecologique-entreprises-widget#238]
Was previously the case, but `inexist` does not seem to be a commonly used verb (see [dictionary entry](https://www.merriam-webster.com/dictionary/inexist) : "archaic"), and with a different meaning than intended. 

Proposed new name `isMissing` or `missing`

_Originally posted by @pierrecamilleri in https://github.com/betagouv/transition-ecologique-entreprises-widget/pull/210#discussion_r1383988269_

**Comment by pierrecamilleri** [comment]
Résolu dans #388
