### ISSUE TITLE
Unhandled case when entreprise . effectif = 20

### ISSUE THREAD

**Issue by yvalentin** [betagouv/transition-ecologique-entreprises-widget#239]
Again, not linked to this PR, but there is an obvious unhandled case when `entreprise . effectif = 20`. 

Not sure we should keep this `inputCleaning` property as `structure_sizes` is used nowhere I am aware of.

_Originally posted by @pierrecamilleri in https://github.com/betagouv/transition-ecologique-entreprises-widget/pull/210#discussion_r1383993130_
            
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/240
- [ ] https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/238
```

**Comment by pierrecamilleri** [comment]
Le code en question n'était pas exécuté (`disabled: true`), donc je l'ai supprimé, rendant caduque cette issue.
