### ISSUE TITLE
Reformulation du filtre objectif sur la page de résultats + annuaire

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#242]
Renommer les filtres liées aux objectifs (ticket lié #206)

- [x] Renommer le nom du filtre "filtrer par objectif prioritaire" par "Filtrer par objectif"

- [x] Renommer les dénominations des objectifs par : (pour gagner en simplicité et harmoniser la manière de nommer)
🏢 Bâtiment
🚲 Mobilité
🗑 Déchets
💧 Eau
⚡️ Energie
🧑‍🎓 RH
🌱 Stratégie environnementale 
🏭 Production

Possible d'intégrer les émojis ?

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/41645aeb-6378-45f6-86c1-d5b9800437b5)

**Comment by JulienParis** [comment]
@ColineLebaratoux cf #275 pour validation des renommages
