### ISSUE TITLE
migrer les domaines de staging et preprod vers des sous-domaines de `mission-transition-ecologique.beta.gouv.fr`

### ISSUE THREAD

**Issue by JulienParis** [betagouv/transition-ecologique-entreprises-widget#244]
Les espaces de staging et de preprod sont déployés dans un domaine en `incubateur.net`. Pour des soucis de clarté envers l'incubateur et beta, il est nécessaire d'homogénéiser les noms de nos espaces de preprod/staging avec notre nom de domaine principal "mission-transition-ecologique.beta.gouv.fr"

- https://preprod.transition-ecologique-des-entreprises.incubateur.net/
  - idéalement, changer et avoir les redirections vers : `https://preprod.mission-transition-ecologique.incubateur.net`
- https://staging.transition-ecologique-des-entreprises.incubateur.net/
  - idéalement, changer et avoir les redirections vers : `https://staging.mission-transition-ecologique.incubateur.net`
  
## Notes

- [Pad de notes avec Julien Dauphant](https://pad.numerique.gouv.fr/E6LLDFgWRci7PoloVo4weg?both#)
- L'ensemble de la gestion du nom de domaine "mission-transition-ecologique.beta.gouv.net" est géré via OVH
- Les redirections sont gérées par Julien Dauphant via une app dédiée Scalingo sur laquelle il a la main

**Comment by yvalentin** [comment]
@JulienParis 
> - Supprimer les entrées Always Data (inutiles)  

Il me semble que c'est fait ?

**Comment by JulienParis** [comment]
> @JulienParis
> 
> > * Supprimer les entrées Always Data (inutiles)
> 
> Il me semble que c'est fait ?

De facto toute la logique liée aux domaines (DNS, redirections...) passe par OVH désormais, mais j'ai toujours ces noms de domaine dans Always Data, qui ne servent à rien en fin de compte =>

![Capture d’écran 2023-11-22 à 12 13 00](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/7dc0a208-d82a-47de-9eab-d6585ec6a2c7)

Je voulais être certain de pouvoir cliquer sur la petite poubelle en face de chacun de ces domaines dans Always Data.

**Comment by jbledevehat** [comment]
@JulienParis Est-ce que ce ticket est fait ?

**Comment by JulienParis** [comment]
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/e63cb391-867d-45fe-a11d-192131f8d5e1)
