### ISSUE TITLE
modifier le logo mission transition dans le header et le footer

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#263]
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/1a0390e7-df71-440f-815c-80dfc512d4fa)
Le logo actuel est très pixellisé. 
lien vers le logo : 
https://drive.google.com/file/d/1_ydcec6w8Il8smji8j4Xvt1_8x13Bfi-/view?usp=drive_link

**Comment by JulienParis** [comment]
> @JulienParis le logo est coupé sur la partie droite
> 
> ![Image](https://user-images.githubusercontent.com/47628484/283478680-9ff04cf2-7dc8-44d1-938a-608089029c4c.png)

Je pense que c'est le logo png que tu m'as donné qui est un peu coupé sur la partie droite => https://drive.google.com/file/d/1_ydcec6w8Il8smji8j4Xvt1_8x13Bfi-/view

**Comment by ColineLebaratoux** [comment]
Au temps pour moi 😬
Je te redonne un nouveau lien : https://drive.google.com/file/d/1S5gSPgIefVKMxXGtFN97YPPKYf_RMYwk/view?usp=drive_link

**Comment by ColineLebaratoux** [comment]
Merci !
