### ISSUE TITLE
Ajouter les données d'éligibilité sur la fiche dispositif

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#266]
https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=4167%3A87176&mode=design&t=yGmpUNUPsuXiV6mB-1

- ticket data lié #183 
- PR implem en front #441

**Comment by JulienParis** [comment]
Je viens de sortir ce ticket des archives car pour qu'il soit résolu il faut compléter 2 étapes : 1) intégrer les données d'éligibilité dans les yaml (fait avec #426) ; 2) visualiser les données dans le frontend (pas encore fait à ce jour)

**Comment by JulienParis** [comment]
Preview sur : https://tee-frontend-preprod-pr441.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
Merci @JulienParis ! 
Petits ajustements : 

- [ ] Est-ce que tu peux passer les titres des rubrique a la même taille que le texte ? (et appliquer le même interlignage entre le titre et les textes 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/5116799a-65c7-4f93-9e8b-a3795a44977b)

- [ ] Remplacer les pictos ✓ par des bulletpoints (désolé, cette version avec les ✓ était dans le cas où on verifiait les données d'éligibilité, hors ici elles sont en texte brut)
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/9c128999-4884-49c0-9f6a-e4e53b1b0fd6)

- [ ] Changer l'ordre d'affichage des catégories : taille, secteur géographique, nb d'années d'activités, secteur d'activité, autres critères

- [ ] Passer les textes en 2 colonnes pour la version desktop (cf proposition de @yvalentin  https://github.com/betagouv/transition-ecologique-entreprises-widget/pull/441#discussion_r1429738930)

**Comment by ColineLebaratoux** [comment]
- [ ] L'affichage des secteurs géographiques serait plus lisible séparé avec des virgules : "Martinique, Guyane, La Réunion..." Cette évolution est à faire de mon côté dans le tableau de données ?

**Comment by JulienParis** [comment]
C'était un peu plus relou qu'attendu à cause des typages mais ça donne ça sur la #441 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/cc3f6adf-b751-4094-b651-d26d76c87b36)

**Comment by ColineLebaratoux** [comment]
Bravo ! c'est parfait
J'attends l'évolution d'affichage des secteurs géographiques pour valider le ticket @pierrecamilleri

**Comment by pierrecamilleri** [comment]
Données corrigées mergée en preprod à l'instant, donc ce sera testable quand la PR #441 sera en preprod également (ça ne saurait tarder, elle a été relue et validée)

**Comment by ColineLebaratoux** [comment]
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/ba56c09d-2998-4b1a-ad8d-f7132bd398f6)

**Comment by JulienParis** [comment]
Problème résolu : en réadaptant cette partie du code j'avais oublié que certaines fiches n'ont pas tous les "blocs" dans la partie Eligibilité. La chose est normalement corrigée maintenant => 

![Capture d’écran 2023-12-20 à 13 28 40](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/9b19c5a7-c551-46f0-8f07-7d6cd3eb937d)

**Comment by ColineLebaratoux** [comment]
- [ ] Est-ce possible de répartir équitablement les blocs sur les 2 colonnes quand il y en a 4 ? 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/196c9c0d-329a-4aa6-9783-884109bc4e9f)

**Comment by pierrecamilleri** [comment]
Normalement j'ai rééquilibré :

https://tee-frontend-preprod-pr441.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
Tu gères !
