### ISSUE TITLE
Diminuer les marges autour du CTA "je me lance" pour le placer au dessus de la zone de flotaison

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#269]
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/7794f7d8-fdac-496d-9e92-86715b91d93b)

cf maquette : https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=3028%3A95808&mode=design&t=yGmpUNUPsuXiV6mB-1

**Comment by JulienParis** [comment]
question: @ColineLebaratoux juste pour ma culture générale, c'est quoi la "ligne de flottaison" ? C'est la ligne horizontale qui coupe l'écran en 2 si on la trace au milieu de l'écran ?

**Comment by ColineLebaratoux** [comment]
C'est parfait comme ça Juju, j'ai répondu sur la 272 ! 

nb :  la ligne de flottaison c'est une ligne imaginaire qui sépare la partie visible de la page de la partie invisible (il est ensuite nécessaire de scroller). Elle détermine où placer les éléments les plus importants, et notamment le CTA principal.
