### ISSUE TITLE
Reformulation et correction UI sur la page d'accueil

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#271]
- [x] Ajouter les logos des partenaires sur la page d'accueil (pour mettre en avant la promesse cross-opérateur peu comprise par les utilisateurs) Attention avec le bon logo CCI
_”c’est dommage, si vous ne me l’aviez pas dit, je serais passé à côté du fait que c’était toutes les offres des différents partenaires publics. C’est un vrai atout !”_
 [(cf maquette)](https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=4292%3A79319&mode=design&t=peUdBITJee8JpWMA-1)

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/19b47ccb-e71f-4cd7-a694-fa6c4f6fe809)

---

 - [x] modifier "votre" par "mon"

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/8c4e3281-0755-42b5-9e0c-98a8478adac6)

---
- [x] diminuer la taille des 3 titres : 1. Je renseigne mon profil..." 2. Je réponds à ..." 3. J’accède aux aides... ce qui permet de passer les texte sur 2 lignes. 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/d09dd1cc-4f80-40c1-b8da-e2cebc42e5be)

cible : 
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/b83770c5-a636-4f4f-b6f8-d2b3178927cf)

---
- [x] Ajouter "On vous aide à atteindre vos objectifs" au dessus des blocs thématiques de la page d'accueil
Test utilisateur : (Scrolle sur la page d’accueil) _"là on rentre dans une autre partie. il manque comme une section pour m’expliquer à quoi correspond cette deuxième partie."_

 cf [maquette desktop](https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=3028%3A95808&mode=design&t=HF8fi4CE5XzUuuGN-1) et [maquette mobile](https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=4171%3A28294&mode=design&t=HF8fi4CE5XzUuuGN-1)
---

**Comment by JulienParis** [comment]
@ColineLebaratoux preview sur https://tee-frontend-preprod-pr546.osc-fr1.scalingo.io

**Comment by ColineLebaratoux** [comment]
- [ ] Pourrais-tu diminuer la taille du logo CCIfrance ? + ajouter "..."

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/69430cdd-3334-4863-959a-7b05891028eb)

cible : 
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/c9412c2d-d7a3-4a48-b75a-b659cda42f96)

**Comment by JulienParis** [comment]
changement apporté en partant sur l'image unique contenant tous les logos => https://tee-frontend-preprod-pr546.osc-fr1.scalingo.io/
