### ISSUE TITLE
📱 Corrections UI responsive

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#274]
---
- [x] diminuer les marges gauches [comme sur la maquette ](https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=2694%3A96459&mode=design&t=Ih3VNPKwcMzOIzrH-1)

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/a3bd6c9d-66f4-418e-a1f5-ec6200944279)

---
- [x] sur la fiche dispositif, modifier l'affichage des données cout, type, prestation, porteur de l'aide
cible : 
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/b3a753c8-ff15-4383-90e4-bb876e84964b)

---

- [x] coller le bandeau thématique en haut de la page pour avoir un max de contenu au dessus de la ligne de flottaison. (desktop et mobile)
- [x] En version mobile, faire évoluer l'UI du bandeau thématique : enlever le nom "thématique" du bandeau et diminuer la taille du text. voir maquettes [ici ](https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=2694%3A47016&mode=design&t=9ShGRj0y8x6484nm-1)et[ là](https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=2694%3A47075&mode=design&t=9ShGRj0y8x6484nm-1)

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/99752743-4ade-42a0-bf66-b2f9080709a8)

version cible : 
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/864e254c-ae4b-41c1-bbe8-965f266bb72e)

https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=2694%3A47016&mode=design&t=k7ehRLgsg6sijzXV-1

---

- [x] Sur la HP, supprimer l'image en haut, diminuer la taille des typos sur la HP, les espacements pour rapprocher le "je me lance" de la ligne de flottaison (cf maquette)
[ image ](https://drive.google.com/file/d/12IbSm0QGvC_TOMekP-Nz-sCfXQ6ZOr2w/view?usp=drive_link)

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/d033b09a-41e3-49c3-a436-868002fafd85)

- [x] diminuer la taille des textes des 3 étapes et ferrer à gauche

---
- [x] diminuer les marges en haut des titres des questions ou du titre "vos résultats" pour avoir un max de contenu au dessus de la ligne de flottaison. 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/889919d2-2150-438a-9d35-0140edd476bd)

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/bd8b07f0-10e3-420f-86fb-45434a81094a)

- [x] réduire les espacements entre les blocs thématiques sur [la HP cf maquette](https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=4171%3A28294&mode=design&t=8gzuLuADOLFGWniS-1)

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/ece92b67-266b-4b3f-aa7a-0d7aa5e45ca5)

**Comment by JulienParis** [comment]
Ct bien tricky...

Preview sur : https://transition-ecologique-entreprises-preprod-pr569.osc-fr1.scalingo.io

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/de10f409-d60d-4a01-b10e-6390f1b159b0)
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/d80d0cc5-3383-4ba3-93df-85f3e5c8b3cd)
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/6405112c-bf16-4619-a628-eba5ec589b17)
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/01829eab-3594-4ddc-b133-1b5ae99be155)
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/5926a582-5ac8-4379-9a4e-ccbcef9f999b)
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/1fc79e27-a0f5-429a-bba1-80a3986ec729)
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/3b34102e-5ab7-49d4-8698-2fdbf8a48def)
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/b4c376d4-c6df-48c8-8ec5-34a279d44a83)
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/038337d7-d7a3-4306-b4d4-a3ad823aad7c)

**Comment by ColineLebaratoux** [comment]
Merci @JulienParis ! Bravo, j'imagine la galère pour faire ces petites corrections UI 
Je fais un nouveau ticket pour y mettre mes retours => https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/585#issue-2135987561
