### ISSUE TITLE
Correction UX à l'étape SIRET

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#280]
Correction suite aux tests utilisateurs : 
A l'étape SIRET, l’utilisateur ne sait pas s’il doit cliquer pour seléctionner le résultat. 

retour UX qui revient 1 fois sur 3 : _c’est là ou je trouve que c’est dommage. Je suis restée bloqué. J’avais pas compris.  il faut cliquer sinon on peut pas cliquer sur suivant. C’est un tout ptit truc mais qui embête vraiment !_

- [x] sélectionner le résultat par défaut = le bouton valider est actif dès lors qu'il y a un résultat.
- [x] Ne plus rendre cliquable le résultat (on ne peut pas le déséléctionner. Si l'utilisateur change d'avis, il peut supprimer sa recherche grace à la croix.

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/a6c78bbc-dc35-41f4-b65d-13a0d8602ae2)

- [x] permettre d'afficher tout le texte dans le champs "votre numéro SIRET (14 chiffres)" :
- mettre en plus petit "votre numéro SIRET (14 chiffres)" pour que le texte entier s'affiche sur mobile 
- ou remplacer le texte mobile par "votre n° SIRET (14 chiffres)" 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/5579fc42-7652-4209-a854-c3e68f7ae442)

**Comment by JulienParis** [comment]
pour validation => preview : https://tee-preprod-pr593.osc-fr1.scalingo.io/questionnaire

Note : La petite croix permettant de faire un reset de l'input a demandé un peu de jonglage => 

Captures d'écran

---

Sur mobile :

<img width="433" alt="Capture d’écran 2024-02-21 à 11 38 52" src="https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/9c5b740b-038f-43f9-9edf-7057e047fc45">

---

Desktop / pas d'input :

<img width="883" alt="Capture d’écran 2024-02-21 à 11 39 48" src="https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/11063eb5-5c17-4787-890e-56c84369bd1b">

---

Desktop / input => petite croix apparaît

<img width="893" alt="Capture d’écran 2024-02-21 à 11 39 18" src="https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/04b48638-62ff-4e11-a3fd-80d89a5ee292">

---

Desktop / input + loading  (searching)

<img width="863" alt="Capture d’écran 2024-02-21 à 11 40 15" src="https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/921be43d-fb10-4eca-b4b6-b1b044e92582">

---

Desktop / input + response => carte de réponse est préselectionnée et n'est plus cliquable / l'utilisateur peut cliquer sur la croix pour annuler son input

<img width="869" alt="Capture d’écran 2024-02-21 à 11 40 28" src="https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/2068acde-ba89-4066-97e1-d284e9b73b29">

**Comment by ColineLebaratoux** [comment]
Petit bug, il y a deux croix d'annulation qui s'affichent. 


![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/542c33c4-0a5f-4f3c-8305-bd26ef573633)
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/419c7de0-7cd8-46b2-83ee-c7bc3678e597)

**Comment by JulienParis** [comment]
chelou, sur Firefox j'ai pas la croix dans la partie bleue... 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/b42cab25-4333-4a03-961e-8f1d93e914b1)

**Comment by JulienParis** [comment]
Bon j'ai tenté de trouver une solution universelle pas trop compliquée =>

J'ai enlevé le comportement par défaut du DSFR [qui ne marche pas sur Firefox](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-search-cancel-button), et mis cette croix de reset entre l'input et la loupe. A priori ça marche sur Chrome / Safari / Firefox



![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/5e8bc7ee-7744-4334-8750-7bd3acebd1cc)



![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/2a03f898-762d-4782-ba55-b080719ddf1a)

**Comment by ColineLebaratoux** [comment]
@JulienParis 👍 Bien joué, il n'y a plus qu'une croix. 
En revanche, on voit bien que c'est 2 composants séparés : 
- est-ce que tu peux passer tout en bleu clair (la barre de recherche apparait en bleu clair et la croix est dans un carré gris sur chrome. cf capture d'ecran)
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/bd1513a8-6f53-4b18-ab17-e21ccac514d7)
- est-ce que la zone de sélection bleu peut englober la barre de recherche et la croix ?

**Comment by JulienParis** [comment]
@ColineLebaratoux c'est (encore une fois) chelou car de mon côté je n'ai pas ce fond bleu sur mes navigateurs quand je sélectionne le champ, de gauche à droite : Firefox, Safari, Chrome (sur MacOS) => 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/06ae2b0b-ad81-4d26-8554-691d6207a57e)

**Comment by ColineLebaratoux** [comment]
OK alors fermons les yeux la dessus ! 🙈

Et la zone de sélection bleu peut-elle englober la barre de recherche et la croix ?

**Comment by JulienParis** [comment]
@ColineLebaratoux cool

Du coup j'ai implémenté la zone de sélection (bordure bleue) sur l'ensemble de la zone d'input (input + croix + loupe). J'ai inclus la loupe dedans car ça me semblait à la fois + propre en terme d'UI, et j'avoue ct + simple aussi côté code =>

<img width="634" alt="Capture d’écran 2024-03-12 à 15 01 57" src="https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/03b27a29-9ed7-412f-afda-c4f6066b3639">

**Comment by ColineLebaratoux** [comment]
Top ! 🎉
