### ISSUE TITLE
Reformuler la question matière première dans le parcours "je ne sais pas par ou commencer"

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#283]
- [x] Reformuler la question ”Avez-vous pour objectif de réduire vos pertes de matières premières ou votre production de déchets ?”  pour **”Avez-vous pour objectif de réduire vos pertes de matières premières ?”** 

---
Retour suite aux tests utilisateurs 
_“la perte de matière première ou la production de déchets. la question est double j’ai l’impression. Je ne sais pas quoi répondre”_ 
[cf test utilisateur](https://www.notion.so/accelerateur-transition-ecologique-ademe/Test-esth-ticienne-ada4723c324a4dce8ae863c13502e40a?pvs=4)

**Comment by ColineLebaratoux** [comment]
tu en penses quoi @jbledevehat ?

**Comment by jbledevehat** [comment]
@ColineLebaratoux Oui très bien, ça sera plus clair effectivement

**Comment by JulienParis** [comment]
@ColineLebaratoux pour validation https://staging.mission-transition-ecologique.incubateur.net/questionnaire

J'ai regardé de mon côté ça m'a l'air ok =>

![Capture d’écran 2023-12-04 à 12 49 03](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/b737c0ae-f26a-4b65-a129-ec6891aed846)
