### ISSUE TITLE
Lien mailto dans les CGU sur "france-transition(at)beta.gouv.fr" ?

### ISSUE THREAD

**Issue by JulienParis** [betagouv/transition-ecologique-entreprises-widget#286]

**Comment by JulienParis** [comment]
Note: si je ne me trompe pas a priori ce point précis est réglé. Si c'est bien le cas on peut clore ce ticket et le mettre dans la colonne `done`

cf : https://mission-transition-ecologique.beta.gouv.fr/accessibilite

---

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/4eb0b3ce-3483-45e7-aae4-89b91fdcc988)

**Comment by jbledevehat** [comment]
Je laisse @ColineLebaratoux confirmer

**Comment by jbledevehat** [comment]
Voir #385

**Comment by ColineLebaratoux** [comment]
@jbledevehat @JulienParis je ne suis pas sûre de bien comprendre l'objet du ticket. 
- Dans les CGU, on pourrait ajouter un lien mailto dans le corps du texte pour éviter d'avoir à chercher le formulaire.

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/da85a0b8-3d16-4ca1-ad28-6c083a73196f)

- Concernant le bandeau de contact en bas de page, je me demande pourquoi il y a un traitement différent au niveau du CTA alors que c'est le même comportement derrière : ouverture d'un mail externe ? (l'icône du lien externe étant le plus approprié ici)
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/6a0152d6-5a68-4b3d-b424-d6a5a9f54137)
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/10946d1f-8ac2-441b-a412-b81946ae74d0)
