### ISSUE TITLE
Thumbnail (preview image) pour le partage de l'url sur les réseaux

### ISSUE THREAD

**Issue by JulienParis** [betagouv/transition-ecologique-entreprises-widget#289]
cf : 

- https://www.opengraph.xyz/
- https://ogp.me/
- https://blog.hubspot.com/marketing/open-graph-tags-facebook-twitter-linkedin

**Comment by ColineLebaratoux** [comment]
<title>Transition écologique des entreprises</title>
<meta name="description" content="Des accompagnements et financements pour m'aider à réduire l'impact environnemental de mon entreprise">


<meta property="og:url" content="https://mission-transition-ecologique.beta.gouv.fr/">
<meta property="og:type" content="website">
<meta property="og:title" content="Transition écologique des entreprises">
<meta property="og:description" content="Des accompagnements et financements pour m'aider à réduire l'impact environnemental de mon entreprise">
<meta property="og:image" content="https://opengraph.b-cdn.net/production/documents/11d022bd-3b11-40a2-bb85-18c54800b4c8.png?token=oGRvPHXfY6M67XDFLR0nwzN-glyJMBksqPonctLgrno&height=676&width=1200&expires=33241422744">


<meta name="twitter:card" content="summary_large_image">
<meta property="twitter:domain" content="mission-transition-ecologique.beta.gouv.fr">
<meta property="twitter:url" content="https://mission-transition-ecologique.beta.gouv.fr/">
<meta name="twitter:title" content="Transition écologique des entreprises">
<meta name="twitter:description" content="Des accompagnements et financements pour m'aider à réduire l'impact environnemental de mon entreprise">
<meta name="twitter:image" content="https://opengraph.b-cdn.net/production/documents/11d022bd-3b11-40a2-bb85-18c54800b4c8.png?token=oGRvPHXfY6M67XDFLR0nwzN-glyJMBksqPonctLgrno&height=676&width=1200&expires=33241422744">

**Comment by ColineLebaratoux** [comment]
<title>Transition écologique des entreprises</title>
<meta name="description" content="Des accompagnements et financements pour m'aider à réduire l'impact environnemental de mon entreprise">


<meta property="og:url" content="https://mission-transition-ecologique.beta.gouv.fr/">
<meta property="og:type" content="website">
<meta property="og:title" content="Transition écologique des entreprises">
<meta property="og:description" content="Des accompagnements et financements pour m'aider à réduire l'impact environnemental de mon entreprise">
<meta property="og:image" content="https://opengraph.b-cdn.net/production/documents/11d022bd-3b11-40a2-bb85-18c54800b4c8.png?token=oGRvPHXfY6M67XDFLR0nwzN-glyJMBksqPonctLgrno&height=676&width=1200&expires=33241422744">


<meta name="twitter:card" content="summary_large_image">
<meta property="twitter:domain" content="mission-transition-ecologique.beta.gouv.fr">
<meta property="twitter:url" content="https://mission-transition-ecologique.beta.gouv.fr/">
<meta name="twitter:title" content="Transition écologique des entreprises">
<meta name="twitter:description" content="Des accompagnements et financements pour m'aider à réduire l'impact environnemental de mon entreprise">
<meta name="twitter:image" content="https://opengraph.b-cdn.net/production/documents/11d022bd-3b11-40a2-bb85-18c54800b4c8.png?token=oGRvPHXfY6M67XDFLR0nwzN-glyJMBksqPonctLgrno&height=676&width=1200&expires=33241422744">

**Comment by JulienParis** [comment]
PR liée #526

**Comment by yvalentin** [comment]
Je pense que nous pouvons améliorer les meta et le title sur les pages dispositifs
Techniquement voir : https://github.com/vueuse/head
