### ISSUE TITLE
Avoir un menu burger opérationnel  (header responsive)

### ISSUE THREAD

**Issue by JulienParis** [betagouv/transition-ecologique-entreprises-widget#293]
Nous devons voir apparaitre les 2 liens Accueil et Annuaire derrière le menu burger sur tablette/smartphone

**Comment by JulienParis** [comment]
Résolution en #332, en attente de review (pas encore mergé en préprod)

**Comment by ColineLebaratoux** [comment]
ok c'est validé ! 
On pourra faire évoluer l'UI du menu burger dans une prochaine version :)
