### ISSUE TITLE
Problèmes de scroll

### ISSUE THREAD

**Issue by JulienParis** [betagouv/transition-ecologique-entreprises-widget#294]
Note: Ce ticket centralise plusieurs problèmes similaires relatifs au comportement actuel de _scroll_. Les tickets concernés et rendus tout ou partiellement caduques sont les #172, #200, et #284 

- [x] Entre chaque piste de question, s'assurer qu'on est bien en haut de la question (aujourd'hui la position du scroll reste bloqué sur celui de la précédente question) 
  - **Doublon possible avec ces autres points**
  - [x] entre chaque question, au clic sur suivant la position du scroll reste au niveau de la question précédente
  - [x] Entre 2 questions, la position du scroll de la page suivante est maintenue au niveau de la position de la question précédente
- [x] Supprimer l'effet de mouvement "scroll to top" pour créer une transition franche entre la page de résultat et une page dispositif
  - **Doublon possible avec ces autres points**
  - [x]  Remonter directement en haut de page sans effet de balayage. 
  - [x] (sans effet de mouvement scroll to top). (peut-être traité avec le ticket #170 ?)
- [x] Sur la page de résultats, maintenir la position du scroll au niveau du résultat cliqué pour faciliter les allers retours entre la page de résultats et les fiches dispositifs (retour utilisateur “C’est dommage on retourne toujours au premier étage de la page, il faut tout redescendre. c’est pénible.”) 
  - **Doublon possible avec des autres points**
  - [x] au clic sur un dispositif la position du scroll reste au niveau de la position de la page de résultat
  - [x] Au clic sur un dispositif sur la page de résultat, la position du scroll de la page de résultats est maintenue sur la page dispositif

https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/96e4553c-4794-406a-8a4c-e65485e9455b

**Comment by jbledevehat** [comment]
Attention @JulienParis doublon avec la #284 > fusionne stp le contenu

**Comment by JulienParis** [comment]
@jbledevehat J'ai marqué la #284 avec le label `duplicate` et proposé qu'on ferme le 284 : https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/284#issuecomment-1816456647

**Comment by JulienParis** [comment]
@ColineLebaratoux et @jbledevehat => J'ai mis en `staging` la branche `fix/scroll-problems-294` qui cherche à résoudre l'ensemble des soucis de scroll relevés dans ce ticket. 

https://staging.mission-transition-ecologique.incubateur.net/q

Si le résultat en `staging` vous satisfont vous pouvez passer ce ticket en `valid` et on pourra le merger en `preprod`

PS: je viens de me rendre compte de 2 ou 3 aberrations en changeant d'écran pour tester. Si vous voyez des trucs bloquants vous pouvez le dire en commentaire ici et/ou créer des nouveaux tickets...

**Comment by ColineLebaratoux** [comment]
Yes !!! c'est top 👏
