### ISSUE TITLE
Corrections responsive : revoir la marge et enlever les tags du fils d'ariane

### ISSUE THREAD

**Issue by JulienParis** [betagouv/transition-ecologique-entreprises-widget#296]
Note: Le reste des corrections responsives jugées moins prioritaires sont dans #274 

Note: Ce ticket reprend des issues de la #172 où les problèmes listés étaient trop disparates pour être réglés selon le principe de "1 issue === 1 branche de travail === 1 merge" pour des mises en prod et des déploiements plus fluides

- [x] diminuer les marges gauche droite sur l'ensemble du formulaire 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/0100c9b7-eb71-4d41-b5a0-40c444457d84)
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/644998ae-94f9-43bf-9ebd-dbe26e715c5c)

- [x] enlever les tags correspondant au fil d'ariane sur la page résultat

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/b11ef364-f46e-4ee9-b153-c2430e0a98b7)

**Comment by JulienParis** [comment]
note: @ColineLebaratoux ticket réglé avec la PR #306 passée en `preprod`. Sur #306 tu pourras voir les _screenshots_ comparant "avant / après". Tu peux aussi tester en _live_ [en allant sur la preprod](https://preprod.mission-transition-ecologique.incubateur.net/). 

Si les modifs te paraissent correctes et répondre correctement aux problèmes de _responsive_ listés dans ce ticket tu peux supprimer le tag "nedd validation" et apposer le tag "valid", ça me signifiera qu'on peut alors le passer en prod.

**Comment by ColineLebaratoux** [comment]
J'ai l'impression que tu as retiré le fil d'ariane sur l'ensemble du parcours en version mobile. C'est ok, uniquement si le bouton back permet de revenir en arrière sur les questions (#277). Ce sera le cas ?

**Comment by JulienParis** [comment]
> J'ai l'impression que tu as retiré le fil d'ariane sur l'ensemble du parcours en version mobile. C'est ok, uniquement si le bouton back permet de revenir en arrière sur les questions (#277). Ce sera le cas ?

Alors oui, mais il faut juste bien considérer qu'on parle au futur (proche ou moyen terme) car la question de l'historique de navigation est abordé non seulement dans la #277 mais c'est surtout l'objet de la #292

**Comment by ColineLebaratoux** [comment]
@jbledevehat, sur ce ticket, je proposais de supprimer le nuage de tag (qui sert de fil d'ariane), sur la page de résultats. En revanche, si le bouton back n'est pas opérationnel pour revenir en arrière sur les questions, ca risque d'être délicat pour la navigation. Tu en penses quoi, on remet les tags ?

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/c1c7a10a-0759-4f68-b5a1-be3b0f7e6821)

**Comment by JulienParis** [comment]
question : @ColineLebaratoux @jbledevehat pardon j'ai du lire trop vite la demande concernant le fil d'ariane et effectivement je l'ai enlevé (en responsive) sur tout le parcours (page résultat ou pas). Je peux faire si vous le souhaitez un nouveau ticket + la modif pour ne plus avoir ce fil d'Ariane sur la page résultat mais quand même l'avoir durant le parcours.

note : si on a quand même ce fil d'Ariane durant le parcours le nombre de tag peut être assez important sur le parcours "Je ne sais pas par où commencer"
