### ISSUE TITLE
Nous n'avons plus l'effectif de l'entreprise dans Brevo

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/transition-ecologique-entreprises-widget#302]
Il nous faut voir l'info STRUCTURE _SIZE dans le tableau Brevo

**Comment by pierrecamilleri** [comment]
à toute fin utile, la donnée d'entreiprise est disponible dans le champ "all_data" dans le champ "entreprise . effectif".

C'est un peu fastidieux mais peut être utile lorsque l'info `STRUCTURE_SIZE` est absente
