### ISSUE TITLE
correction de bugs sur mobile

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#328]
- [x] A la dernière question du questionnaire "je ne sais pas par où commencer", les checkbox n'apparaissent pas
- [x] A la dernière question du questionnaire "je ne sais pas par où commencer", l'espace entre l'émoji"⚡️" et les 2 audits est trop important. 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/8e4cc4b7-956b-47eb-8eaa-47d1b539dac1)

**Comment by JulienParis** [comment]
@ColineLebaratoux Je viens de regarder le site de prod sur Chrome / Firefox / Safari (cf screenshot + bas dans cet ordre de navigateurs) sur laptop, et sur Safari / Firefox / Chrome sur iphone, mais les icônes apparaissent bien en prod et les espaces sont corrects (sauf sur Safari pour les espacements, fix sur PR #524) =>

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/6a3fbb86-4269-467c-90ef-476778d2249d)

Peut-être un souci de rafraîchissement de cache de ton côté ? si ce n'est pas le cas merci de me dire sur quelle config exactement tu as rencontré ce souci.

En attendant la preview est sur : https://tee-frontend-preprod-pr524.osc-fr1.scalingo.io

**Comment by ColineLebaratoux** [comment]
@JulienParis 
1/ je ne reproduis plus le problème avec les checkbox manquantes

2/ En effet, le problème de l'espacement trop important pour les 2 audits énergetique est rencontré sur safari. 
Je n'ai pas compris si tu as pu le corriger ? 
Est-ce que je peux le tester ?

**Comment by JulienParis** [comment]
@ColineLebaratoux oui c'est bien réglé maintenant sur safari =>

<img width="1388" alt="Capture d’écran 2024-01-31 à 14 16 14" src="https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/905f889e-4610-4ee6-81b2-30a732957307">

Je merge dans preprod
