### ISSUE TITLE
Mettre en place le tri de pertinence par thématique dans le parcours "j'ai un objectif en tête"

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#336]
- [ ] Ajouter un tri de pertinence : mettre les dispositifs mono thématique en premier.
1/ les dispositifs spécifique à une thématique en premier 
2/ les dispositifs multi thématiques en deuxième

- [ ]  Supprimer et remplacer le filtre actuel par rapport aux natures de dispositifs (moins pertinents que ce filtre mono-thématique)
NB : Le filtrage est fait dans le back aujourd’hui 

A la suite du ticket https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/174 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/ee5f746f-8c2a-4b4b-a596-dc0e09efb127)

ex de retour utilisateur _"c’est étrange de retrouver cette étude (projet de recherche) dans diminuer ma consommation d’eau. Sobriete et résilience des territoires, je vois pas l’eau ?  Mais au début, j’aimerais des propositions vraiment plus pertinentes. peut-être à la fin je peux trouver des trucs plus large."_

_“là j’avais pris sur l’eau. C’est là ou c’est etonant, j’ai demandé la catégorie eau mais j’ai l’impression qu’on me propose toutes les aides auxquelles je peux prétendre. 
on a l’impression que la catégorie eau n’est pas prise en compte. 
Je vois “contrat chaleur renouvelable” ca a un rapport avec l’eau ? 
Je suis assez étonné quand même. “_

**Comment by ColineLebaratoux** [comment]
réponse de Pierre : 

> Par exemple si les déchets ne sont pas un enjeux pour lui, nous ne lui proposons pas un audit déchet (même s'il n'en a jamais fait). est-ce le cas / est-ce possible ?


Oui c'est possible (pour les deux suggestions) mais par contre il y a des prérequis un peu longs pour ne pas casser le refiltrage de la page des résultats au passage :  notamment le ticket https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/352 qui lui-même dépend de https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/164.

En effet, ces conditions de filtrage s'écrivent avec des combinaisons de OU et ET, et l'implémentation du refiltrage fait puor l'instant l'hypothèse d'une unique liste OU à plat.

Par exemple dans le second cas, la condition s'écrirait si je comprends bien (en pseudo-publicodes) : 

une de ces conditions :
    - toutes ces conditions :
        - objectif = "bâtiment"
        - objectif = "énergie"
  - ... # éventuellements d'autres conditions
EDIT : il y a un tout petit plus de complexité à gérer car le filtrage devient différent pour le parcours "Je ne sais pas par où commencer" et "J'ai un objectif en tête" (ou le refiltrage), ce qui n'est pas trivial à mutualiser proprement !

**Comment by ttdm** [comment]
Lien scalingo : https://tee-preprod-pr692.osc-fr1.scalingo.io/

Explications sur le tri :
Uniquement sur la piste "j'ai un objectif en tête", ajout d'un tri sur le nombre d'objectifs qui est effectué en plus et après le tri historique et qui privilégie les dispostifs ayant moins d'objectifs ciblé.

Comportement du tri :
- Si un programme à moins d'objectif ciblé, il sera privilégié.
- En cas d'égalité d'objectifs ciblé, l'ancien tri est toujours appliqué.
