### ISSUE TITLE
Affluence (autoscalling Scalingo)

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/transition-ecologique-entreprises-widget#338]
Face à un lancement proche, voir pour gérer l'affluence avec Scalingo

**Comment by JulienParis** [comment]
Note: pour mémoire la gestion des ressources directement dans l'application Scalingo se trouve ici (dans ce cas avec l'app `tee-frontend`, mais la même chose est valable pour `tee-backend`) =>

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/101cd3ff-58f8-40df-9673-33bae29abcce)
