### ISSUE TITLE
Intégration : data des nouvelles pistes de questions

### ISSUE THREAD

**Issue by JulienParis** [betagouv/transition-ecologique-entreprises-widget#35]
cf nouvelle arborescence / arbre de décisions : https://miro.com/app/board/uXjVPgXnd3A=/

**Comment by jbledevehat** [comment]
Pour précision du board sur notre sprint https://miro.com/app/live-embed/uXjVPgXnd3A=/?moveToViewport=9455,-7146,7016,3666&embedId=736193765490
