### ISSUE TITLE
Reformulation & évolution UI du message de confirmation d'envoi du formulaire

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/transition-ecologique-entreprises-widget#369]
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/7ada946b-4370-4dcd-ad13-2f828eec8e80)

- [x] Reformuler et corriger l'UI du texte de message de confirmation : 
- Enlever la promesse "sous 5 jours" => dire plutôt "prochainement" que de s'engager sur une durée. (Une contrainte remontée par Bpifrance)
- repréciser qui est l'opérateur destinataire (comme sur le formulaire) => cf retour utilisateur _"je sais pas où ça va...ma demande va tomber aux oubliettes”_
- Préciser l'objectif du contact. cf retour utilisateur _"Mais on sait pas bien pourquoi on complète le formulaire en fait"._
- Ajouter le contact possible par mail (c'est ce que fait bpifrance ?) => cf retour utilisateur _"on est recontacté par mail ou téléphone ? merci pour votre appel : Par téléphone ? autant vous dire que ça va pas trop plaire"._ 

=> Proposition : 
**"Un conseiller de "nom de l'opérateur" vous contactera prochainement par mail ou par téléphone pour échanger sur votre besoin et répondre à vos questions."** 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/f175a33b-b836-4670-8949-96c79835725b) 
=> voir [maquette figma](https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=4302%3A86487&mode=design&t=CPWCpgYUy6QNKGSk-1)

---

- [x] Corriger "merci d'avance pour votre appel" => "Merci d'avance pour votre retour"

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/e4b3ba49-9051-43f4-a4a2-7c483f41d297)

**Comment by ColineLebaratoux** [comment]
@jbledevehat que penses-tu de la proposition de reformulation ?

**Comment by jbledevehat** [comment]
Parfait oui

**Comment by JulienParis** [comment]
@ColineLebaratoux pour validation => review app : https://tee-frontend-preprod-pr403.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
Merci @JulienParis 
- attention le scroll up n'est pas en place. Au clic sur "envoyer", on arrive sur le bas de la page. Alors qu'on devrait être centré sur le message de confirmation.
- Si je chipote de l'UI : est-ce que tu peux avoir un check plus fin comme l'icône de la maquette (qui provient du Design system)
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/de0a0baf-0b9f-4850-9deb-909d2e7fbe6f) => mais si tu as d'autres choses à faire, je comprendrai ! 😁

**Comment by JulienParis** [comment]
J'ai fait une petite modif pour ajouter le scroll

Sinon j'ai regardé les [icônes du dsfr](https://www.systeme-de-design.gouv.fr/elements-d-interface/fondamentaux-techniques/icone) et je n'ai pas trouvé ce check + fin : les deux semblent identiques entre remixIcon et DSFR. 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/6cda7bd8-d50d-41a3-bd8e-fb168117be02)

**Comment by ColineLebaratoux** [comment]
Ok, c'est pas très grave. Au cas où, il s'appelle "check-line"

**Comment by ColineLebaratoux** [comment]
Pour le scroll ça fonctionne, merci ! 
En revanche, est-ce que tu penses que tu peux centrer le cadre du message dans la page. Comme ceci :



![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/b4e0cac4-7a38-4dc5-af9b-1ba2d485c800)

**Comment by JulienParis** [comment]
@ColineLebaratoux le scroll back devrait désormais centrer sur le milieu du bloc de message maintenant

**Comment by ColineLebaratoux** [comment]
@JulienParis, J'ai testé sur ce lien https://tee-frontend-preprod-pr403.osc-fr1.scalingo.io/  mais au clic sur "envoyer", on arrive sur le bas de la page (et pas centré sur le milieu du bloc de confirmation)



![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/46cff2d6-dfc6-4dab-bade-2787a95a0cb4)

**Comment by ColineLebaratoux** [comment]
le clic sur "envoyer" ne fonctionne plus. (la flèche de gauche s'efface, le message d'erreur / confirmation ne s'affiche pas)

**Comment by JulienParis** [comment]
@ColineLebaratoux je pense avoir réglé les pbs (bug du clic sur "envoyer" + scroll back sur le centre du message). Ca marche en local du moins et ça a pu déployer.  Je te laisse y jeter un oeil pour validation

**Comment by ColineLebaratoux** [comment]
@JulienParis, 
✅ le bug du clic sur "envoyer" est résolu 
❌ En revanche pas celui du scroll

**Comment by JulienParis** [comment]
@ColineLebaratoux je viens de piger pourquoi le scroll ne fonctionne pas chez toi, tu utilises certainement Safari (et de mon côté j'utilise Firefox en général). La fonction que j'utilise pour le scroll back s'appelle `scrollIntoView` ([documentation ici](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView)), avec l'option `block: 'center'`, et il se trouve que tout marche avec cette fonction partout SAUF que sur Safari `center` est la seule option qui ne fonctionne pas =>

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/efcba711-bf39-447a-a0ce-d9868dcbbf8a)

Pour éviter de faire qq chose de trop custom mon avis serait de rester sur `block: start`, du moins si ça te convient...

**Comment by ColineLebaratoux** [comment]
hello @JulienParis ! Mes tests sont fait sur chrome

**Comment by ColineLebaratoux** [comment]
Le scroll est calé sur le haut du message d'erreur. Est-ce possible de le caler au milieu du message ? (même remarque #329)


![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/cb620b63-03bf-441b-bb6a-c51e6448ee2e)
