### ISSUE TITLE
Affichage bug sur les formations

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/transition-ecologique-entreprises-widget#375]
Sur les formations nous avons un titre au dessus du formulaire avec un message buggé

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/22809387/8d13b36f-e284-4635-983d-5e9ab9d8d180)

**Comment by yvalentin** [comment]
Le fix était très court et sans risque, je me suis permis de faire le check sur la review app (pour se rassurer) et d'envoyer en prod ;-)


Merge dans le preprod aussi !
