### ISSUE TITLE
Quelles évolutions pour intégrer les actions inspirationnelles à la plateforme ?

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#381]
En tant qu’utilisateur 🤷 néophyte,  je recherche des idées d’actions concrètes pour mon secteur d’activité pour m’inspirer.

**Comment by jbledevehat** [comment]
https://www.edf.fr/entreprises/eco-gestes?field_ec_activity_target_id=826&field_ec_category_target_id=813
