### ISSUE TITLE
Envoyer automatiquement les demandes vers Bpifrance à travers leur API

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/transition-ecologique-entreprises-widget#383]
Aujourd'hui nous devons envoyer les demandes manuellement vers Bpifrance à travers leurs API.
Envoyons celle-ci automatiquement afin de gagner du temps pour le service client.

1. Conserver les données dans Brevo pour stats, mail de reception...
2. Envoyer les données ensuite vers l'API
3. Selon succès ou erreur de transmission de Bpifrance vers Brevo d'un statut de transmission

**Comment by ColineLebaratoux** [comment]
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/ca6cd54a-dac0-4c88-b8e8-95721bd2a6d9)

**Comment by yvalentin** [comment]
@jbledevehat @ColineLebaratoux @celinebagault 
Pour information, nous n'envoyons jamais le companyName pour le moment dans API. Pour celà il faut faire une amélioration avec une récupération des infos siret depuis le back !

**Comment by yvalentin** [comment]
De plus, on a un timout à 3 sec lors de l'appel à API de BPI. J'ai remarque que 1 sec n'était pas suffisant que nous avions bcp d"erreurs en retour d'appel (timeout). Ce qui en vrai est quand même beaucoup 3 sec. Il faudrait voir pour améliorer ce point pour ne pas détériorer l'expérience utilisateur sur notre platforme !
