### ISSUE TITLE
Ajouter la page "Echanger avec un conseiller" (Place des Entreprises) à la place des mailto

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/transition-ecologique-entreprises-widget#385]
_Mise à jour du brief 12/12 par @ColineLebaratoux_ 

On sépare les contacts en plusieurs flux : 
- **flux 1(principal)**  : via les formulaires de contact situés sur chaque page dispositif pour recevoir les "candidatures" par dispositif

- **flux 2 :** via l'adresse mail "france-transition@beta.gouv.fr" dédié à recevoir les problèmes rencontrés sur la plafeforme
Ce lien est affiché sur un bandeau en bas de page sur les pages du footer (accessibilité, mentions légales, données personnelles) 
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/91bab270-180f-49d6-9155-a353db571ed9)
Ce lien est mentionné dans le corps de ces 3 pages et sur le message d'erreur 500 [cf ticket 329](https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/329)

TO DO
- [x] Pour la page accessibilité, corriger la mention "merci de nous contacter via notre formulaire en ligne", par ""merci de nous contacter par mail à : france-transition@beta.gouv.fr" (lien cliquable)

- [x] Pour la page données personnelles, on remplace "Merci d'envoyer un e-mail à cette adresse" par "merci de nous contacter par mail à : france-transition@beta.gouv.fr" (lien cliquable)

- **flux 3 :** (à créer) via une page contact dédiée (ouverte dans un nouvel onglet) intégrant l'iframe de Place des entreprises, dédié à recevoir les demandes des utilisateurs n'ayant pas trouver ce qu'il recherchait dans les parcours principaux du site. 
La création de ce flux 3 permet d'éviter à l'équipe de recevoir des mails, et de diriger le flux de demandes directement vers Place des entreprises.
Ce lien est affiché sur un bandeau en bas de page sur les pages résultats des 2 parcours, les fiches dispositifs et sur la page Annuaire : 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/d1533140-10c7-439c-8300-b215c0a9dbc1)

TO DO
- [x] Correction du texte sur le bandeau de contact "Vous souhaitez échangez avec un conseiller ?
Vous ne trouvez pas ce que vous recherchez ? écrivez-nous, nous vous mettrons en relation avec le bon interlocuteur pour répondre à votre question."

- [x] Créer une page "échanger avec un conseiller" avec l'[iframe de Place des entreprises](https://les-aides.fr/echanger-avec-un-conseiller) comme sur les [aides.fr](http://aides.fr/), en arrivant directement sur le niveau "[Mettre en oeuvre votre transition écologique & RSE] 

- [x] Possibilité d'afficher le lien dans le footer (en mineur pour ne pas court-circuiter les autres flux principaux)

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/e77de1b4-07af-476f-a201-03f27c512843)

**Comment by yvalentin** [comment]
@ColineLebaratoux @jbledevehat
> Avoir le même CTA, format bouton (et non lien) (https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/286#issuecomment-1840828271)

Est-ce que ça vous va d'avoir un lien avec une balise <a href="...">...</a> avec biensur le format visuel du button ?

**Comment by yvalentin** [comment]
Il manque peut être quelques choses ici (page [données personnelles](https://mission-transition-ecologique.beta.gouv.fr/donnees-personnelles)) ?

![image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/1521862/b8131fb6-af9a-4f77-8f29-e5d33a38296b)

**Comment by ColineLebaratoux** [comment]
je reprends la conversation ici : 
- @jbledevehat, je questionne le point 1.  "Avoir un lien dans le header "Échanger avec un conseiller" vers cette page" : je crains que ça court-circuite le parcours du formulaire et que ça génère plus de demandes non adressées. Y-a t-il une raison pour le remettre en avant ? Sinon, je proposerais bien de garder les bandeaux actuels :
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/11bbaa89-04f4-42af-803f-e85534bcb182)
On en rediscute si tu veux @jbledevehat !

- Voici une proposition de maquette pour la [page contact ](https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=4365%3A23833&mode=design&t=3eV2my1KZDyFGAfN-1)

- @yvalentin, est-ce que tu peux m'expliquer ce que c'est une balise <a href="...">...</a> ?

- @yvalentin, bien vu pour les textes dans les pages du footer !
@jbledevehat ok pour toi ? 
1) Pour la page accessibilité, au niveau de la mention "merci de nous contacter via notre formulaire en ligne", on peut ajouter un lien menant vers la nouvelle page contact 
2) Pour la page données personnelles, on remplace "Merci d'envoyer un e-mail à cette adresse" par "Merci de nous contacter via notre formulaire en ligne" + lien menant vers la nouvelle page contact

**Comment by ColineLebaratoux** [comment]
- @yvalentin, est-ce que tu peux m'expliquer ce que c'est une balise 
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/133fc4c2-47ae-4b49-ad93-b3838d0fe96e)



- @yvalentin, bien vu pour les textes dans les pages du footer !
@jbledevehat ok pour toi ? 
1) Pour la page accessibilité, au niveau de la mention "merci de nous contacter via notre formulaire en ligne", on peut ajouter un lien menant vers la nouvelle page contact 
2) Pour la page données personnelles, on remplace "Merci d'envoyer un e-mail à cette adresse" par "Merci de nous contacter via notre formulaire en ligne" + lien menant vers la nouvelle page contact

**Comment by ColineLebaratoux** [comment]
@yvalentin Après discussion ce matin avec jb et julien, j'ai mis à jour la description du ticket. N'hésite pas si tu as des questions, merci !

**Comment by ColineLebaratoux** [comment]
Evolution long terme documentée ici : https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/415

**Comment by jrayneau** [comment]
Voici le lien de l'"iframe" à intégrer :

https://place-des-entreprises.beta.gouv.fr/aide-entreprise/france-transition-ecologique/theme/environnement-transition-ecologique

**Comment by jrayneau** [comment]
[Intégration du service Place des Entreprises - Iframe-5.pdf](https://github.com/betagouv/transition-ecologique-entreprises-widget/files/13650607/Integration.du.service.Place.des.Entreprises.-.Iframe-5.pdf)

**Comment by ColineLebaratoux** [comment]
ok pour la bulle 💬

**Comment by yvalentin** [comment]
Done !
@ColineLebaratoux Tu peux faire la review fonctionnel ici
https://tee-frontend-preprod-pr424.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
C'est tout bon ! 
Est-ce que tu pourrais juste diminuer la taille des icones ? 

- 💬 sur le bouton 
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/2ceb1bd6-8792-4f6a-acba-d5d42de3ac75)

- 💬 idem dans le footer
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/fd932611-9afd-4ca0-932c-80e97f22cbfa)

- ✉️ idem sur le bouton
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/d0297549-c7cd-4f01-b842-8aaf979d4849)

**Comment by yvalentin** [comment]
Merci à @jrayneau , j'ai pu ajouté la même techno que sur "aide..." et donc l'iframe s'affiche completement sans le double scrolling et s'affiche aussi correctement sur un resize de la page ! Cool !!

**Comment by yvalentin** [comment]
@JulienParis Est-ce que tu sais faire le dégraissage demandé par Coline juste au dessus ?

**Comment by ColineLebaratoux** [comment]
- [ ] Correction au niveau du formulaire de l'iframe. Au clic sur suivant, la position du scroll doit être en haut de la page
(particulièrement important entre l'étape 1 et l'étape 2 / et entre l'étape 3 et le message de validation. 

screenshots de la position actuelle de la page au clic sur suivant : 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/0369e8cc-0efc-4181-b016-1c4a8f2efe79)

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/81a30199-2726-4859-ad25-ffdec289a43f)

**Comment by ColineLebaratoux** [comment]
@yvalentin se rapproche de PDE pour demander l'ajustement de l'iframe

**Comment by yvalentin** [comment]
Conversation avec les dev de PDE:

> Yohann Valentin
[3:05 PM](https://mattermost.incubateur.net/betagouv/pl/fx9nqnuc1pna7nnmtj6ed6f1oa)

Bonjour @Claire Zuliani et @Lucien,
Nous avons intégré l'iframe pour la page "échanger avec un conseiller" de Place des Entreprise.
Vous pouvez visualiser ça sur le lien suivant :
https://tee-frontend-preprod-pr424.osc-fr1.scalingo.io/echanger-avec-un-conseiller

Lorsque nous cliquons sur des liens, nous aimerions avoir un scollTo (top) afin que l'utilisateur se retrouve au bon niveau de la page !

J'ai pu voir que pour les-aides.fr les liens comportent un hashtag afin de faire le défilement sur la haut de page au niveau ([#section-breadcrumbs](https://mattermost.incubateur.net/betagouv/messages/ef828225c6c9a5de6a2a75caa50617406c246751#)).

Pouvons-nous avoir le même systeme avec le hashtag sur la balise "main" ayant id = content ([#content](https://mattermost.incubateur.net/betagouv/messages/ef828225c6c9a5de6a2a75caa50617406c246751#)) ?
Ou aussi avoir un breadcrumb ?  


> Claire Zuliani
[3:24 PM](https://mattermost.incubateur.net/betagouv/pl/hnkp7135htyzicctgayau1jknc)

ok, les balises présentent ou non dépendent du type d'iframe, et j'ai l'impression que sur votre iframe une balise a sauté. Merci pour ton retour ! Je créé un ticket 

(bon, malheureusement, le destin des tickets créés juste avant les congés, c'est généralement d'être traité à la rentrée...)

c'est quoi le degré d'urgence, pour vous ?


> Yohann Valentin
[3:26 PM](https://mattermost.incubateur.net/betagouv/pl/hd3yr7x14iyjm8snefc6q9hb7e)

Pas de soucis pour la réparation en tout début d'année prochaine. Nous sommes aussi en congés (pour la plus part la semaine pro).
Est-ce que c'est envisageable pour la semaine du 2 janvier ?

> Claire Zuliani
[3:28 PM](https://mattermost.incubateur.net/betagouv/pl/mf95fqi4pjytfyiza43skxq8re)

oui, je suis moi aussi de retour cette semaine là !

**Comment by jbledevehat** [comment]
Attention source=mailto&to=undefined dans la page mentions legales
