### ISSUE TITLE
Filtrer le dispositif "coup de pouce chauffage" pour les entreprises du tertiaire

### ISSUE THREAD

**Issue by celinebagault** [betagouv/transition-ecologique-entreprises-widget#391]
Le coup de pouce chauffage est un dispositif réservé aux bâtiments du tertiaire. 

Or, beaucoup d'entreprises le sélectionnent en raison de son titre accrocheur, sans appartenir au secteur tertiaire (et la description longue ne met pas tellement en valeur ce critère d'éligibilité). 

Pourrait-on filtrer ce dispositif à partir du code NAF de l'entreprise pour qu'il ne soit visible que pour les entreprises du tertiaire ?

**Comment by pierrecamilleri** [comment]
Concrètement, ne pas proposer ce dispositif pour les sections NAF (niveau 1) : 

- A Agriculture, sylviculture et pêche
- B Industries extractives
- C Industrie manufacturière
- D Production et distribution d'électricité, de gaz, de vapeur et d'air conditionné
- E Production et distribution d'eau ; assainissement, gestion des déchets et dépollution
- F Construction
