### ISSUE TITLE
Afficher la date de fin du dispositif sur la fiche dispositif

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#394]
**Afficher la date de fin du dispositif sur la fiche dispositif**  

- [x] afficher la date de fin dans l'une des cases "caractéristiques " de la fiche dispositif, dans le format "Disponible jusqu’au JJ/MM/AAAA" ou afficher ["aide disponible"](https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=4414%3A67643&mode=design&t=kcwAKuYtI96Bl0uh-1) quand pas de date renseignée

- [x] Pour ne pas ajouter une cinquième case (et tasser les contenus), supprimer la case "nature du dispositif" pour remplacer par "date de fin". 

- [x] Afficher la nature du dispositif en tag sur l'image (permet en plus de gagner en cohérence avec l'affichage sur la liste de résultats) 

- [x] ne pas afficher le dispositif dans l'annuaire et dans les résultats lorsqu'il n'est pas commencé ou lorsqu'il est terminé

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/9d0fd1a7-fdd4-4c15-badc-39a405da9bdc)

ticket data lié #429 
ticket front lié #430 (affichage aide non disponible)

**Comment by ColineLebaratoux** [comment]
@jbledevehat qu'en penses-tu ?

**Comment by jbledevehat** [comment]
Super oui :-)

**Comment by JulienParis** [comment]
@pierrecamilleri il faudra juste que je fasse un point avec toi pour vérifier si les dispositifs qui ne sont plus actifs apparaissent ou pas dans la liste des yaml (pour pouvoir intégrer dans la PR #486 les demandes du ticket #430)

**Comment by ColineLebaratoux** [comment]
Super, c'est bon !
