### ISSUE TITLE
Envoyer des mails d'accusé de réception génériques 

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#399]
Envoyer des mails d'accusé de réception génériques => [voir page notion](https://www.notion.so/accelerateur-transition-ecologique-ademe/Mails-g-n-riques-cba07b0aa21c48448e27de80c242742f?pvs=4)
- [ ] Coder l'envoi d'email, adapter la pipeline d'opportunité en conséquence.

**Version court terme**
On envoie automatiquement des mails d’AR génériques pour tous les dispositifs **sauf Bpifrance** (Bpifrance se charge de l'envoi de ses propres mail d'AR)

NB : Céline envoie également manuellement un mail supplémentaire avec des précisions sur les dispositifs activables en autonomie [(cf notion)](https://www.notion.so/accelerateur-transition-ecologique-ademe/Mails-dispositifs-activables-en-autonomie-5feec63c8e474a91859db36241c0cde7?pvs=4)

En lien avec : #395, #399 
Dépend de #482 

---
- [x] Confirmer la solution Brevo pour l'envoi des mails 
- [x] Ecrire le mail d'AR générique => [voir page notion](https://www.notion.so/accelerateur-transition-ecologique-ademe/Mails-g-n-riques-cba07b0aa21c48448e27de80c242742f?pvs=4)
- [x] Creuser la question des données personnelles (desinscription ? obligation de présenter un mail contact) @jrayneau 

---
Pour info : 
**Version moyen terme**

- On envoie automatiquement des mails d’AR génériques (via brevo ? à confirmer) pour tous les dispositifs sauf Bpifrance et sauf les dispositifs activables en autonomie
- Bpifrance envoie ses propres mails d’AR
- On envoie spécifiquement un mail pour les dispositifs activables en autonomie (différent des générique car plus précis)
- On fait évoluer la donnée et la structure des étapes pour intégrer des urls (cf ticket https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/498#issue-2086365865)
- Céline peut arrêter d’envoyer manuellement les mails d’AR avec l’url pour les dispositifs activables en autonomie
- Pour l’ensemble des dispositifs, on mesure le taux d’activation par l’envoi du formulaire (=1 opportunité)

**Version long terme**

- On supprime le formulaire de contact pour les dispositifs activables en autonomie (cf ticket https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/395#issue-2030441924)
- On défini une autre méthode pour mesurer le taux d’activation pour les dispositifs activantes en autonomie (ex : enregistrer l’opportunité à l’ouverture de la fiche / ou intégrer un fonctionnalité de partage par mail : https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/516#issue-2094290392)**

---
- [ ] Revoir la mise en page du mail sur brevo @ColineLebaratoux

**Comment by ColineLebaratoux** [comment]
Y-a t-il un contenu spécifique à écrire pour les dispostifs Ademe : 
ex : 
"- vous allez être contacté par votre direction régionale afin de vous guider, de préciser les critères d’éligibilité et de vous apporter un éclairage sur les documents à compléter
- Vous pouvez ensuite déposer votre dossier + lien vers Agir"

**Comment by jbledevehat** [comment]
**Version court terme**

1. On envoie automatiquement des mails d’AR génériques (via brevo ? à confirmer) pour tous les dispositifs sauf Bpifrance
2. Bpifrance envoie ses propres mails d’AR [(cf notion)](https://www.notion.so/accelerateur-transition-ecologique-ademe/Mails-Bpifrance-116a808228414233966e84608a88082c?pvs=4)
3. Céline envoie manuellement un mail supplémentaire avec des précisions sur les dispositifs activables en autonomie [(cf notion)](https://www.notion.so/accelerateur-transition-ecologique-ademe/Mails-dispositifs-activables-en-autonomie-5feec63c8e474a91859db36241c0cde7?pvs=4)
4. On n’affiche aujourd’hui aucune url dans les fiches dispositifs
5. Pour l’ensemble des dispositifs, on mesure le taux d’activation par l’envoi du formulaire (=1 opportunité)

**Version moyen terme**

1. On envoie automatiquement des mails d’AR génériques (via brevo ? à confirmer) pour tous les dispositifs sauf Bpifrance et sauf les dispositifs activables en autonomie
2. Bpifrance envoie ses propres mails d’AR
3. On envoie spécifiquement un mail pour les dispositifs activables en autonomie (différent des générique car plus précis)
4. On fait évoluer la donnée et la structure des étapes pour intégrer des urls (cf ticket 
https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/498#issue-2086365865)
5. Céline peut arrêter d’envoyer manuellement les mails d’AR avec l’url pour les dispositifs activables en autonomie
6. Pour l’ensemble des dispositifs, on mesure le taux d’activation par l’envoi du formulaire (=1 opportunité)

**Version long terme**

1. On supprime le formulaire de contact pour les dispositifs activables en autonomie (cf ticket
https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/395#issue-2030441924)
2. On défini une autre méthode pour mesurer le taux d’activation pour les dispositifs activantes en autonomie (ex : enregistrer l’opportunité à l’ouverture de la fiche / ou intégrer un fonctionnalité de partage par mail
https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/516#issue-2094290392)**

**Comment by jrayneau** [comment]
(1) J'ai l'impression qu'il y a souvent confusion entre les deux notions d'activation et de conversion 
Lors du Comité Stratégique, on avait défini les mesures de cette façon   :
- le taux d'activation = Le nb de formulaire / le nb de visites sur le site
- le taux de conversion = le nb de dispositif activé / sur le nb de formulaire
(Peut-être que nous devrions changer les termes que l'on avait choisis ?)

(2) Pour le court terme, ça serait intéressant de préciser comment on compte mesurer le taux de conversion.
 (= par exemple en demandant régulièrement à chaque opérateur, comme baisse les watts, si les SIRETS listés se sont inscrits dans les 7 jours)

(3) Pour le moyen/long terme,  on avait évoqué d'autres possibilités intéressantes à creuser : 
- Stocker le SIRET à l'affichage de la fiche et vérifier si il y a eu conversion auprès de chaque opérateurs. 
- Ajouter un tracking si l'opérateur est capable de gérer des sources d'acquisition (j'en doute)

**Comment by ColineLebaratoux** [comment]
Pour mémoire : 
Proposition 1 : 


### Définir la solution technique pour envoyer le mail d'AR ? 

- [x] Brevo ?
- [ ] fait par le CRM de l'Ademe ?
- [ ]  créer un mail : contact.missiontransitionecologique@beta.gouv.fr ? 

---
### Définir la route court terme - moyen terme pour le sujet des mails d'Accusé de réception pour les dispositifs activables en autonomie

**Version court terme**
1. On envoie automatiquement des mails d’AR génériques via brevo (pour tous les dispositifs sauf Bpifrance et activables en autonomie)
2. Bpifrance envoie ses propres mails d’AR [(cf notion)](https://www.notion.so/accelerateur-transition-ecologique-ademe/Mails-Bpifrance-116a808228414233966e84608a88082c?pvs=4)
3. Céline envoie manuellement les mails d’AR avec le(s) url(s) pour les dispositifs activables en autonomie [(cf notion)](https://www.notion.so/accelerateur-transition-ecologique-ademe/Mails-dispositifs-activables-en-autonomie-5feec63c8e474a91859db36241c0cde7?pvs=4)
4. On n’affiche aujourd’hui aucune url dans les fiches dispositifs 
5. Pour l’ensemble des dispositifs, on mesure le taux d’activation par l’envoi du formulaire (=1 opportunité)


**Version moyen terme** 
1. On envoie automatiquement des mails d’AR génériques via brevo (pour tous les dispositifs sauf Bpifrance et activables en autonomie)
2. Bpifrance envoie ses propres mails d’AR 
3. On fait évoluer la donnée et la structure du tableau pour intégrer des urls (cf ticket https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/498#issue-2086365865)
4. On supprime le formulaire de contact pour les dispositifs activables en autonomie (cf ticket https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/395#issue-2030441924)
5. Céline peut arrêter d’envoyer manuellement les mails d’AR avec l’url pour les dispositifs activables en autonomie 
6. On défini une autre méthode pour mesurer le taux d’activation pour les dispositifs activantes en autonomie (ex : enregistrer l’opportunité à l’ouverture de la fiche / ou intégrer un fonctionnalité de partage par mail https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/516#issue-2094290392)**

**Comment by celinebagault** [comment]
Concernant le mail d'AR

```
Bonjour Madame Lefort,

Nous avons bien reçu votre demande déposée sur le site https://mission-transition-ecologique.beta.gouv.fr/ en date du 30/01/2024 et nous vous en remercions.

Elle concerne l’accompagnement "Rénovation Petit Tertiaire Privé”:
[“Faites-vous accompagner dans vos travaux de rénovation énergétique”](https://staging.mission-transition-ecologique.incubateur.net/aides-entreprise/renovation-petit-tertiaire-prive) 

Un conseiller de l’ADEME vous contactera prochainement par mail ou par téléphone pour échanger sur votre besoin et répondre à vos questions.

Récapitulatif de votre demande :
Bonjour, Mon entreprise a une activité de type "secteur".
Le dispositif "nom du dispositif" pourrait m'intéresser car j'ai pour projet de ...
J'ai besoin d'être accompagné(e) sur ...
Merci d'avance pour votre appel,
Amélie LEFORT
06 88 37 98 17
SIRET : 81221286800051
 
Pour toutes autres questions, vous pouvez nous envoyer un message à [france-transition@beta.gouv.fr](mailto:france-transition@beta.gouv.fr)

Nous vous souhaitons une très bonne journée,
L’équipe de Mission Transition Écologique
```

Quelques micro-modifications :
- en date du 30/01/2024  > le 30/01/2024 
- Pour toutes autres questions > Pour toute autre question

Et, question ouverte, est-ce qu'on les invite vraiment à nous recontacter sur france-transition@beta.gouv.fr ? Parce que je crains un peu la déferlante de questions à ce moment précis (même si seulement 20% de nos contacts en profitent pour reposer une question suite au mail d'AR, on risque de manquer de bande passante et d'outils pour gérer ce flux).

**Comment by jrayneau** [comment]
Concernant le lien de désinscription, je me suis renseigné auprès de SignalConso et Place des entreprises, ils n'ont pas de lien de description sur l'email d'accusé de réception.   => On peut donc partir sur l'email sans lien de desincription

**Comment by yvalentin** [comment]
Après lecture de l'ensemble du ticket, il me semble qu'il manque le sujet de l'email générique d'accusé de réception ? (je suis peut être passer à côté 😄  )

**Comment by yvalentin** [comment]
Lien pour la validation fonctionnelle ;-)

https://tee-preprod-pr653.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
hello @yvalentin 
Je viens de tester mais je ne reçois pas de mail d'AR 🤔

**Comment by yvalentin** [comment]
@ColineLebaratoux Tu peux recommencer ça devrait être bon. (J'ai redeployé pour avoir les variables d'environnement à jour)

**Comment by yvalentin** [comment]
@ColineLebaratoux C'est à nouveau déploy ici : https://tee-preprod-pr653.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
ça fonctionne !
je m'ajoute un ticket sur la mise en page. 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/c224c886-a662-42c7-a798-5874aa0c7f02)
