### ISSUE TITLE
Mettre le bon logo CCI

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/transition-ecologique-entreprises-widget#400]
Le logo CCI présent sur la plateforme n'est plus le bon, suite à une remonter d'un membre du réseau

**Comment by ColineLebaratoux** [comment]
https://fr.wikipedia.org/wiki/Fichier:Logo_de_CCI_France.svg

**Comment by JulienParis** [comment]
preview pour validation : https://tee-frontend-preprod-pr442.osc-fr1.scalingo.io/
