### ISSUE TITLE
Supprimer le SIRET par défaut dans le formulaire de contact

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#410]
- [x] Supprimer le numéro de SIRET pré-rempli dans le champ "SIRET de votre entreprise" : il donne l'impression qu'un (mauvais) SIRET est déjà renseigné. => laisser le champ vide

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/5be5e125-bb99-4ae4-a1bb-cfd09dbe0d56)

**Comment by JulienParis** [comment]
review app : https://tee-frontend-preprod-pr403.osc-fr1.scalingo.io/
