### ISSUE TITLE
Afficher qu'une aide n'est plus disponible

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#430]
**Comment avertir à l'utilisateur qu'une aide n'est plus disponible ?**
(fiche dispositif issues d'une ancienne url partagée)

**2 cas :** 

### A) Une aide prend fin 

- [x] => on ne l'affiche plus dans l'annuaire et dans les résultats sur la plateforme
- [x] => si le lien est partagé, on l'affiche avec un bandeau "cette aide n'est plus disponible" à afficher sur les dispositifs dont la date de fin est passée. 
- [x] => Dans ce cas, je propose de ne pas afficher le formulaire de contact

### B) Une aide qui se renouvelle 

- [ ] => si la nouvelle aide est déjà disponible,  alors redirection automatique d'une aide à une autre (ex : Tremplin 2022 => tremplin 2023)
- [ ] => si la nouvelle aide n'est pas encore disponible, afficher l'aide précédente avec le bandeau "cette aide n'est plus disponible" + date de fin : "potentiellement reconduit à partir du 1/01/2025" @pierrecamilleri 
- [ ] => implique d'ajouter un champ dans les données : reconduit oui / non 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/213eeb98-f211-4c9d-a486-4b656dcac80a)

[cf maquette figma](https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=4413%3A66677&mode=design&t=kcwAKuYtI96Bl0uh-1)

ticket front lié #394
ticket data lié #386

**Comment by JulienParis** [comment]
@pierrecamilleri @ColineLebaratoux j'ai l'impression qu'en ce qui concerne la partie B) "Une aide qui se renouvelle" on n'a pas (ou on n'aura pas) ce problème car les infos seront sans doute changées directement dans le yaml d'origine. En tout cas il ne me semble pas avoir vu de champs dans les données (en tout cas dans le schéma) pour spécifier une redirection vers une aide semblable ou pour indiquer une reconduction

**Comment by ColineLebaratoux** [comment]
Oui parfait cette proposition @JulienParis !

**Comment by ColineLebaratoux** [comment]
Juste un point d'attention sur l'icône + la flèche "retour aux résultats" pas alignés

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/3c17c0b6-4622-4b74-939e-520dc67475b3)

**Comment by JulienParis** [comment]
- Pour la largeur du bandeau j'ai l'impression que c'est déjà le cas

<img width="1305" alt="Capture d’écran 2024-01-18 à 15 14 12" src="https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/43ce6297-3518-475c-941f-404859cc667f">

- J'ai réglé l'alignement de la flèche et du texte, mais pour que ce soit plus propre côté code (et bien signifier qu'on peut cliquer dessus) j'ai repassé ce bouton en mode "bouton" : il se grise au survol

<img width="468" alt="Capture d’écran 2024-01-18 à 15 16 43" src="https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/bace2180-55fe-4928-a291-0cd95fea948a">
<img width="466" alt="Capture d’écran 2024-01-18 à 15 16 50" src="https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/dc4def29-4a36-4ef9-85b4-d23c5f61a370">

**Comment by ColineLebaratoux** [comment]
Hello Juju ! 
Pas tout à fait, regarde : 
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/7bc51944-e08f-456e-a666-221704fc423b)
il faudrait que ce soit en largeur max comme le bandeau "vous souhaitez échanger avec un conseiller ?"


![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/73444025-4f75-4ea7-8b42-7de21fa61ed7)


C'est possible ?

**Comment by JulienParis** [comment]
> C'est possible ?

Bien vu ! Je viens de faire la modif sur la PR #486
