### ISSUE TITLE
Ajustements UI : Revoir les espacements sur la fiche dispositif

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#447]
Pour améliorer la lisibilité de la fiche dispositif, revoir les interlignages pour créer des blocs harmonieux :  
- [x] augmenter l'espacement la description courte et le bloc d'objectifs
- [x] diminuer l'espacement entre les 5 objectifs

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/8fe2638b-dd9e-42cb-909e-0c429707e86d)

- [x] harmoniser les espacements entre les différents blocs de la fiche dispositif (se calquer sur le plus petit espacement)
- [x] harmoniser les espacements au niveau du bloc d'éligibilité (avant après et à l'intérieur)

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/6b40fccc-e6b3-499b-956e-3a7128656aac)

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/e40be2c0-330f-4a0f-8ca2-339da625b2c7)

**Comment by ColineLebaratoux** [comment]
voir également les espacements sur mobile : https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=2694%3A96459&mode=design&t=N3ZwYEXEzqzB3jCE-1

**Comment by JulienParis** [comment]
Modifs apportées, preview sur https://transition-ecologique-entreprises-preprod-pr566.osc-fr1.scalingo.io/

Nota : sur cette preview il y a toujours le bloc "type de programme" (le 4eme bloc) dans la liste des blocs après les objectifs. La suppression de ce bloc redondant est en attente de validation de #553 pour passer en preprod

Je traiterai la question des marges extérieures sur le ticket #274
