### ISSUE TITLE
Le logo CMA est déformé/aplati

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/transition-ecologique-entreprises-widget#450]
Retour de la CAM 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/22809387/74ac6517-ed00-437a-9157-0a91beedb975)

> Mes collègues de la direction communication m’informent que le logo de CMA France apparait déformé 
> Je vous joins une version du logo rectangulaire. Pouvez-vous modifier le logo afin que celui-ci apparaisse net ?

**Comment by ColineLebaratoux** [comment]
On peut diminuer un peu sa taille aussi 


![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/2ed05c6b-3ace-4402-bd7b-f9f83b85206e)

**Comment by JulienParis** [comment]
Modif faite sur PR #525

Preview : https://tee-frontend-preprod-pr525.osc-fr1.scalingo.io
