### ISSUE TITLE
Modif UI : Accordéon pour les conditions d'éligibilité et la description longue

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#456]
- [x] mettre les conditions d'éligibilité dans un accordéon dépliable, comme la description longue (cf ticket #184)
- accordéon dépliable déplié par défaut sur desktop
- accordéon dépliable fermé par défaut sur mobile (le contenu est très long au scroll sur mobile)
breakpoint choisi : tiroir ouvert par défaut à partir de la taille de fenêtre MD (768 px) et + grand (cf [breakpoints DSFR](https://www.systeme-de-design.gouv.fr/elements-d-interface/fondamentaux-techniques/grille-et-points-de-rupture))

---

- [x] Ajustement UI pour les titres des accordéons [cf maquette](https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=2694%3A96459&mode=design&t=nGjLM2378vxlAfwm-1)
cf commentaire de @JulienParis sur le #184 
> Je suis pour le moment resté sur l'accordéon tel qu'il est exactement proposé et décrit par le DSFR (notre Bible à tous, amen), sans les modifs d'UI que tu proposes de ton côté dans Figma

**Comment by ColineLebaratoux** [comment]
maquette mobile : https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=2694%3A96459&mode=design&t=N3ZwYEXEzqzB3jCE-1

**Comment by JulienParis** [comment]
preview on https://transition-ecologique-entreprises-preprod-pr567.osc-fr1.scalingo.io/
