### ISSUE TITLE
A l'envoie du formulaire je n'ai pas de message de validation. Il ne se passe rien à l'écran.

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/transition-ecologique-entreprises-widget#458]
J'ai fait le choix d'objectif en tête > Sans SIRET > 30 salariés > Bretagne > Mobilité > Fond Tourisme Durable
J'ai rempli le formulaire et j'ai cliquer sur envoyer
Il ne se passe plus rien...
J'ai bien la création dans Brevo, mais je n'ai plus de message de validation/fin.

**Comment by yvalentin** [comment]
@jbledevehat C'est corrigé et envoyé en prod ;-)
