### ISSUE TITLE
scroll message d'erreur ou confirmation

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#459]
A la suite [Evolution UI & reformulation du message d'erreur 500#329](https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/329) et de https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/369

- [x] Le scroll est calé sur le haut du message d'erreur. Est-ce possible de le caler au milieu du message ? (même remarque https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/369)

- [x] Le scroll est calé sur le haut du message d'erreur. Est-ce possible de le caler au milieu du message ? (même remarque #329)

position souhaitée : 
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/cb620b63-03bf-441b-bb6a-c51e6448ee2e)

**Comment by JulienParis** [comment]
@ColineLebaratoux preview du fix du 'scroll to center' sur : https://tee-frontend-preprod-pr544.osc-fr1.scalingo.io/aides-entreprise/amo-chaufferie-biomasse

**Comment by ColineLebaratoux** [comment]
testé sur safari, mais ça ne fonctionne pas


![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/a9367505-c40b-4a7c-9137-618d7f18083b)

**Comment by JulienParis** [comment]
Nouvelle tentative - avec l'ajout d'un micro temps de délai (100 millisecondes) avant de ramener le bloc de message au centre de la fenêtre) car l'app n'avait pas le temps de recalculer la bonne hauteur de div entre celle du formulaire et le message de réponse. 

Testé sur Safari et Firefox, sur macOS  : https://tee-frontend-preprod-pr544.osc-fr1.scalingo.io/aides-entreprise/amo-chaufferie-biomasse

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/7b4b3d26-8ef0-4f00-92a5-44e479113f7f)

**Comment by ColineLebaratoux** [comment]
Bien joué, le micro-temps de délai fonctionne bien ! 🙌
