### ISSUE TITLE
Remettre le SIRET obligatoire dans le formulaire de contact

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/transition-ecologique-entreprises-widget#460]
Remettre le SIRET obligatoire dans le formulaire de contact ( ajouter *)

ticket formulaire de contact lié [#470](https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/470)

**Comment by yvalentin** [comment]
Ici ce qui est faite est uniquement de remettre le siret obligatoire sur le formulaire (sans vérification/validation du champs)

Pour les validations voir le ticket #470 ;-)

**Comment by ColineLebaratoux** [comment]
Testable où @yvalentin ?

**Comment by yvalentin** [comment]
@ColineLebaratoux Tu peux tester ici : https://tee-frontend-preprod-pr485.osc-fr1.scalingo.io/
