### ISSUE TITLE
Renommer de dispositifs

### ISSUE THREAD

**Issue by celinebagault** [betagouv/transition-ecologique-entreprises-widget#471]
Renommer les dispositifs 
- [x] etude-photovoltaique >> etude-photovoltaique-cci 
- [x] etude-photovoltaique-2 >> etude-photovoltaique-ademe
- [x] visite-energie >> visite-energie-cci
- [x] visite-energie-2 >> visite-energie-cma
- [x] investissement-solaire-thermique-metropole >> investissement-solaire-thermique

---
- ~~[ ] Réorienter le dispositif : https://mission-transition-ecologique.beta.gouv.fr/aides-entreprise/investissement-solaire-thermique-outre-mer vers https://mission-transition-ecologique.beta.gouv.fr/aides-entreprise/investissement-solaire-thermique qui a fusionné~~

**Comment by ColineLebaratoux** [comment]
- étude photovoltaïque 1 
- étude photovoltaïque 2
- Visite énergie (cci)
- Visite énergie 2 (cma)
