### ISSUE TITLE
Evolution du message d'erreur 500 et personnalisation du contenu du mail france-transition

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#473]
Evolution suite au ticket #329 

- [x] Au clic sur france-transition@beta.gouv.fr depuis le message d'erreur du formulaire de contact, personnaliser le titre et le corps du mail. 

- titre du mail : [france-transition] Demande d'informations concernant le dispositif _nom du dispositif_
- corps du mail (pré rempli et complété par l'utilisateur dans le formulaire de contact)

> Bonjour,

> Mon entreprise a une activité de type "_secteur"_.
> Le dispositif "nom du dispositif" pourrait m'intéresser car j'ai pour projet de ...
> J'ai besoin d'être accompagné(e) sur ...
> Merci d'avance pour votre appel, 

> Prénom + NOM
> numéro de téléphone 
> SIRET : _Numéro Siret_

---
- [x] Reformulation du message d'erreur. Remplacer : "Vous avez la possibilité de nous transmettre votre demande par mail 
à france-transition@beta.gouv.fr en précisant vos coordonnées, votre numéro de SIRET, le nom et le lien de l’aide qui vous intéresse" par "Vous avez la possibilité de nous transmettre votre demande par mail à france-transition@beta.gouv.fr"

**Comment by yvalentin** [comment]
En attente du #329

**Comment by ColineLebaratoux** [comment]
🎉 C'est super !
