### ISSUE TITLE
Ecriture et envoi de mails d'AR pour les dispositifs activables en autonomie

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#482]
Rédiger les mails de confirmation aux utilisateurs ayant postulé à des dispositifs activables en autonomie : 
- Pour fournir l'url de redirection
- Pour donner la marche à suivre pour les dispositifs complexes

- [x] Rédiger les mails => [sur notion](https://www.notion.so/accelerateur-transition-ecologique-ademe/Mails-dispositifs-activables-en-autonomie-5feec63c8e474a91859db36241c0cde7?pvs=4)
- [x] Envoyer les mails @celinebagault 
- [x] Mettre à jour les contenus des fiches dispositifs @ColineLebaratoux 

En complément du ticket #399

**Comment by celinebagault** [comment]
Proposition de mail pour le coup de pouce chauffage :


Bonjour Madame/Monsieur,

Vous avez manifesté votre intérêt pour le Coup de pouce chauffage, qui vous permet de bénéficier d’une prime pour le remplacement de vos anciens équipements par un système de chauffage fonctionnant aux énergies renouvelables et ne consommant ni charbon ni fioul.

**🏢 Pour être éligible au Coup de pouce, votre bâtiment doit :**

    Être dédié à un usage tertiaire (vous devez en être propriétaire ou gestionnaire)
    Être inférieur à 1000 m2
    Être construit depuis au moins deux ans à la date d’engagement des travaux

**🔧 Les travaux concernés par le Coup de pouce**

En priorité, le Coup de pouce chauffage finance le raccordement à un réseau de chaleur alimenté majoritairement par des énergies renouvelables. ﻿Vous pouvez vérifier votre proximité aux réseaux de chaleur [ici](https://france-chaleur-urbaine.beta.gouv.fr/).
À défaut, en cas d’impossibilité technique ou économique du raccordement au réseau le plus proche, le Coup de pouce finance la mise en place d’équipements de chauffage ou de production d’eau chaude sanitaire ne consommant ni charbon ni fiou. Vous trouverez la liste détaillée [ici](https://france-renov.gouv.fr/petit-tertiaire-prive#quels-travaux-sont-concernes-par-le-coup-de-pouce-).

**✅ Voici la marche à suivre pour bénéficier du Coup de pouce chauffage :**

    Rendez-vous chez un fournisseur d’énergie signataire de la charte (dont vous trouverez la liste en pièce jointe) et demandez-lui les offres disponibles. N’hésitez pas à comparer les offres entre plusieurs fournisseurs d’énergie.
    Acceptez l’offre d'un fournisseur (cette offre doit décrire la proposition) puis signez le devis des travaux.
    Faites réaliser les travaux.
    Demandez au professionnel une facture qui mentionne la dépose de l’équipement existant en indiquant l’énergie de chauffage (charbon, fioul ou gaz) et le type d’équipement déposé ou à défaut il est fait mention de la marque et de la référence de la chaudière remplacée.
    Renvoyez les documents (factures, attestations, etc.) au fournisseur d’énergie signataire de la charte dans les délais prévus.

**💰 Les barèmes**

Le montant des primes dépend des offres commerciales de chaque signataire de la charte, c’est pour cela qu’il est important de comparer les offres commerciales avant de vous engager.

Le montant des primes est établi en fonction de la surface du bâtiment, du type d’équipement installé, du type d’équipement qui est remplacé, et du cours du marché des Certificats d'économies d'énergie (CEE).

**❓Des questions ?**

Si vous avez des questions, vous pouvez composer le numéro d’assistance (prix d’un appel) : 0 808 800 700

Nous vous souhaitons une très bonne journée,

L’équipe de Mission Transition Écologique

**Comment by ColineLebaratoux** [comment]
@celinebagault j'ai posé une V2 directement sur notion : https://www.notion.so/accelerateur-transition-ecologique-ademe/Mails-dispositifs-activables-en-autonomie-5feec63c8e474a91859db36241c0cde7?pvs=4

Quel casse tête ! 🤯

**Comment by ColineLebaratoux** [comment]
**Différents types de dispositifs activables en autonomie** 

Et pour chaque dispositifs, se poser la question du process : 
- Comment vont-on mesurer le taux d'activation et le taux de conversion ?
=> afficher le lien sur la fiche dispositif ou dans le mail ? 

- Dispositif avec du contenu accessible / accompagnement en ligne : ex : formation RSE, Baisse les watts, Formations CFDE, enviroveille...
=> est-ce qu'on affiche le lien sur la fiche dispositif ? 
=> tracker uniquement qui clique sur le lien

- Dispositif complexe mais sans relai humain (coup de pouce chauffage, Ademe)
- Dispositif simple sans contact humain (VTE Vert)
- Dispositif avec contact humain (Prêt...)

💡**Brainstorming** 
- afficher un niveau de complexité d'activation de l'aide ?
- Afficher clairement le type de dispositif : accès à une plateforme en ligne / nécessite de déposer un dossier / nécéssite un contact avec l'opérateur /
