### ISSUE TITLE
ajouter les colonnes pour les liens externes sur la fiche dispositif 

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#498]
**Problématique**
1/4 des dispositifs nécessiteraient des liens externes pour compléter la description.
Or aujourd'hui, soit on n'intègre pas ces liens et c'est à l'utilisateur de mener l'enquête, soit on intègre un lien non cliquable dans le corps du texte (bad UX)
Voir [ la page notion ](https://www.notion.so/accelerateur-transition-ecologique-ademe/R-flexion-sur-l-int-gration-des-urls-f336ada1dd964596ad524e85b341079e?pvs=4)

---
**Proposition design dev front**
Ajouter des CTA contextualisés en dessous des étapes en question 

🖥 [maquette écran large ](https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=4621%3A75846&mode=design&t=ChR0GHAsNhgfa2XV-1)
📱 [maquette mobile](https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=2694%3A96459&mode=design&t=ChR0GHAsNhgfa2XV-1)
**Version standard**
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/a78fa8f2-9cf8-4469-842f-0794da7b5a9d)

**Version avec un maximum de liens (rare)**
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/84f06424-4995-47f4-ac25-f5eb85cf69fc)

---
Ce ticket doit être réalisé après le ticket lié data #601 
Ce ticket doit être réalisé avant https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/395 consistant à supprimer le formulaire de contact

**Comment by ColineLebaratoux** [comment]
Vous en pensez quoi @jbledevehat @celinebagault @jrayneau ?

**Comment by ColineLebaratoux** [comment]
**Problématique**
Certains financements complexes nécessitent l'accès à des liens externes pour permettre de vérifier son éligibilité, la liste des projets financés, des partenaires, etc

(Nous ne parlons pas ici du lien pour réaliser la démarche en ligne. Pour les dispositifs activables en autonomie, nous avons fait le choix de ne fournir ce lien qu'après complétion du formulaire pour être en mesure d'effectuer le suivi des demandes).[ (voir le sujet sur les dispositifs activables en autonomie)](https://www.notion.so/accelerateur-transition-ecologique-ademe/Mails-dispositifs-activables-en-autonomie-5feec63c8e474a91859db36241c0cde7?pvs=4)

**Définir comment intégrer des liens externes sur la fiche dispositif ?** 

---
**Par exemple :** 
- "Choisissez votre assistant maître d'ouvrage et obtenez un devis. Les compétences du prestataire doivent respecter un référentiel validé par l’ADEME (RGE Étude ou équivalent)" + [lien vers le référentiel](https://france-renov.gouv.fr/annuaires-professionnels/artisan-rge-architecte)
- "Prenez contact avec des fournisseurs d’énergie signataires de la charte Coup de pouce chauffage" + accès au PDF
- "Vérifiez votre éligibilité en réalisant le test “Votre bâtiment est-il raccordable à un réseau de chaleur ?” [sur ce lien.](https://france-chaleur-urbaine.beta.gouv.fr/ressources/aides#contenu)

---
**Propositions**
- [ ] Ajouter des CTA contextualisés en dessous des étapes en question 
Pour mesurer le taux d'activation, on enregistre les "opportunités" issues de TEE (Siret + nom du dispositif)
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/46c5b8f8-ce21-4951-916f-5cd88829a00a)
[maquette](https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=3028%3A101611&mode=design&t=tU6SajpglTA4OGlC-1)
Inciter l'utilisateur a compléter le formulaire pour avoir toutes les informations par mail



---
- [ ] Créer une nouvelle partie dédiée aux liens externes, comme sur Agir 
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/a8e4da2a-d8e1-41f5-b343-4c7f3f286bc2)

---
- 👎[ ] Ne pas intégrer ces liens dans la fiche dispositif, mais uniquement sur le mail d'accusé de réception. 
Ex : coup de pouce chauffage, pour lequel on présente 8 étapes pour réaliser le process

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/06fcb682-f986-4988-9ca6-b899c8ecfc63)

---

**Comment by jbledevehat** [comment]
@pierrecamilleri @JulienParis @yvalentin 

Est-ce qu'on pourrait pour gagner du temps écrire les étapes/objectifs en markdown pour intégrer des URL en bouton afin d'avoir le visuel décrit ci-dessus ? 

Exemple : 
1. Vérifiez l'éligibilité de votre projet en lisant la documentation de l'ADEME. [Condition éligiblité et finacement](https://agirpourlatransition.ademe.fr/entreprises/sites/default/files/%C3%89tudes%20lutte%20contre%20le%20gaspillage%20alimentaire%20-%20Conditions%20d%27%C3%A9ligibilit%C3%A9%20et%20de%20financement%20-%202024.pdf)

**Comment by pierrecamilleri** [comment]
À mon avis on sera plus confort avec un format de données qui autorise de rattacher des url à des objectifs plutôt que de faire du markup dans les données : 

```
objectifs: 
  - texte: Réalisez un diagnostic blablabla
    liens:
      - ancrage: Conditions d'éligibilité et financement
         href: https://agirpourlatransition.ademe.fr/entreprises/sites/default/files/%C3%89tudes%20lutte%20contre%20le%20gaspillage%20alimentaire%20-%20Conditions%20d%27%C3%A9ligibilit%C3%A9%20et%20de%20financement%20-%202024.pdf
      - ancrage: Autre lien
        href: https//monlien.com
  - texte: Autre objectif
       
```

Après, c'est sûr, ça se renseigne moins bien dans un excel… et peut être que l'avis n'est pas partagé.
