### ISSUE TITLE
Mettre à jour le schéma Process des demande vers les opérateurs

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#505]
Mettre à jour le process surBénéficiez d'un accompagnement par l'équipe Clef Verte pour faire progresser votre démarche et présenter un dossier le plus qualitatif possible au Jury de fin d'année (rapport d'audit, actions engagées et pièces justificatives, synthèse du suivi, etc.): 

- [ ] Ademe
- [ ] dispositifs activables en autonomie

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/b92b41a9-be31-4742-8b1f-c7d987a16972)

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/b2973f53-597a-4875-9f7e-fbb2825e70ef)

**Comment by ColineLebaratoux** [comment]
---
**Notes du brainstorming**

- Formulaire de contact qui renvoi directement aux directions régionales
 
- Contact par COS

-  Identifier les dispositifs Ademe comme des "Dispositifs activables en autonomie" : à la fin du formulaire de contact, afficher un CTA "à vous de jouer" + lien vers Agir

-  Ecrire un mail de confirmation avec la marche à suivre (cf dispositifs activables en autonomie)

Idée à plus long terme :
- Création d’une étape supplémentaire dans le parcours pour commencer le dépôt du dossier Agir

---
Pré-requis pour bien définir ce process :

- [ ]  Tester la création de dossier sur Agir @celinebagault @ColineLebaratoux

- [ ]  faire des stats pour évaluer la part des entreprises mal orientée / non éligible / éligible... https://ademecloud-my.sharepoint.com/:x:/g/personal/jeanbaptiste_ledevehat_ext_ademe_fr/ERd2B-dleTZJvL2qf6jZ-mMBVweoDUh2CsTDGjDPdaJcyw?rtime=-PuaY6YV3Eg

**Comment by jrayneau** [comment]
Voici une proposition de modification. Je l'ai mis dans un Miro à part pour éviter de faire des bêtises  
https://miro.com/app/board/uXjVN2K_dtU=/?share_link_id=577493811012
- J'ai ajouté une colonne "Mesure de conversion"
- C'est une première version à améliorer / discuter avec vous (@jbledevehat, @ColineLebaratoux @celinebagault )
