### ISSUE TITLE
Intégration des nouveaux dispositifs Ademe 

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#539]
Correspond au 8 dispositifs dont "Opérateur = ADEME" & "T=1"

**Comment by pierrecamilleri** [comment]
Déploiement pour tester [ici](https://tee-preprod-pr617.osc-fr1.scalingo.io/)

**Comment by ColineLebaratoux** [comment]
Merci @pierrecamilleri, j'ai tout vérifié. 
2 petites demandes de corrections : 

- Pour [territoire d'industrie](https://tee-preprod-pr617.osc-fr1.scalingo.io/aides-entreprise/fond-vert-territoires-d-insdustrie), j'avais ajouté une URL dans la colonne secteur géographique en lien avec le ticket #570. Finalement, nous avons choisi de présenter cette liste dans le lien de la première étape (cf ticket #601). Peux-tu supprimer ce lien ? 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/838d2c0f-a118-4e1b-8ad9-a7ad423c1bb1)

- J'ai également corrigé 2, 3 coquilles sur ces 8 lignes. Est-ce que tu accepterais de recharger l'ensemble de ces contenus ?

**Comment by pierrecamilleri** [comment]
Oui, bien sûr, bien noté

**Comment by jbledevehat** [comment]
@pierrecamilleri Tu peux donc supprimer les 3 dispositifs Bpifrance : 
- diag-decarbon-action-2
- diag-eco-flux-2
- diag-ecoconception-2

**Comment by pierrecamilleri** [comment]
- J'ai supprimé les 3 dispositifs. 
- J'ai mis à jour les dispositifs, j'espère que je n'ai rien oublié car les lignes étaient dupliqués dans Data et Data Prod.

Pour "Territoires d'industrie", j'ai mis "Projets situés dans le périmètre géographique d’un des Territoires d’industrie 2023-2027" en condition d'éligibilité géographique spécifique. 

Par contre, pas accès en écriture au tableau, donc fait en local...
