### ISSUE TITLE
Créer une page Stats

### ISSUE THREAD

**Issue by jrayneau** [betagouv/transition-ecologique-entreprises-widget#540]
Créer une  page stats.
URL : https://mission-transition-ecologique.beta.gouv.fr/stats

Prérequis [#549](https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/549)

Données à afficher :
- [ ] Back API
      - **Un chiffre : Nombre de dispositif activé depuis le lancement** (écrire "à mesurer")
      - Un chiffre : Nombre d'aide proposée depuis le lancement >> 93
      - Un chiffre : Nombre de demandes d'entreprise depuis le lancement >> 912
      - Un graphique temporel : Nombre de demandes reçues et cumulées mois par mois >>
      - Un tableau : Top 20 des dispositifs depuis le lancement (nom et nombres de demandes) >>

- [ ] Front : Définir la techno (strapi ou autres) et créer un premier visuel de page avec celle-ci

--- 

Vision cible 

Impact : 
- Un chiffre : Nombre d'aide proposée depuis le lancement
- **Un chiffre : Nombre de dispositif activé depuis le lancement**
- Un graphique : 
      - Nb de demandes effectuées par trimestre 
      - Comparé au nb de dipositifs ou l'aide a été proposée par l'opérateur par trimestre  
      - Comparé au nb de dispositifs activés par trimestre  + Taux de conversion 
- Un petit texte sur la mesure de l'impact écologique avec notre ambition à terme  

Autres stats :
- Répartition des demandes effectuées par opérateur (période ? sur le dernier trimestre ?) 
- Répartition  des demandes effectuées par thème (période ? sur le dernier trimestre ?)
- Top 10 des dispositifs (période ? sur le dernier trimestre ?)

Doc beta.gouv sur la mesure d'impact :
https://doc.incubateur.net/communaute/gerer-sa-startup-detat-ou-de-territoires-au-quotidien/je-gere-mon-produit-et-son-impact/definir-et-mesurer-limpact

**Comment by ttdm** [comment]
Voila une première version toute simple : 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/15088539/5e146cc1-a56e-4d30-aaed-8c622bc0de45)

L'idée c'est que cette page valide les deux items proposés par julien (hormis le top 10 ou 20 des dispositifs) et qu'elle permet d'avoir une base pour parler design / contenu.

**Comment by ColineLebaratoux** [comment]
Hello @ttdm ! 
Je te propose ces ajustements UI : 
https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=5503%3A114472&mode=design&t=GZCJFcSI0Zm1oDZO-1

J'ai également fait quelques évolutions édito.
@JulienParis @jbledevehat qu'en pensez-vous ? 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/8b578438-414c-4d29-bcbe-426f07d870eb)

**Comment by jbledevehat** [comment]
Trop bien 👍

**Comment by jbledevehat** [comment]
Je me permet d'ajouter le lien pour le retrouver https://tee-preprod-pr588.osc-fr1.scalingo.io/stats
