### ISSUE TITLE
Personnaliser le message sur la page de résultats

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#548]
❌ **Certains utilisateurs doutent encore de leur éligibilité pour les résultats proposés**
- l'aider à comprendre que le dispositif est présenté parce qu'il est éligible 
- l'aider à comprendre que les variables affichées sont contextualisées en fonction de son siret et réposnes au questionnaire 
_> *"c’est pas clair du tout ça sur le site. On entre le siret au départ mais sur ici, je ne suis plus sûre d’être concerné par toutes ces offres."“Ah si ça pourrait être pour moi ? Alors, il faut rassurer sur le fait que la liste des aides sont bien applicables à notre activité, et à nos petites structures, sinon elles vont dire “c’est pas pour moi”.*
> *Il doit y avoir un sacré algorithme derrière ! Mais il faut que les critères d’éligibilité soient affichées. parce que qu’on ne sait pas vraiment ce qui est pris en compte”*_
---
### **Proposition** 

- [ ] ajouter la taille + le secteur d'activité (issu du Siret ou du formulaire) + région sur le message d'introduction aux résultats 

_

> Voici les aides éligibles à votre [taille de l'entreprise]* du secteur ["secteur d'activité"] et correspondantes à vos enjeux prioritaires.
"Voici les accompagnements dont vous pouvez bénéficier pour diminuer l’empreinte écologique de votre [taille de l'entreprise]* du secteur ["secteur d'activité"] en région [nom de la région] 
_

*taille : Entreprise individuelle / TPE / PME / ETI ou GE

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/ecce225e-c0db-4560-94e9-196d0a7f5654)

solution liée : #565

**Comment by ColineLebaratoux** [comment]
C'est un minor fix ou pas si simple à réaliser @JulienParis ?

**Comment by JulienParis** [comment]
@ColineLebaratoux C'est pas exactement un minor fix, mais c'est pas de la *rocket science* non plus. Je garde ce ticket dans ma todo list pour ce sprint

**Comment by JulienParis** [comment]
@ColineLebaratoux première version de cette feature => https://tee-preprod-pr628.osc-fr1.scalingo.io/

Exemple de résultat => 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/8830b0d2-ddb5-440b-869b-bc3165d80202)

**Comment by ColineLebaratoux** [comment]
Super @JulienParis !
Quelques retours concernant la taille de l'entreprise : 
- J'ai testé un cas d'EI (SIRET 49898713000032) qui apparait en TPE parce que notre question effectif ne permet pas de le distinguer. On a évoqué cette évolution ici : [#578](https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/578). Tu penses que tu peux traiter ce ticket simultanément pour pouvoir afficher "Entreprise individuelle" (pas EI)
- Pour ce qui est de l'acronyme GE, je crois qu'il n'est pas très connu non plus. Dans le cas d'une réponse +de250 collaborateurs à la question effectif, peux-tu plutôt écrire "ETI ou Grande Entreprise"

**Comment by JulienParis** [comment]
Issue en stand-by, cf https://github.com/betagouv/transition-ecologique-entreprises-widget/pull/628#discussion_r1519411631

**Comment by JulienParis** [comment]
@ColineLebaratoux sur la question des EI quelques éléments de réflexion + ping @pierrecamilleri @ttdm pour les questions de filtrage : 

- Quand on fait une requête SIRET à partir du front depuis la piste de question `trackStructureSiret`, en fait on va taper dans notre propre backend sur le point d'API `GetEstablishmentBySiret`, qui lui-même va requêter l'API SIRENE  et qui fait le "passe-plat" : https://tee-preprod-pr588.osc-fr1.scalingo.io/api/docs/#/default/GetEstablishmentBySiret 

- Notre point d'API ne renvoie pas d'infos concernant la taille de l'entreprise : c'était un choix de notre part, car nous avions jugé les infos SIRENE pas assez fiables ou assez bien mises à jour. Si on cherche ton SIRET de test avec notre point d'API on a donc en réponse un objet qui ne contient pas l'info sur la taille de l'entreprise : 

```json
{
  "siren": "498987130",
  "nic": "00032",
  "siret": "49898713000032",
  "creationDate": "2007-07-11",
  "denomination": null,
  "nafCode": "86.90E",
  "address": {
    "streetNumber": "136",
    "streetType": "RUE",
    "streetLabel": "DE L'AIGUILLETTE",
    "zipCode": "13012",
    "cityLabel": "MARSEILLE 12",
    "cityCode": "13212"
  },
  "region": "Provence-Alpes-Côte d'Azur",
  "nafLabel": "Activité profess. rééducation appareillage & pédicures-podologues",
  "nafSectionCode": "Q"
}
``` 

- Bref pour le moment on "oblige" les utilisateurs à passer par la question sur la taille de l'entreprise, laquelle d'ailleurs n'a pas de catégorie EI mais uniquement TPE / PME / ETI / GE.

PS : il faudrait aussi voir s'il y a un intérêt en termes de filtrage des dispositifs (si certains dispositifs s'adressent uniquement à des EI)

---

Pour tenter de répondre à ta question sur les EI il y aurait plusieurs pistes : 

- Soit on ajoute la catégorie 'EI' à la piste de question sur la taille de l'entreprise
  - `+` : très léger à changer côté code
  - `-` : on continue à poser cette question après la piste SIRET 

- Soit on change le comportement de notre point d'API pour récupérer et renvoyer la taille de l'entreprise au front, et donc pouvoir zapper la piste de question d'après sur la 
  - `+` : plus agréable côté utilisateurices
  - `-` : données sur l'entreprise moins fiables / un plus lourd à intégrer car changements back et front

- Soit enfin on ne change rien au comportement actuel car aucun effet en termes de filtrage...

What do you think ?

**Comment by JulienParis** [comment]
> Pour ce qui est de l'acronyme GE, je crois qu'il n'est pas très connu non plus. Dans le cas d'une réponse +de250 collaborateurs à la question effectif, peux-tu plutôt écrire "ETI ou Grande Entreprise"

OK, c'est modifié => 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/b2bc41b0-1572-408b-865b-fc85cbfdb89a)

**Comment by ColineLebaratoux** [comment]
> > J'ai testé un cas d'EI (SIRET 49898713000032) qui apparait en TPE parce que notre question effectif ne permet pas de le distinguer. On a évoqué cette évolution ici : [#578](https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/578). Tu penses que tu peux traiter ce ticket simultanément pour pouvoir afficher "Entreprise individuelle" (pas EI)
> 
> [@ColineLebaratoux](https://github.com/ColineLebaratoux) sur la question des EI quelques éléments de réflexion + ping [@pierrecamilleri](https://github.com/pierrecamilleri) [@ttdm](https://github.com/ttdm) pour les questions de filtrage des données yaml :
> 
> * Quand on fait une requête SIRET à partir du front depuis la piste de question `trackStructureSiret`, en fait on va taper dans notre propre backend sur le point d'API `GetEstablishmentBySiret`, qui lui-même va requêter l'API SIRENE  et qui fait le "passe-plat" : https://tee-preprod-pr588.osc-fr1.scalingo.io/api/docs/#/default/GetEstablishmentBySiret
> * Notre point d'API ne renvoie pas d'infos concernant la taille de l'entreprise : c'était un choix de notre part, car nous avions jugé les infos SIRENE pas assez fiables ou assez bien mises à jour, et donc on demande directement à l'utilisateurice. Si on cherche ton SIRET de test avec notre point d'API on a donc en réponse un objet qui ne contient pas l'info sur la taille de l'entreprise :
> 
> {
>   "siren": "498987130",
>   "nic": "00032",
>   "siret": "49898713000032",
>   "creationDate": "2007-07-11",
>   "denomination": null,
>   "nafCode": "86.90E",
>   "address": {
>     "streetNumber": "136",
>     "streetType": "RUE",
>     "streetLabel": "DE L'AIGUILLETTE",
>     "zipCode": "13012",
>     "cityLabel": "MARSEILLE 12",
>     "cityCode": "13212"
>   },
>   "region": "Provence-Alpes-Côte d'Azur",
>   "nafLabel": "Activité profess. rééducation appareillage & pédicures-podologues",
>   "nafSectionCode": "Q"
> }
> * Bref pour le moment on "oblige" les utilisateurices à passer par la question sur la taille de l'entreprise (la piste `trackStructureWorkforce`, [voir ici](https://github.com/betagouv/transition-ecologique-entreprises-widget/blob/2d3fab3cd9ffbdd265bb1363cebffcb739e69724/packages/web/src/questionnaire/trackStructureWorkforce.ts#L95C1-L95C13) ), laquelle d'ailleurs n'a pas de catégorie EI mais uniquement :
>   
>   * TPE (<20)
>   * PME 1 (21-49)
>   * PME 2 (50-250)
>   * ETI / GE (>250).
> 
> PS : il faudrait aussi voir s'il y a un intérêt en termes de filtrage des dispositifs (si certains dispositifs s'adressent uniquement à des EI). De mon côté il ne me semble pas avoir vu de dispositif fléché uniquement sur les EI, mais je peux me tromper.
> 
> Pour tenter de répondre à ta question sur les EI il y aurait plusieurs pistes :
> 
> * A) Soit on ajoute la catégorie 'EI' à la piste de question sur la taille de l'entreprise
>   
>   * `+` : très léger à changer côté code, peut-être plus explicite côté utilisateurice
>   * `-` : on continue à poser cette question après la piste SIRET, sachant que côté filtrage ça n'aura aucun effet supplémentaire
> * B) Soit on change le comportement de notre point d'API pour récupérer et renvoyer la taille de l'entreprise au front, et donc pouvoir zapper la piste de question d'après sur la
>   
>   * `+` : plus agréable côté utilisateurices
>   * `-` : données sur l'entreprise moins fiables / un plus lourd à intégrer car changements back et front
> * C) Soit enfin on ne change rien au comportement actuel car aucun effet en termes de filtrage...
>   
>   * `+` : cette issue est close ainsi que [Ne pas poser la question de l'effectif pour les entreprises individuelles #578](https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/578)
>   * `-` : Coline est pas forcément convaincue
> 
> Perso j'aurais plutôt tendance à voter A) mais vous ?
> 
> What do you think ?

Merci @JulienParis pour cet éclairage ! Idem, je pense que la solution A) est utile et suffisante. 
ça permet d'afficher la bonne info à l'utilisateur et de le rassurer sur le fait qu'il a sa place sur la plateforme. 
cf verbatim d'un testeur EI "Dans le choix de l’effectif “moins de 20 ? C’est un peut grosse maille comme simulation. Il n’y a pas de différence pour nous quand on est seul? ”

ça pourrait donner ça :
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/fe2ddf93-5bb8-4fd2-a207-769152e00857)

**Comment by ColineLebaratoux** [comment]
Merci @JulienParis pour cet éclairage ! Idem, je pense que la solution A) est utile et suffisante.
ça permet d'afficher la bonne info à l'utilisateur et de le rassurer sur le fait qu'il a sa place sur la plateforme.
cf verbatim d'un testeur EI "Dans le choix de l’effectif “moins de 20 ? C’est un peut grosse maille comme simulation. Il n’y a pas de différence pour nous quand on est seul? ”

ça pourrait donner ça :


![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/aa642b5d-4a49-43eb-b474-7743509392d7)

tu en penses quoi @jbledevehat ?

**Comment by JulienParis** [comment]
Option "entrepreneur individuel" ajouté sur la branche

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/e90388d6-70ce-4464-9192-6e5918f7dbc8)

**Comment by jbledevehat** [comment]
Que reste-t-il pour envoyer en prod ?

**Comment by jbledevehat** [comment]
@JulienParis @yvalentin Est-ce qu'on peut tester maintenant ?

**Comment by yvalentin** [comment]
@jbledevehat @ColineLebaratoux 
ici: https://tee-preprod-pr696.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
- [ ] Peux-tu enlever l'italique sur les textes personnalisés ? 
- [ ] Peux-tu remplacer les termes actuels par "TPE" "PME" " "ETI ou Grande Entreprise"


![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/3e0f25e6-e8e7-4b97-95df-bb2583da9703)
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/2b096f5c-0418-44c0-9ca7-f1ea42de069f)
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/cd7bec45-09f7-40b2-abb8-e736953d8983)

**Comment by yvalentin** [comment]
@ColineLebaratoux @jbledevehat 
Petite precision:

Est-ce que pour vous le texte que la page de résultat est ok ?

Exemple avec "👩‍🔧 J’ai une activité industrielle, fabrication, production"
Et le texte de la page resulat "Voici les accompagnements dont vous pouvez bénéficier pour diminuer l’empreinte écologique de votre PME du secteur industrie en région Auvergne-Rhône-Alpes."



![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/1521862/a7ebef2f-05b7-4a43-9282-d481cbda3319)





![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/1521862/a0b06ec3-f333-4b39-824f-7353c72427d3)

**Comment by ColineLebaratoux** [comment]
Hello ! Pour moi c'est ok. Je manque de billes sur le sujet, je n'ai jamais eu de retours utilisateurs sur le sujet. 
Laissons ça comme ça, et j'imagine que ce sera faisable s'il faut le faire évoluer plus tard.
