### ISSUE TITLE
Mettre à jour la liste des opportunités Brevo pour rattraper l'historique (contacts seuls)

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/transition-ecologique-entreprises-widget#549]
Suite à la modification de gestion des opportunités dans Brevo, il nous faut récupérer l'existant afin d'avoir une liste d'opportunité à jour. 

Cela signifie créer une opportunité par contact pour tous les contacts créés avant la première opportunité créée dans Brevo.

**Comment by pierrecamilleri** [comment]
J'ai réalisé le script, et j'ai fait tourner sur la pipeline d'opportunités de test. J'insère dans la colonne "Nouvelle" car il n'y a pas de colonne "transmis" sur cette pipeline, mais lorsque le script sera lancé "pour de bon", il sera inséré dans la colonne "Transmis".

Les données sont importées depuis "contact", et les changements d'id et les suppressions de programmes ont été pris en compte. Il en résulte 708 opportunités historiques. 

# Où les trouver

Dans Brevo, sélectionner la fenêtre "Opportunités", à côté du titre sélectionner "Modifier" et sélectionner "Test".

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/22995923/9cefd58f-8a31-4927-8881-000a36344ebe)

# Pour la suite

Je laisse à Thibaut @ttdm dans la PR les instructions pour faire tourner le script "pour de vrai" après validation.

**Comment by jbledevehat** [comment]
J'ai pu tout exporter et j'ai croisé pas mal d'info... Pour moi c'est bon. Bravo @pierrecamilleri pour ce boulot :-) et surtout merci. @ttdm tu peux envoyer ça en prod.
