### ISSUE TITLE
Pouvoir envoyer des mails depuis Brevo

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/transition-ecologique-entreprises-widget#557]
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/22809387/9efbba9f-b613-4742-add4-5971bc746499)

**Comment by jrayneau** [comment]
Message à Lillian :
Hello @lsagetlethias ,
Pour mieux gérer notre relation avec les utilisateurs, nous avons besoin d'une boite email génrérique.
En l'intégrant à notre CRM Brevo,  cela permettait à notre chargée client d'envoyer et de recevoir directement des emails depuis Brevo.
L'idée serait de créer une boite mail générique comme contact@mission-transition-ecologique.beta.gouv.fr
Est-ce qu'il serait possible de le faire en utilisant le compte OVH géré par l'incubateur ?
A disposition pour échanger avec toi sur le sujet si notre besoin mérite plus d'éclaircissement.

**Comment by jrayneau** [comment]
infos beta  sur les boites emails :
https://doc.incubateur.net/communaute/travailler-a-beta-gouv/jutilise-les-outils-de-la-communaute/outils/liste-de-diffusion-et-adresses-de-contact
