### ISSUE TITLE
Problème Tracking Matomo

### ISSUE THREAD

**Issue by jrayneau** [betagouv/transition-ecologique-entreprises-widget#561]
Le tracking Matomo (visites) ne fonctionne plus depuis jeudi 1er février
.

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/8970478/bc486af3-62dd-4480-90a7-2e5b144bf81e)

**Comment by yvalentin** [comment]
Certainement besoin de remplacer la partie de code de Matomo par un lib vue Matomo
https://github.com/AmazingDreams/vue-matomo
