### ISSUE TITLE
Mettre à jour le schéma de donnée

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/transition-ecologique-entreprises-widget#572]
Afin de mobiliser les partenaires ayant des dispositifs dans leurs système d'information, il faut un schéma de donnée clair et parlant pour eux.

Mettre à jour celui-ci avec les conditions d'écriture (travail design/data à synchroniser).

Lien du schéma : https://github.com/betagouv/transition-ecologique-entreprises-widget/blob/preprod/packages/data/schemas/program-data-schema.json

**Comment by jbledevehat** [comment]
@pierrecamilleri en 1h à 2 on peut faire le taff je pense en repassant rapidement sur la page à 4 mains.

**Comment by jbledevehat** [comment]
En comparaison avec https://schema.data.gouv.fr/etalab/schema-dispositif-aide/0.0.2/documentation.html#propriete-beneficiaires-aide 
Je pense qu'il faut apporter quelques modifications comme dans le schéma : 
- ajouter "programme_aides"
- ajouter "recurrence"
- ajouter "date_mise_a_jour"

Dans la cible j'aurai bien repris le "beneficiaires" afin de pouvoir être exhaustif pour les autres cibles (que nous n'avons pas, communes, régions...). Qu'en dis-tu ?

Penses-tu qu'un "id" et un "slug" soit nécessaire ?

**Comment by jbledevehat** [comment]
@pierrecamilleri Est-ce que @ttdm pourrais avancer sur ce ticket par hasard ?

**Comment by pierrecamilleri** [comment]
L'essentiel est déjà fait, donc pour cette fois-ci ce ne sera pas la peine, mais oui, c'est Thibaut qui s'occupera de faire évoluer ce schéma initial. 

J'ai ajouté : 

- "programmes" (array, optionnel)
- "types bénéficiaires" (array, obligatoire)
- "date mise à jour" (string, optionnel)
- "identifiant interne" (string, optionnel). À partir du moment où la production de données est décentralisée sur plusieurs acteurs, on ne peut pas garantir l'unicité de l'identifiant, d'où le "interne". 

J'ai pas mis "récurrence" qui à mon avis complexifie inutilement un schéma de données déjà assez costaud, et qui peut déjà être précisé dans les multiples champs descriptifs. Mais si t'insiste je le rajoute.

**Comment by jbledevehat** [comment]
Oui tu as raison, alors let's go pour l'envoyer en prod :-) Merci à toi
