### ISSUE TITLE
Corrections UI responsive (suite)

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#585]
Dans la suite du[ ticket ](https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/274)
---
- [x] Revoir les tailles et les espacements entre les logos dans le footer cf image ci-après : 
- [x] supprimer l'encadré gris autour de chaque logo 
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/3c29c612-cf84-414f-8716-fd3c56ccb6e9)

---
- [x] harmoniser les hauteurs de tous les blocs thématiques sur le questionnaire "je ne sais pas par ou commencer" (se fixer sur celle de la mobilité)
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/f7f331d9-5910-4e61-a2b3-3649f5dbcace)

---
- [x] sur la HP, revoir l'espacement entre les numéros et le texte et augmenter la largeur du bloc  (diminuer les marges gauche et droite)
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/1fa251e5-b215-47fe-8a9c-56d28e83326b)

---
- [x] sur la fiche dispositif, diminuer l'espacement entre les objectifs et les encarts de détails (coût, prestation, contact, date de fin)
- [x] sur la fiche dispositif, augmenter un peu la taille des 4 pictos (coût, prestation, contact, date de fin)
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/3a7ccedf-f211-4b17-9f57-87eacaa7a0cf)

---
- [x] Revoir les marges gauche et droites sur la fiche dispositif pour les encarts "les étapes de votre demande d'aide" "suis-je éligible" "en savoir plus" 
cf capture d'ecran : le texte est collé au bord de l'écran
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/3d64ffa6-b272-4069-a2d3-58de1bed3d23)

**Comment by ColineLebaratoux** [comment]
@JulienParis tu peux me partager le lien pour tester ?

**Comment by JulienParis** [comment]
@ColineLebaratoux pardon pour l'oubli, le lien de _preview_ est celui-ci : https://tee-preprod-pr590.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
Tout parfait ! 
Sauf ce point qui ne semble pas avoir changé :
- [ ]  sur la fiche dispositif, augmenter un peu la taille des 4 pictos (coût, prestation, contact, date de fin)

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/d72552a9-d225-4841-bedc-067304f52e72)

**Comment by JulienParis** [comment]
@ColineLebaratoux effectivement je ne voyais pas ce problème sur mon navigateur de prédilection (Firefox), d'autant que j'ai des réglages de taille de typo différents sur Firefox. En testant sur Safari j'ai vu ce dont tu parlais.

Après modifs voilà le résultat que j'arrive à obtenir et sur Firefox (à gauche) et sur Safari (à droite) => https://tee-preprod-pr590.osc-fr1.scalingo.io/aides-entreprise/amo-chaufferie-biomasse 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/189dd649-2ed7-4803-891f-643daf131d7c)

**Comment by ColineLebaratoux** [comment]
Super !

**Comment by JulienParis** [comment]
> Super sur Chrome ou firefox En revanche, les blocs se mettent côte à côte sur Safari

Comme tu le vois sur mon dernier screenshot je n'ai pas ce comportement sur Safari. Les blocs ont bien la classe DSFR `fr-col fr-col-sm-12 fr-col-md-4` qui indique qu'en largeur `sm` ils sont censés faire 12 colonnes, et qu'en taille `md` faire 4 colonnes de large.

Tu as tenté en rafraichissant la page ?
