### ISSUE TITLE
Affichage du 4ème bloc à mettre sur une même ligne

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/transition-ecologique-entreprises-widget#594]
A corriger pour avoir les blocs sur la même ligne

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/22809387/a05340d6-f773-4064-866a-a48d654d742d)

**Comment by JulienParis** [comment]
Solution proposée (1 bloc = 3 colonnes sur 12), sachant qu'on a parfois 3 blocs, parfois 4, et que quel que soit le cas en responsive chaque bloc fait 12 colonnes

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/f003ebec-9c4b-4812-b472-4d68c2a86d27)

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/79e84b62-65b8-4f61-bf4c-ebf654ce770f)

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/6dc9136d-97d4-4ba1-89d9-6e2202ab3e75)

**Comment by ColineLebaratoux** [comment]
Hello @JulienParis ! Est-ce qu'on pourrait plutôt opter pour la solution qui permet d'occuper à chaque fois la pleine largeur de l'écran : 
- Si 3 blocs, 3 colonnes par bloc 
- Si 4 blocs, 2 colonnes par bloc

Je trouve cet affichage plus propre. Est-ce que c'est faisable ?
[cf maquette](https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=4621%3A75592&mode=design&t=ZBmu2UjkGx0FSnwj-1)

**Comment by JulienParis** [comment]
> Hello [@JulienParis](https://github.com/JulienParis) ! Est-ce qu'on pourrait plutôt opter pour la solution qui permet d'occuper à chaque fois la pleine largeur de l'écran :
> 
>     * Si 3 blocs, 3 colonnes par bloc
> 
>     * Si 4 blocs, 2 colonnes par bloc
> 
> 
> Je trouve cet affichage plus propre. Est-ce que c'est faisable ? [cf maquette](https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=4621%3A75592&mode=design&t=ZBmu2UjkGx0FSnwj-1)

ok je vais faire ça

**Comment by JulienParis** [comment]
@ColineLebaratoux rebelote pour validation : https://tee-preprod-pr595.osc-fr1.scalingo.io/

Pleine largeur quel que soit le nombre de blocs d'infos (je retraduis) :

- Si 4 blocs d'info =>  3 cols (sur 12) par bloc
- Si 3 blocs d'info =>  4 cols (sur 12) par bloc

---

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/bcce18fc-d6c7-45a8-9234-89484af31fb5)

---

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/8fb81d27-fea1-49bd-94df-39a29ac7776a)

**Comment by ColineLebaratoux** [comment]
Parfait @JulienParis, tu gères !
