### ISSUE TITLE
Intégration des nouvelles colonnes avec les 🔗 liens URL pour chaque étape

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#601]
- [ ] Intégration des nouvelles colonnes : 
- 3x3 colonnes à côté de chaque objectif : (x3 car possibilité d'intégrer 2 liens côte à côte)
1) url 
2) nom de l'url 
3) colonne téléchargement : 1 oui - 0 non 
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/791e4bf8-2b0b-4135-bb73-ccfa1d029a7b)

---

- [ ] Vérification des urls pour éviter les liens pétés = 
- déclencher une commande manuelle pour vérifier les liens sortants 
- si code 200 = site out
- warning (mais pas bloquant)

ticket design lié [#498](https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/498)

---

**Problématique**
1/4 des dispositifs nécessiteraient des liens externes pour compléter la description.
Or aujourd'hui, soit on n'intègre pas ces liens et c'est à l'utilisateur de mener l'enquête, soit on intègre un lien non cliquable dans le corps du texte (bad UX)
Voir [ la page notion ](https://www.notion.so/accelerateur-transition-ecologique-ademe/R-flexion-sur-l-int-gration-des-urls-f336ada1dd964596ad524e85b341079e?pvs=4)

---
**Proposition design dev front**
Ajouter des CTA contextualisés en dessous des étapes en question 

🖥 [maquette écran large ](https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=4621%3A75846&mode=design&t=ChR0GHAsNhgfa2XV-1)
📱 [maquette mobile](https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=2694%3A96459&mode=design&t=ChR0GHAsNhgfa2XV-1)
**Version standard**
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/a78fa8f2-9cf8-4469-842f-0794da7b5a9d)

**Version avec un maximum de liens (rare)**
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/84f06424-4995-47f4-ac25-f5eb85cf69fc)

---
Ce ticket doit être réalisé après le ticket lié data #601 
Ce ticket doit être réalisé avant https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/395 consistant à supprimer le formulaire de contact

**Comment by ttdm** [comment]
Voici la liste des liens problématiques pour cet ajout initial de liens : 

🖊️ baisse-les-watts.yaml   / lien 1.1 :  Le lien redirige actuellement vers la page d'accueil de baisse-les-watts. 
🖊️ formations-du-cfde.yaml   / lien 1.1 :  code 403 "interdit" mais il me semble que c'est OK ? 
🖊️ formations-tee.yaml / lien 1.1 : code 403 "interdit" mais il me semble que c'est OK ? 

Il faut aussi voir comment on fait pour les fichiers que l'on doit héberger nous même.
C'est quelque chose qui doit rester très ponctuel et qui sera manuel pour les devs ? 
Est ce qu'une "dropbox beta-gouv" utilisable par tous les membres du projet serait acceptable ? (j'imagine que l'addresse serait alors plus générique comme fichiers.gouv.fr)

**Comment by ColineLebaratoux** [comment]
hello @ttdm 

🖊️ baisse-les-watts.yaml / lien 1.1 : Le lien redirige actuellement vers la page d'accueil de baisse-les-watts. => C'est ok, il s'agit d'un lien tracké https://www.baisseleswatts.fr/?mtm_campaign=missiontransitionecologique&mtm_source=missiontransitionecologique&mtm_medium=missiontransitionecologique&mtm_content=missiontransitionecologique
🖊️ formations-du-cfde.yaml / lien 1.1 : code 403 "interdit" mais il me semble que c'est OK ? > ce lien fonctionne non ? https://www.cci.fr/ressources/developpement-durable/cfde/nos-formations 

🖊️ formations-tee.yaml / lien 1.1 : code 403 "interdit" mais il me semble que c'est OK ? = ce lien fonctionne aussi chez moi : https://universite.bpifrance.fr/Account/login

**Comment by ColineLebaratoux** [comment]
@ttdm c'est bon j'ai supprimé et remplacé par des liens les 4 fichiers que j'avais temporairement hebergé sur notion

**Comment by ttdm** [comment]
@ColineLebaratoux : Par rapport aux logos des liens, je pensais que c'était lié au format : pdf/docx.. = téléchargement avec logo et positionnement logo différent des pages web classiques. 

Je viens d'aller voir dans l'excel et il n'y a plus un seul élément où la colonne téléchargement vaut 1. 

Si je comprend bien, tu avais imaginé la colonne plutôt par rapport aux fichiers que l'on devait potentiellement héberger nous même ? 
Du coup on supprime les 6 colonnes téléchargements du fichier excel et le traitement qui va avec ? 
Et je fais quand même le petit jeu sur les icones ou pas ? 
![image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/15088539/8de6ee9f-903c-4a88-a150-e2788b817757)
![image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/15088539/f0eba9cd-f492-4f05-a378-0c74f4b67847)

**Comment by ColineLebaratoux** [comment]
Hello @ttdm ! 
Oui tu as raison, maintenant que tous les liens sont des liens externes, on peut supprimer la colonne dédiée et utiliser un unique picto. 
Tant mieux, ça simplifie les choses !

Quelques retours :
- J'ai l'impression que la taille de typo est similaire entre le texte et celui du CTA. (sur la maquette, par exemple, j'ai mis 16 pour le texte des étapes, et 14 pour le CTA)
- Peux-tu changer la couleur des CTA pour du violet #6A62F4 ? (pas celui du DSFR dont le contraste n'est malheureusement pas accessible sur du blanc)
- Sur la version mobile, peux-tu corriger les espacements et alignements des textes, au plus proche de cette maquette :


![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/f2e4ee75-d0be-4f85-b44e-942e1834cc6b)

Merci !

**Comment by ttdm** [comment]
https://tee-preprod-pr689.osc-fr1.scalingo.io/aides-entreprise/bonus-ecologique

C'est bon pour toi @ColineLebaratoux ?

**Comment by ColineLebaratoux** [comment]
C'est top @ttdm ! 
Il y a juste une petite correction d'alignements au niveau des étapes (cf maquette ci dessus)

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/fc5412a4-29f6-4b74-a81d-ace01c83f676)

**Comment by ttdm** [comment]
C'était l'alignement qu'on avait en prod en ce moment ;) 

Je viens de faire une modif rapide. C'est mieux mais c'est pas au pixel. La différence est à mon avis invisible. Il y a un peu plus de travail si on veut vraiment être au pixel (l'ancien code n'utilise pas le système de marge du dsfr mais des marges manuelles qu'il faudrait convertir pour être au pixel).

**Comment by ColineLebaratoux** [comment]
Super, merci beaucoup !
