### ISSUE TITLE
Routes de la piste de questions

### ISSUE THREAD

**Issue by yvalentin** [betagouv/transition-ecologique-entreprises-widget#610]
Voici l'ensemble des routes (et des entrées de la piste de questions.

On peux en profiter pour faire un peu de nettoyage (si besoin)

En lien la page sur notion au sujet de la piste de questions (à voir si c'est à jour) et peut être à ajouter sur le repo git, si non déjà present)
https://www.notion.so/accelerateur-transition-ecologique-ademe/Sch-matisation-des-tracks-f150828cd4c74e6f8bff3f924adfb045

```ts
  BuildingProperty = 'track_structure_building_property', // propriétaire ou locataire ? 
  ContactForm = 'track_form',  
  EnergyReductionPriority = 'track_energy_reduction_priority', 
  Goals = 'track_goals',
  QuestionnaireRoute = 'track_questionnaire_route', // Quel parcours ? 
  MobilityWishes = 'track_mobility_wishes',
  Results = 'track_results',
  Sectors = 'track_sectors',
  Siret = 'track_siret',
  StrategyAudits = 'track_strategy_audits',
  StrategyAuditsSelect = 'track_strategy_audits_select',
  StructureRegion = 'track_structure_region',
  StructureWorkforce = 'track_structure_workforce', // Effectif
  WastesMaterials = 'track_wastes_materials',
  WastesSorting = 'track_wastes_sorting',
  WastesStake = 'track_wastes_stake',
  WaterStake = 'track_water_stake'
```

**Comment by pierrecamilleri** [comment]
J'ai poursuivi le nettoyage dans #603, et je me suis permis d'éditer directement dans le corps du ticket pour enlever les questions jamais posées.

**Comment by ColineLebaratoux** [comment]
https://mission-transition-ecologique.beta.gouv.fr/questionnaire/autodiag
https://mission-transition-ecologique.beta.gouv.fr/questionnaire/autodiag/siret

  BuildingProperty = 'track_structure_building_property', // propriétaire ou locataire ? 
  ContactForm = 'track_form',  
  EnergyReductionPriority = 'track_energy_reduction_priority', 
  Goals = 'track_goals',
  QuestionnaireRoute = 'track_questionnaire_route', // Quel parcours ? **=> 'choix_du_parcours**
  MobilityWishes = 'track_mobility_wishes', **=> 'mobilité**
  Results = 'track_results', **=> 'résultats'**
  Sectors = 'track_sectors', **=> 'activité'**
  Siret = 'track_siret', **=> 'siret'**
  StrategyAudits = 'track_strategy_audits', => 
  StrategyAuditsSelect = 'track_strategy_audits_select',
  StructureRegion = 'track_structure_region',
  StructureWorkforce = 'track_structure_workforce', // Effectif
  WastesMaterials = 'track_wastes_materials',
  WastesSorting = 'track_wastes_sorting',
  WastesStake = 'track_wastes_stake',
  WaterStake = 'track_water_stake'

**Comment by ColineLebaratoux** [comment]
@yvalentin, j'ai tenté des reformulation, à minima il s'agit de traduire en français puisque c'est un outil local. 
Tu en penses quoi ?

**Comment by yvalentin** [comment]
> [@yvalentin](https://github.com/yvalentin), j'ai tenté des reformulation, à minima il s'agit de traduire en français puisque c'est un outil local. Tu en penses quoi ?

Pour moi, ça me va sauf les accents... Je pense les enlever ? (@ColineLebaratoux)
