### ISSUE TITLE
Modifier le titre de la page pour le SEO

### ISSUE THREAD

**Issue by jrayneau** [betagouv/transition-ecologique-entreprises-widget#615]
Le titre est actuel est trop long [Mission Transition écologique - Aides et financements TPE ...]
Il faudrait le changer en "Transition écologique - Aides et financements TPE & PME"

**Comment by JulienParis** [comment]
pour validation : https://tee-preprod-pr632.osc-fr1.scalingo.io/

**Comment by jbledevehat** [comment]
Je ne vois pas comment pouvoir tester cela avec une URL de preprod. Donc validons.

**Comment by JulienParis** [comment]
> Je ne vois pas comment pouvoir tester cela avec une URL de preprod. Donc validons.

tu peux tester ici : https://www.opengraph.xyz/url/https%3A%2F%2Ftee-preprod-pr632.osc-fr1.scalingo.io%2F
