### ISSUE TITLE
Sur le parcours "je ne sais pas par où commencer" ajouter stystématiquement le bandeau thématique 

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#616]
Ajouter le bandeau thématique systématiquement au dessus de chaque question

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/c5466443-4110-4fe2-9825-75bf6635c4d8)

**Comment by JulienParis** [comment]
preview sur : https://tee-preprod-pr641.osc-fr1.scalingo.io/
