### ISSUE TITLE
Créer un Sitemap

### ISSUE THREAD

**Issue by JulienParis** [betagouv/transition-ecologique-entreprises-widget#618]
Préconisation Google (pour Google Search Consol) et pour les bonnes pratiques BetaGouv (Dashlord)

**Comment by yvalentin** [comment]
https://github.com/jbaubree/vite-plugin-sitemap

**Comment by ttdm** [comment]
J'ai une première implémentation fonctionnelle. 

Côté technique, Il y a un point qui peut être amélioré par rapport à la manière dont je liste et charge les programmes.

Côté données, tout l'intêret de la sitemap réside dans les informations supplémentaires qu'on apporte aux robots et notamment la fréquence de mise à jour et l'importance de chaque page. 
Le tableau ci dessous récapitule les infos pour l'instant contenues dans la sitemap : 

| Page  | Priorité | Fréquence de mise à jour |
| ------------- | ------------- | ------------- |
| Accueil  | Maximale  | Hebdo  |
| Questionnaire  | Moyen  | Mensuel  |
| aides-entreprise  | Moyen  | Mensuel  |
| ajouter-une-aide-entreprises  | Moyen  | Mensuel  |
| echanger-avec-un-conseiller  | Moyen  | Mensuel  |
| accessibilite  | Moyen  | Mensuel  |
| mentions-legales  | Basse  | Mensuel  |
| donnees-personnelles  | Basse  | Mensuel  |
| Programmes (95pages) | Moyen Plus  | Mensuel  |
| nouvelle page par défaut | Moyen  | Mensuel  |

A noter que les programmes constituants la grande majorité des pages et l'importance devant être équilibrée (tout ne peut pas être important, c'est contre productif pour le SEO), il ne peuvent pas etre mis au dessus de [moyen plus] terme d'importance.

**Comment by jrayneau** [comment]
C'est tout pour moi !
