### ISSUE TITLE
Modifier dans la plateforme et la fiche produit france-transition@beta.gouv.fr par le nouveau mail

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/transition-ecologique-entreprises-widget#619]
- [x] Dans les pages de la plateforme 
   - [x] Supprimer dans la page dispositifs : " Pour toute question, vous pouvez nous contacter à "france-transition(at)beta.gouv.fr"  "
   - [x] Changer l'adresse mail dans les pages Accessibilité, Données perso... du footer
   - [x] Voir s'il y a l'adresse mail ailleurs...
- [x] Dans la fiche produit beta.gouv.fr par @jbledevehat

**Comment by JulienParis** [comment]
@jbledevehat du coup c'est quoi le bon email ?

**Comment by jbledevehat** [comment]
C'est [contact@mission-transition-ecologique.beta.gouv.fr](mailto:contact@mission-transition-ecologique.beta.gouv.fr)

**Comment by jbledevehat** [comment]
Voici les retours de @ColineLebaratoux 

remplacer "france-transition@beta.gouv.fr" par "contact@mission-transition-ecologique.beta.gouv.fr"

- au niveau du bandeau sur les pages du footer


![Image](https://github.com/orgs/betagouv/projects/54/assets/47628484/7c134e79-589c-43b7-b9a2-a16709e592d9)

- Sur les mentions légales et sur la page accessibilité
![Image](https://github.com/orgs/betagouv/projects/54/assets/47628484/a7d84718-0004-474b-8627-ce070dbfc081)


![Image](https://github.com/orgs/betagouv/projects/54/assets/47628484/57a8e758-9c82-438d-b08c-18ada9f2e722)



- au niveau du message d'erreur 

![Image](https://github.com/orgs/betagouv/projects/54/assets/47628484/5d96c0a3-af48-4bbe-aafe-e09e1a33f318)

**Comment by jbledevehat** [comment]
@JulienParis Il faudrait vérifier s'il y a d'autres endroit possible.

**Comment by JulienParis** [comment]
preview : https://tee-preprod-pr636.osc-fr1.scalingo.io/

**Comment by jbledevehat** [comment]
Rien n'a été modifié dans ton URL @JulienParis 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/22809387/8abfb289-50c4-41f8-9bff-efd46ba75097)
ou autre exemple
https://tee-preprod-pr636.osc-fr1.scalingo.io/donnees-personnelles

**Comment by JulienParis** [comment]
Effectivement il y avait une partie de cette issue qui se résout par des changements dans le code, mais le mail est aussi entré en variable d'environnement sur Scalingo. Modification faite.

Test : https://tee-preprod-pr636.osc-fr1.scalingo.io/donnees-personnelles

**Comment by yvalentin** [comment]
Est-ce qu'il faut aussi changer ici ?
https://www.notion.so/accelerateur-transition-ecologique-ademe/Accueil-93eb32ce96dc464cbdbe2154e13c8eea
