### ISSUE TITLE
Certain dispositif n'ont plus de conditions d'éligiblité d'affiché

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/transition-ecologique-entreprises-widget#640]
Nous avons certains dispositifs qui n'ont plus de conditions d'éligibilité d'affiché.
Exemple : 
- https://mission-transition-ecologique.beta.gouv.fr/aides-entreprise/performa-environnement
- https://mission-transition-ecologique.beta.gouv.fr/aides-entreprise/tremplin

Peut-être est-ce dû à l'absence de description longue ?
@corriger rapidement

**Comment by yvalentin** [comment]
Lien pour validation functionnel: https://tee-preprod-pr642.osc-fr1.scalingo.io/

**Comment by jbledevehat** [comment]
Ok à envoyer pour corriger au plus vite
