### ISSUE TITLE
🖥 Corrections fiche dispositif + formulaire de contact

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#66]
- [x] Remettre le formulaire sur la fiche dispositif. Cf new UI proposée sur la maquette Figma (mettre le téléphone avant le siret)

- [x]  Supprimer tous les textes d'exemple sur le formulaire de contact "Camille" "Dujardin" "0605040302""je souhaite connaitre les aides pour installer des éoliennes" dans le formulaire de contact, qui alourdissent le formulaire. 
(sauf SiRET pré-rempli = gain de temps pour l'utilisateur)

![Image](https://user-images.githubusercontent.com/47628484/252682277-0baed7f2-8ecd-48d6-b7d0-ca404c1b62f6.png)

- [x] UI : Corriger la couleur du titre de la page expertise > bleu foncé 000091
- [x] UI : fixer une hauteur max de l'image à côté du titre (cf figma)
- [x] UI : "au programme" + numérotation 1/2/3/4...

- [x] Mettre à jour les illustrations à utiliser pour les dispositifs (sur la page résultat et la page dispositif). 
solution temporaire : Que penses-tu de partir sur une petite bibliothèque d'illustrations à placer random pour illustrer chaque dispositif ? (cf figma 02 - autodiag/résultat)
A commencer par ces 3 premières images : 
https://drive.google.com/file/d/1cdW7gSXoI0OGimbzv8IKvLKk0BCltk8u/view?usp=drive_link
https://drive.google.com/file/d/1BFSkxY6BM1IqA6-QLMwC5rVYIzXFeZ3m/view?usp=drive_link
https://drive.google.com/file/d/1w_ubTvWlnCoqKjDHghE4E45ufyAArYF8/view?usp=drive_link

**Comment by JulienParis** [comment]
Changes integrated in PR #80
