### ISSUE TITLE
🖥 Navigation formulaire : validation automatique et scroll vertical

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#68]
**1) Créer une validation automatique entre chaque question.** 
règles de navigation : 
- ajouter un bouton "ok" et la mention "appuyer sur entrée" sur desktop en alternative
- imposer la validation au clic sur ok uniquement lorsqu'il y a un texte à saisir / une selection multiple 

**2) Changer la navigation horizontale pour une navigation "verticale" à la typeform** 
- mettre en place une animation avec un défilement des questions de haut en bas (parfait pour la navigation mobile)
- permettre une navigation top down - down top

**3) Revoir le comportement du fil d'arianne par thématiques cliquables**
- garder en mémoire les choix précédents 

références : 
https://www.typeform.com/templates/t/market-research/?attribution_user_id=80642cc0-120a-4d7f-a54f-da0276b0a68f
https://www.teamzero.com/safety-ideas

**Comment by pierrecamilleri** [comment]
Relevé de décision: 

- @JulienParis  regarde si la navigation Typeform est nettement plus complexe que le scroll to top ou pas. Si c'est le cas, on priorise uniquement le scroll to top, sinon, la navigation typeform.

**Comment by JulienParis** [comment]
Tips / refs : 

- CSS based transitions : https://vuejs.org/guide/built-ins/transition.html#css-based-transitions

**Comment by JulienParis** [comment]
@ColineLebaratoux Premiers tests de transitions de track en track sur staging : https://staging.transition-ecologique-des-entreprises.incubateur.net/#
