### ISSUE TITLE
Suppression du filtre par thématique sur la page de résultats "j'ai un objectif en tête"

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#694]
- [x] supprimer ou masquer le (re)filtre thématique sur la page de résultats "j'ai un objectif en tête"

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/77ca1642-9609-4f18-8c09-22b784606f9d)

**Comment by yvalentin** [comment]
https://tee-preprod-pr710.osc-fr1.scalingo.io/
