### ISSUE TITLE
Matomo x widget

### ISSUE THREAD

**Issue by JulienParis** [betagouv/transition-ecologique-entreprises-widget#8]
L'objectif est de permettre de suivre le funnel de l'utilisateur sur le parcours.
Le moyen : ajouter des événements Matomo sur chaque étape

**Comment by JulienParis** [comment]
@jbledevehat @jrayneau quels est le lien vers le matomo utilisé actuellement ?

**Comment by JulienParis** [comment]
Demande faite sur le airtable + documentation ajoutée (proposée) sur le repo de la doc globale de betagouv : https://github.com/betagouv/doc.incubateur.net-communaute/pull/99

**Comment by JulienParis** [comment]
Je mets ça juste comme une question ouverte. D'après les stats Matomo de mission-transition il y a eu 2 pics assez clairs de fréquentation depuis le début de mission transition, je me demande à quoi ils correspondent exactement =>

cf [lien vers les stats](https://stats.data.gouv.fr/index.php?module=CoreHome&action=index&idSite=194&period=range&date=previous30#?period=range&date=2021-08-17,2023-06-04&category=Dashboard_Dashboard&subcategory=1&idSite=194)

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/3dbeb0fd-756c-4084-9c11-cce76a555695)
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/7e15d422-4654-48e8-aaea-1810c46c9831)
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/82b5dd19-92b4-4cb1-b936-fc7faf1d3777)

**Comment by jbledevehat** [comment]
A mon sens il nous faut connaitre principalement le trafic de visiteur unique sur les 3 premières entrées et sur les niveaux suivants (nombre/proportions) jusqu'au formulaire. Ainsi que le taux de sortie sur ces mêmes pages.

**Comment by JulienParis** [comment]
Les événements Matomo sont composés de [la façon suivante](https://matomo.org/faq/reports/the-anatomy-of-an-event/) : 

```
└ Category (required)
    └ Action (required)
        └ Name (optional-recommended)
            └ Value (optional)
```

Côté code ils sont [envoyés de la manière suivante](https://matomo.org/faq/reports/implement-event-tracking-with-matomo/) : 

```js
const _paq = window._paq
_paq.push(['trackEvent', eventCategory, eventAction, eventName, eventValue])
```

Suite à la discussion d'hier avec @jrayneau on s'est mis d'accord pour configurer Matomo de façon à pouvoir savoir en priorité : 

1. Combien de personnes visitent l'outil (trafic) : mesures de fréquentation (visiteurs uniques, etc...) enregistrée par défaut par Matomo
2. Combien de personnes commencent à utiliser le parcours : premier clic dans le questionnaire (première action dans la première piste de questions)
3. Combien de personnes finissent le parcours : arrivée sur la piste des résultats
4. Combien de personnes remplissent et envoient le formulaire : bouton CTA de fin de formulaire

Pour illustrer quand une personne va cliquer sur une réponse dans une piste de questions (ici la piste "track_need" des besoins), ça donnerait quelque chose du genre : 

```
└ Category          --> Nom du domaine utilisé / ex. : "mission-transition.beta.gouv.fr" ou "transition-ecologique-des-entreprises.beta.gouv.fr"
    └ Action        --> Famille d'action  / ex. : "questionnaire"
        └ Name      --> Sous-famille d'action / ex. : "track_needs"
            └ Value --> Valeur d'action envoyée / ex. : "starting"
```

ou bien pour ce qui est de l'action envoyée lors du clic sur le bouton d'envoi du formulaire : 

```
└ Category          --> Nom du domaine utilisé / ex. : "mission-transition.beta.gouv.fr" ou "transition-ecologique-des-entreprises.beta.gouv.fr"
    └ Action        --> Famille d'action  / ex. : "form"
        └ Name      --> Sous-famille d'action / ex. : "send_form"
            └ Value --> Valeur d'action envoyée / ex. : ""
```

**Comment by JulienParis** [comment]
PR en cours #28 / MR de `j-matomo` $\to$ `staging` pour commencer à faire les choses plus proprement

**Comment by JulienParis** [comment]
Pour info j'ai intégré un petit bout de script complémentaire au script de base de Matomo pour être raccord avec les recommandations de la CNIL : 

Refs : 

- [How do I configure Matomo without tracking consent for French visitors (CNIL exemption)?](https://matomo.org/faq/how-to/how-do-i-configure-matomo-without-tracking-consent-for-french-visitors-cnil-exemption/)
- [Guide pdf](https://www.cnil.fr/sites/default/files/atoms/files/matomo_analytics_-_exemption_-_guide_de_configuration.pdf) + [Guide CNIL pour Piwik](https://www.cnil.fr/sites/default/files/typo/document/Configuration_piwik.pdf)
- [Matomo exempt from tracking consent in France](https://matomo.org/blog/2021/10/matomo-exempt-from-tracking-consent-in-france/#more-46769)
