### ISSUE TITLE
🖥  Correction responsive : marge formulaire / header

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#84]
- [x] réduire l'espacement en haut du formulaire
- [ ] supprimer le header sur la partie formualaire, (uniquement une flèche back + fil d'arianne) [figma](https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=1179%3A144269&mode=design&t=8CGnLH63wT4ky3YW-1)

![Image](https://user-images.githubusercontent.com/47628484/254818229-d619afa9-3317-485e-b132-e5ba43888022.jpg)

**Comment by JulienParis** [comment]
Note : concernant la suppression du header lors de l'apparition de la page de formulaire le problème est le suivant.

Le header en preprod et en prod est un header propre au widget, mais il est possible de désactiver ce header via une propriété du bloc html du widget => 

```html
      <gov-aid-tree-app
        id="main-widget"
        show-header="false"   <---- cette propriété
        show-stepper="true"
        show-footer="true"
        show-message="true"
        seed="track_needs"
        locale="fr"
        dataset-url="/public/data/eco-aides.json"
        max-depth=3
        debug-switch="false"
        debug="false"
        >
      </gov-aid-tree-app>
      <script type="module" src="/src/main.ce.ts"></script>
```

Le widget intégré actuellement dans `mission-transition` (la prod du site `mission-transition`) a la propriété de header désactivée, c'est-à-dire que le widget intégré dans `mission-transition` ne contient pas de header  

Le header qu'on voit dans `mission-transition` est le header existant du site en php. Le widget - qui est intégré au sein du html de `mission-transition` - ne peut pas donc interagir avec ce header.
