### ISSUE TITLE
🖥 [BUG] La numérotation à la section "au programme" sur la fiche résultats n'apparaît pas sur Safari

### ISSUE THREAD

**Issue by pierrecamilleri** [betagouv/transition-ecologique-entreprises-widget#92]
![Image](https://user-images.githubusercontent.com/47628484/256252922-40a55eda-b49e-42b3-9fcb-dddd881c106f.PNG)

[cf figma ](https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=996%3A87630&mode=design&t=nRlsgAIdthPiwsc4-1)

**Comment by JulienParis** [comment]
Problème apparaît sur Safari / pas sur Firefox

**Comment by JulienParis** [comment]
Fix préparé sur branche dédiée + PR : #97 

Preview déployée en staging : https://staging.transition-ecologique-des-entreprises.incubateur.net/
